### ISSUE TITLE
Probleme mit Start des lokalen Servers (4.4.146)

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#102]
Wenn man nach dem Start von lecturePresenter das erste Mal versucht den Messenger zu starten, scheitert das reproduzierbar.
Wenn man es dann gleich nochmal versucht, klappt es dann (auch mehrfaches Stoppen und erneut starten klappt dann).
Interessant dabei ist: die Windows Firewall meldet sich bei dem ersten Versuch auch gar nicht (wenn keine Regeln eingetragen sind), sondern erst beim zweiten Startversuch (der dann auch scheitert, falls die entsprechenden Regeln in der Firewall noch fehlen).

Für mich sieht das so aus als ob entweder beim ersten Startversuch irgendwelche Variablen falsch initialisiert sind oder aber einfach nur das Timeout zu kurz ist.

**Comment by devopvoid** [comment]
Timeout ist zu kurz. Momentan 2 Sekunden. Hängt vom Rechner ab, wie schnell er den lokalen Server startet. Wenn dann die Java-Klassen einmal geladen sind, geht beim zweiten Versuch der Start des Servers schneller. Werde das Timout auf 8 Sekunden stellen.

**Comment by Andy-Schuerr** [comment]
Ach klar, das Laden der Klassen bzw. vermutlich auch Just in Time Compilation verzögert den ersten Start. Logisch1

Von: Alex Andres ***@***.***>
Gesendet: Dienstag, 25. Mai 2021 11:58
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] Probleme mit Start des lokalen Servers (4.4.146) (#102)


Timeout ist zu kurz. Momentan 2 Sekunden. Hängt vom Rechner ab, wie schnell er den lokalen Server startet. Wenn dann die Java-Klassen einmal geladen sind, geht beim zweiten Versuch der Start des Servers schneller. Werde das Timout auf 8 Sekunden stellen.

**Comment by devopvoid** [comment]
Duplicate of #96
