### ISSUE TITLE
Eingebetteter Messenger-Server nicht stabil (4.4.146):

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#103]
Die folgenden sporadisch auftretenden Probleme sind leider nicht reproduzierbar:
- Manchmal wird die Messenger-Seite im Browser nur nach eine "reload" geladen (das Problem tritt bislang ausschließlich und
   leider nur sporadisch und nichtreproduzierbar mit Firefox auf)
- Beim ersten Versuch den eingebetteten Messenger-Server von mehreren Clients aus zu nutzen konnte ich den Server
   nicht mehr runterfahren (Logdatei anbei von mehreren Versuchen der Nutzung des Messenger-Servers). Leider
   ist auch dieses Problem nicht reproduzierbar.

[presenter.log](https://github.com/lectureStudio/lectureStudio/files/6537902/presenter.log)

PS: reproduzierbares, aber auch erwartbares Verhalten: wenn man die Messenger-Seite bei laufendem Messenger-Server im Browser geladen hat und der Messenger-Server gestoppt und neu gestartet wird, dann muss man erst die Seite im Browser
neu laden bevor man wieder Nachrichten verschicken kann. Das lässt sich wohl nicht vermeiden und dürfte ja auch ein exotischer Fall sein (wer startet schon während einer laufenden Veranstaltung den Messenger-Server neu).

**Comment by devopvoid** [comment]
Vielen Dank für das Log. Auch wenn es nicht reproduzierbar ist, geht das Problem daraus hervor.

Zum ersten und letzten Punkt: Es ist tatsächlich so, dass die HTML-Seite nicht automatisch aktualisiert wird, wenn ein Quiz (neu) gestartet wird oder Nachrichten aktiviert werden. Das lässt sich realisieren. Man muss hier aber im Falle des lokalen Servers - wegen der Performanz - beachten, dass alle Clients eine ständige Verbindung zum Server aufrechterhalten, um auf dem Laufenden zu bleiben.

**Comment by Andy-Schuerr** [comment]
Vielleicht kann man die Seite bzw. ihre Verbindung zum Server nur dann „aktualisieren“, wenn irgendeine Interaktion damit passiert – statt in regelmäßigen Abständen?

Beim Streaming wird sich das Ganze sowieso vermutlich anders verhalten und im Zuge des Streamings immer auch Events übertragen für gestartetes/gestopptes Quiz bzw. Messenger, sodass dann die entsprechenden Tabs entsprechend erscheinen (aktiviert werden) bzw. verschwinden (deaktiviert werden)?

              AS

Von: Alex Andres ***@***.***>
Gesendet: Dienstag, 25. Mai 2021 12:11
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] Eingebetteter Messenger-Server nicht stabil (4.4.146): (#103)


Vielen Dank für das Log. Auch wenn es nicht reproduzierbar ist, geht das Problem daraus hervor.

Zum ersten und letzten Punkt: Es ist tatsächlich so, dass die HTML-Seite nicht automatisch aktualisiert wird, wenn ein Quiz (neu) gestartet wird oder Nachrichten aktiviert werden. Das lässt sich realisieren. Man muss hier aber im Falle des lokalen Servers - wegen der Performanz - beachten, dass alle Clients eine ständige Verbindung zum Server aufrechterhalten, um auf dem Laufenden zu bleiben.

**Comment by devopvoid** [comment]
> Vielleicht kann man die Seite bzw. ihre Verbindung zum Server nur dann „aktualisieren“, wenn irgendeine Interaktion damit passiert – statt in regelmäßigen Abständen?

Das würde mit WebSockets / Server Sent Events funktionieren. Damit wird die HTML-Seite nicht in regelmäßigen Abständen aktualisiert, sondern nur, wenn sich z.B. ein Quiz geändert hat oder gestoppt wurde. Dafür müssen die Clients (Browser) die Verbindung trotzdem aufrechterhalten, um die Event zu empfangen. Bei z.B. 300 Clients kann es sich schon auf die Performanz des lokalen Servers auswirken.

> Beim Streaming wird sich das Ganze sowieso vermutlich anders verhalten und im Zuge des Streamings immer auch Events übertragen für gestartetes/gestopptes Quiz bzw. Messenger, sodass dann die entsprechenden Tabs entsprechend erscheinen (aktiviert werden) bzw. verschwinden (deaktiviert werden)?

Das Streaming läuft dann separat und die jeweiligen Dienste unabhängig voneinander, wie jetzt schon Quiz/Messenger. Das funktioniert nach dem selben Prinzip wie oben beschrieben. Wenn ein Stream startet, dann erscheint auch ein Tab oder Link zum Stream, wie mit Quiz und Messenger. Wenn der Stream endet, geht der Tab/Link weg.

**Comment by devopvoid** [comment]
Closing due to newly created issue #112
