### ISSUE TITLE
Vektorplayer  (V. 4.4.146): Folienvorschau gibt Annotationen anders wieder als Html-/mpeg4-Player

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#104]
Die redesignte Folienvorschau im lectureEditor und hmtl-/mpeg4-Player funktionieren jetzt so wie ich das erwarten würde.
Es wird immer der Endzustand einer Folie in der Vorschau angezeigt und es werden die Folien expandiert angezeigt, 
wenn sie vor dem Folienwechsel expandiert waren.

Der Vektorplayer verhält sich diesbezüglich aber noch anders in der Vorschau:
- Es werden nie expandierte Folien angezeigt
- Es wird immer der Zustand der Folie direkt nach dem Wechsel auf die Folie statt direkt vor dem Wechsel auf die
  nächste Folie angezeigt.

**Comment by devopvoid** [comment]
Duplicate of #44

**Comment by Andy-Schuerr** [comment]
Die Folienvorschau im lecturePlayer (Vektor-Format) ist im Augenblick (Version 4.4.164) komplett korrupt. Ich deshalb dazu einen neuen Bug-Report erstellt. Dieser Bug-Report hier ist irrelevant geworden und wird deshalb geschlossen.
