### ISSUE TITLE
Fehlerhafte Folien in Aufnahmen

### ISSUE THREAD

**Issue by elenziat** [lectureStudio/lectureStudio#105]
Leider ist das Problem #45 noch nicht ganz gelöst.

Eben habe ich mit der Version 4.4.136 eine Aufzeichnung gemacht, und dabei hat es wieder das Problem gegeben, dass zwei Folien nicht korrekt gespeichert wurden. Es hat in diesem Fall zwar keine "komischen" Formen gegeben, sondern die Folie wird weitestgehend weiß angezeigt. Im Ergebnis macht es aber keinen Unterschied.

- Immer wenn das passiert, sind mindestens zwei Folien "verbunden". (Das habe ich bei #45 noch nicht vollständig beschrieben, da es mir erst danach bewusst geworden ist.) D.h. es ist auch nicht immer möglich, dies mit dem Austauschen einer Folie zu "retten".
- Ich hatte zwischenzeitlich gehofft, dass es sich mit dem Setzen des Zeitlimits für die Seitenaufzeichnung auf 0ms behoben hätte. So waren die beiden letzten Aufzeichnungen fehlerfrei, nachdem davor zeitweise keine sinnvolle Aufzeichnung möglich war, da es mehrere Fehlstellen an ungünstigen Stellen gegeben hat.

Leider ist dieses Verhalten schwer zu reproduzieren. Nur dass es bei mir bei längeren Aufnahmen auftritt, kann ich mir leider fast sicher sein.

Ich weiß nicht, ob es eine Rolle spielt, aber meine Java-Version ist "openjdk 11.0.8 2020-07-14".

Und hier der Inhalt des log-Files des lecturePresenters:
[presenter.log](https://github.com/lectureStudio/lectureStudio/files/6540375/presenter.log)

**Comment by devopvoid** [comment]
Hatte gehofft, dass es endgültig behoben sei. Hier macht die Bibliothek PDFBox Probleme.

Für den Versuch den Fehler zu reproduzieren bräuchte ich noch weitere Information:
- Wurden die Folien schnell gewechselt? Nur in eine Richtung oder auch vor und zurück?
- Könnte ich vielleicht noch den Foliensatz bekommen bei dem der Fehler auftrat?

> Ich weiß nicht, ob es eine Rolle spielt, aber meine Java-Version ist "openjdk 11.0.8 2020-07-14".

Das spielt keine Rolle. Da in lectureStudio eine eigene Java Runtime (Version 14) integriert ist.

**Comment by elenziat** [comment]
> - Wurden die Folien schnell gewechselt? Nur in eine Richtung oder auch vor und zurück?

Ja, in beide Richtungen. Vorwärts wurden beide Folien korrekt aufgenommen. Das kurze Zurückgehen hat es dann aber nicht ganz verkraftet. (Prinzipiell scheint es aber nicht an das "Zurückgehen" gebunden zu sein.

> - Könnte ich vielleicht noch den Foliensatz bekommen bei dem der Fehler auftrat?

Natürlich. Ich schicke Dir den per Mail.

**Comment by devopvoid** [comment]
> Is PDFBox thread safe?
> No!

🤕 

Bugfix in Arbeit

**Comment by elenziat** [comment]
Mit der Preview-Version 4.4.153 hat es gerade leider wieder eine fehlerhafte Folie in der Aufnahme gegeben. Diesmal war aber nur eine einzelne Folie betroffen, so dass diese einfach ausgetauscht werden konnte.

Interessanterweise zeigt das als PDF-gespeicherte Dokument auch fehlerhafte Folien. Aber andere.

Logfile und Dateien liegen am bekannten Ort.

**Comment by elenziat** [comment]
Die letzten Aufzeichnungen haben bei mir jetzt wieder einwandfrei funktioniert! (lecturePresenter 4.4.158)

**Comment by devopvoid** [comment]
Closing with the prospect that this problem is solved for good.
