### ISSUE TITLE
Echtzeitaudiofilter für Aufnahmen unter schlechten Bedingungen

### ISSUE THREAD

**Issue by arg0n1s** [lectureStudio/lectureStudio#115]
### Problem:
Für Aufnahmen in stillen Umgebungen mit wenig Hallcharakteristik, unter Verwendung eines guten Mikrofons und einer dedizierten Soundkarte, kann mit dem Tool Aufnahmen mit sehr guter Tonqualität produzieren. Leider sind solche Verhältnisse im universitären Bereich selten gegeben. Beispielsweise bei Live-Aufzeichnungen während Vorlesungen befindet man sich üblicherweise in Hörsälen mit sehr schlechter Klangcharakteristik, was einerseits zu Hall führt und andererseits, durch die notwendige Verstärkung, zu Rückkopplungen führt. Selbst ohne das Verstärkungsproblem hat man in Büros meistens mit Hall und stark einstreuenden Nebengeräuschen oder einfach schlechter Aufzeichnungshardware zu kämpfen.
Eine nachträgliche Bearbeitung der Tonspur mit z.B. Audacity kann durch Andwendung von Kompressor-Filtern oder Peak-Limitern noch einiges Retten, das ist aber oft recht aufwändig und erfordert Einarbeitungszeit.

### Lösungsvorschlag:
Zur Lösung dieser oben beschriebenen Probleme würde ich eine kleine ausgewählte Menge von Audiofiltern vorschlagen, die man sich als Aufzeichnender konfigurieren kann, die dann in Echtzeit während der Aufzeichnung das Tonsignal filtern. [OBS](https://obsproject.com/) ist beispielsweise ein Tool, dass das sehr gut kann und dabei benutzerfreundlich bleibt, leider sind die Dateigrößen nach der Aufzeichnung im Vergleich zu Lecture Studio gewaltig und deshalb keine wirkliche Alternative.

**Typische Filter währen zum Beispiel die folgenden:**

**- Peak-Limiter:** Hiermit kann man automatisch Signalspitzen, die z.B. durch Rückkopplung oder Übersteuerung von Mikrofonverstärkern entstehen abscheiden. Das passiert bei schlechten Mikrofonen (z.B. Laptopmikrofone) sehr häufig und lässt sich nachträglich nur mäßig gut korrigieren.
**- Equalizer:** Hiermit lassen sich ganz bestimmte Frequenzen verstärken oder abschwächen. Damit kann man beispielsweise die Hallcharakteristik eines Raumes ausgleichen oder störende Nebengeräusche bestimmter Frequenzen filtern.
**- Kompressor:** Hiermit lässt sich die Dynamik (also die Lautstärkeunterschiede) einer Tonaufnahme reduzieren, um Beispielsweise kurzeitig sehr laute oder sehr leise Ereignisse zu normalisieren. Eine typische Andwendung ist die Filterung von Übersteuerungen von Verstärkerendstufen (siehe Hörsaalzenario).
**- Gate:** Eines der vielseitigsten Dynamikprozessoren. Mit dem klassischen Noise-Gate kann man beispielsweise Klangereignisse unter bestimmten Lautstärke-Levels filtern, um Grundrauschen zu entfernen (man denke z.B. an Lüftergeräusche o.Ä.). Außerdem kann man Gates dazu benutzen, um starke Konsonantenaussprache (z.B. "S") abzumildern, die auf einer Aufnahme normalerweise zu einem sogenannten "Clip" also einer Übersteuerung führen würden. Man spricht auch vom De-Esser. Auch bei Hall kann man mit einem Gate nachregeln. Da man bei Gates zeitliche Verzögerungen einstellen kann, die genau diese zeitlich verzögerten Klangereignisse modellieren, kann das Gate den Audiokanal schließen und damit Nachhall blockieren.

**Comment by Andy-Schuerr** [comment]
Die inzwischen integrierten Filter sollten erst mal ausreichen!
