### ISSUE TITLE
Presenter (V. 207): Schreiben von Text auf dem Whiteboard funktioniert nicht

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#122]
Das Schreiben von Text auf einem ganz leeren Whiteboard (ohne geöffnete pdfs) funktioniert nicht.  Ich kann in der ersten Textbox drei Buchstaben schreiben, dann ist Ende. Auch in neu erzeugten weiteren Textboxen kann ich dann überhaupt keinen Buchstaben mehr schreiben. Anbei die Logdatei dazu.
[presenter.log](https://github.com/lectureStudio/lectureStudio/files/6829598/presenter.log)

**Comment by maxhuettner** [comment]
Die Texteingabe funktioniert nicht, sofern Tasten gedrückt werden, die auch eine Hotkey-Belegung haben (z.B. a für Laserpointer). Statt der Eingabe des Textes wird die im Hotkey hinterlegte Funktionalität ausgewählt und die Texteingabe beendet.
