### ISSUE TITLE
lecturePresenter lässt sich nicht schließen

### ISSUE THREAD

**Issue by elenziat** [lectureStudio/lectureStudio#123]
Folgendes Problem tritt bei mir mit lecturePresenter 4.4.208 unter Windows auf:

- lecturePresenter starten
- Whiteboard öffnen (bzw. auch ein PDF, das Verhalten ist das gleiche)
- Zwei Striche zeichnen (oder auch etwas mehr. Bei zwei Strichen hat es auch manchmal funktioniert.)
- lecturePresenter schließen (wollen)
-> Es erscheint eine Fehlermeldung (siehe angehängter Screenshot). Klickt man diese weg, bleibt lecturePresenter geöffnet. Wenn man dann wieder versucht es zu schließen, erhält man die gleiche Fehlermeldung. Ebenfalls erhält man diese Fehlermeldung, wenn man über "Datei -> Dokumente abspeichern" das Dokument speichern will. Man muss das Programm mit dem Taskmanager beenden.

Das logfile ist angehängt.

![lecturePresenter_Bug](https://user-images.githubusercontent.com/22983571/126147349-9887b3b3-8be4-48dc-adbc-78298dc491f3.png)

[presenter.log](https://github.com/lectureStudio/lectureStudio/files/6840113/presenter.log)

**Comment by devopvoid** [comment]
Danke für die Meldung. Ist behoben.

**Comment by elenziat** [comment]
Gibt es dazu ein neues Release, oder soll man zunächst wieder eine Version zurückgehen?

**Comment by devopvoid** [comment]
Habe das Release 4.4.213 hochgeladen.
