### ISSUE TITLE
lectureStreamingServer (V 4.4.215): Erweiterungsideen

### ISSUE THREAD

**Issue by devopvoid** [lectureStudio/lectureStudio#125]
1. Dozenten:innen müssen in der ersten Ausbaustufe Lehrveranstaltungen selbst als Streams anlegen (ggf. wird in einer zukünftigen Ausbaustufe dann eine Datenbank aller in TUCaN registrierten Kurse der jeweiligen Dozent*in auf Wunsch hin ausgelesen und man kann dann auswählen welche Kurse neu angelegt werden sollen). 

2. Optional: Einer Lehrveranstaltung (einem Stream) können zusätzliche Dozent:innen zugeordnet werden mit ihren TU-IDs, die dann auch administrative Aufgaben für die betreffenden Kurse erledigen dürfen (z.B. Wiss. Mitarbeiter)?

4. Optional: Wenn das Dozent:innen-Bild nicht per Webcam übertragen wird, kann ein Bild imKonto festgelegt werden, das dann stattdessen angezeigt wird.

5. Optional: Gleiches gilt für Teilnehmer:innen an Lehrveranstaltungen; auch bei Ihnen könnte man ein Bild festlegen, das angezeigt wird, wenn die Webcam ausgeschaltet ist.

**Comment by Andy-Schuerr** [comment]
Teilweise erledigt, teilweise zu niedrige Priorität. Deswegen wird der Issue geschlossen.
