### ISSUE TITLE
lectureStreamingClient/-Server (V 4.4.215): Zuordnung von Lehrveranstaltungen für Studierende

### ISSUE THREAD

**Issue by devopvoid** [lectureStudio/lectureStudio#126]
1. Falls es eine geeignete Schnittstelle zu Moodle gibt, könnte man optional Studierenden nur Zugriff auf die Streams erlauben, für die sie in dem zugehörigen Moodle registriert sind (alternativ: Registrierung in TUCaN für die zugeordnete Lehrveranstaltung ist relevant).

2. Einzelne Studierende (TU-IDs) können für den Zugriff auf bestimmte Streams blockiert werden (bei gravierendem Fehlverhalten) --> Negativliste.

3. Alternativ könnte man eine Idee von Zoom aufgreifen und die Möglichkeit anbieten eine Tabelle von TU-Ids oder Klartextnamen oder ... hochzuladen, die einschränkt, welche Teilnehmer zulässig sind --> Positivliste.

**Comment by Andy-Schuerr** [comment]
Das Hochladen einer Excel-Tabelle mit zugelassenen Kursteilnehmer:innen ist die beste/flexibelste Lösung. Man kann sich nämlich eine Excel-Liste aus Moodle runterladen und diese dann in lectureStudio importieren. Dafür muss der lectureStudio-Server wie folgt erweitert werden:
* Man muss bei den Rollen zwischen registrierten und nicht registrierten Teilnehmer:innen unterscheiden.
* Allerdings muss es dann auch möglich sein, Personen über Ihren Namen (und Email-Adresse?) mit einer Rolle
  zu einem Kurs einzutragen (aus Moodle heraus werden aus guten Gründen nicht die TU-IDs der Teilnehmer eines
  Moodle-Kurses exportiert) statt die TU-ID zu benutzen.
* Unter diesen Voraussetzungen könnte man dann alle einem Kurs zugeordneten Teilnehmer über eine Excel-Tabelle
  hochladen, die neben Vorname(n) und Nachname dann eine Rolle vorgibt (und ggf. zusätzliche Spalten mit Email-Adresse
  etc. besitzen kann)

**Comment by Andy-Schuerr** [comment]
Dieser Issue überlappte stark mit einem anderen Issue zu verschiedenen Login- und Verwaltungsmöglichkeiten von Kurs-Teilnehmer:innen. Die Punkte hier, die in dem anderen Issue noch nicht aufgeführt waren, wurden übernommen. Deshalb kann dieser Issue hier gelöscht werden.
