### ISSUE TITLE
lectureStreamingClient/Presenter (V 4.4.215): Redebeiträge abwickeln

### ISSUE THREAD

**Issue by devopvoid** [lectureStudio/lectureStudio#131]
Manchmal wäre es hilfreich, wenn man bei zu einer gehobenen Hand (angemeldetem Redebeitrag) einen erläuternden Text schreiben könnte. Das würde helfen, mehrere gleichzeitige angemeldete Beiträge in einer sinnvollen Reihenfolge abzuarbeiten.
Die Frage ist, wie dafür die geeignete Benutzeroberfläche im Client aussieht?!

**Comment by elenziat** [comment]
Falls geplant ist, während eines Streams auch aufnehmen zu können, wäre es vielleicht sinnvoll, eine Einstellung zu haben, dass der Ton der Redebeiträge nicht mit aufgezeichnet wird.

**Comment by devopvoid** [comment]
Geht beides gleichzeitig, Aufzeichnen und Streamen. Es wird das gleiche Mikrofon genutzt. Sofern das Mikrofon den Ton der Redebeiträge nicht einfängt, sollte es kein Problem sein.

Vielleicht andersherum, eine Einstellung, um den Redebeitrag in der Aufzeichnung zu haben?

**Comment by elenziat** [comment]
Dann ist es ja im Hinblick auf die Verwertbarkeit des Mitschnittes die sichere Lösung. Andersherum (das Aufzeichnen der Redebeiträge) würde ich nicht als nötig einstufen.

**Comment by Andy-Schuerr** [comment]
Die Diskussion habe ich nicht ganz verstanden. Was ist jetzt die Lösung für die Anforderung, dass Redebeiträge bzw. Diskussionen nicht mit aufgezeichnet werden? Man denkt als Dozent:in daran, die Aufzeichnung jedes Mal zu pausieren? Alternativ könnte man eine Option einführen, die dann dafür sorgt, dass während eines Redebeitrags die Aufzeichnung automatisch pausiert und am Ende wieder aktiviert wird. Ich würde daher diesen Issue (mit niedriger Priorität) als offen belassen.

**Comment by elenziat** [comment]
Ist bei einem Edit des Ursprungsbeitrages versehentlich etwas verloren gegangen? Aktuell erscheint die darauf folgende Diskussion etwas kontextlos.

**Comment by Andy-Schuerr** [comment]
Das kann fürchte ich sein. Ich habe vor ca. einer Woche sich überlappende Teile verschiedener Issues gelöscht, um eine bessere Übersicht zu bekommen. Ob das auch diesen Issue betroffen hat, kann ich mich leider nicht mehr erinnern. Das würde erklären, warum die Diskussion in den Kommentaren teilweise so gar nicht zum eigentlichen Issue-Text passt. Sorry! Da in den Kommentaren jetzt zwei Anregungen für neue Features drinstehen schließe ich diesen Issue und erzeuge statt dessen jeweils einen neuen für die beiden offenen Punkte.
