### ISSUE TITLE
lectureClient-Oberfläche (V 4.4.215): Mikrofon und Kamera

### ISSUE THREAD

**Issue by devopvoid** [lectureStudio/lectureStudio#132]
- Der Lautsprecher kann in der Oberfläche ausgewählt werden und die Lautstärke kann geregelt werden (NICHT OS-Standard-Einstellungen verwenden).

- Auf Wunsch kann ein vorhandenes Mikrophon „angemeldet“ werden, wenn man einem Stream beitritt. Dieses Mikrophon ist erst mal gemutet. Beim Anmelden ist ein Mikrophontest integriert.

- Auf Wunsch kann eine vorhandene Kamera „angemeldet“ werden, wenn man einem Stream beitritt. Diese Kamera ist erst mal gemutet. Beim Anmelden ist ein Kameratest integriert.

- Zustand von Mikrophon und Kamera beim Client (gemutet oder … ) müssen klar ersichtlich sein. 

- Client vergibt oder entzieht die Erlaubnis, dass Mikrophon und ggf. zusätzlich Kamera aktiviert werden.

**Comment by Andy-Schuerr** [comment]
Es fehlt im Client vielleicht noch die Möglichkeit das eigene Mikrofon (schnell) zu muten bzw. zu deaktivieren, um ggf. unerwünschte Übertragung von Audio-Inhalten zu verhindern während ein Redebeitrag läuft. Im Augenblick kann nur auf Presenter-Seite das Mikrofon einer Person mit Redebeitrag aktiviert und deaktiviert werden. Gleiches gilt ggf. auch für die Kamera. Es muss aber genau überlegt werden, wie man das ausgestaltet, damit das Muten von Mikrofon und Kamera auf Presenter-Seite Priorität gegenüber dem Muten von Mikrofon und Kamera im Client hat. 

Eine mögliche Lösung: im Client kann über die Zahnradeinstellung auch das Mikrofon auf "keines" gesetzt werden und man benutzt die Einstellung "keine" für die Kamera um diese im Client zu deaktivieren.

Andere mögliche Lösung: auf der Client-Oberfläche gibt es neben dem Lautsprecher-Symbol auch Symbole für Mikrofon und Kamera, um diese muten. Wenn im Presenter bei einem laufenden Redebeitrag Mikrofon oder Kamera gemutet werden, dann sind die danach entsprechende Symbole auf Client-Seite ausgegraut und nicht veränderbar solange das Muten im Presenter nicht aufgehoben wird. Wenn im Client Mikrofon oder Kamera gemutet werden, dann sind danach die entsprechenden Symbole im Presenter ausgegraut und nicht änderbar solange das Muten im Client nicht aufgehoben wird. 
Das ist aber ziemlich kompliziert.

--> Aufgabe für das Bachelorpraktikum sich da eine gute Lösung zu überlegen, da es ein Teilaspekt der interaktiveren Ausgestaltung der Clients ist???
