### ISSUE TITLE
lectureClient-Oberfläche (V4.4.215): Redebeitrag

### ISSUE THREAD

**Issue by devopvoid** [lectureStudio/lectureStudio#133]
1. Die Möglichkeit einen Redebeitrag (als Alternative zu Chat-Nachricht) anzumelden, falls zumindest ein Mikrophon angemeldet ist (Webcam muss nicht sein). Für diesen Redebeitrag wird der Klartextname der Person übertragen, die den Redebeitrag anmeldet.

2. Ein angemeldeter und nicht abgearbeiteter Redebeitrag kann vom Client wieder zurückgenommen werden.

3. Wenn der Client ein Redebeitraganforderungsfenster annimmt (nicht ablehnt), dann werden angemeldete Kamera und Mikrophon automatisch „demutet“.

4. Wenn der Dozent den Redebeitrag als abgearbeitet markiert, werden Kamera und Mikrophon beim Client wieder automatisch „gemutet“.

5. Die eigentliche Aktivierung und Deaktivierung (muten/unmuten) erfolgt aber von Dozentenseite aus; der Client muss aber jede Aktivierung (Unmuten) nochmal zusätzlich bestätigen.

**Comment by Andy-Schuerr** [comment]
Dieses Issue ergänzt und überlappt andere Issues zum Thema Datenschutz, ... im Projekt lectureStreaming.
