### ISSUE TITLE
lectureStreamingClient (V4.4.215): Dozenten-Stream vorladen und PDFs cachen (Erweiterung: als P2P-Lösung?)

### ISSUE THREAD

**Issue by devopvoid** [lectureStudio/lectureStudio#134]
Wenn man den Presenter mit dem Server für Streaming schon mal deutlich vor „Vorlesungsbeginn“ verbindet und dabei (defaultmäßig) erst mal Mikrophon und Kamera ausschaltet, dann können die Zuhörer sich ebenfalls rechtzeitig vor „Vorlesungsbeginn“ verbinden und schon das pdf runterladen lassen. Dieser Zustand muss den Zuhörern sinnvoll angezeigt werden (man sieht bereits die erste Folie, aber Mikrophon und Kamera sind noch aus).

Orthogonal dazu könnte man auch einmal "heruntergeladene" PDFs beim Client cachen und über Hashsummenprüfung eine Logik integrieren, dass bei einer erneuten Verbindung mit einem Stream erst mal geprüft wird, ob die zu übertragenden PDFs bereits lokal (in der gleichen Version, also mit unverändertem Inhalt) bereits im  Cache vorliegen.

Diese Caching-Lösung könnte man auch in Form eines P2P-Content-Management- bzw. File-Distribution-Systems realisieren. Dann könnten die verschiedenen Clienten (zu einem Kurs oder ggf. auch über Kursgrenzen hinweg) untereinander ein P2P-Netzwerk bilden und die benötigten Dokumente austauschen und damit den Server vor allem zu Beginn eines Streams deutlich entlasten.

**Comment by Andy-Schuerr** [comment]
Dieser Issue hat sich durch neuere Pläne und Ideen erledigt.
