### ISSUE TITLE
Werden Textnachrichten oder Audio-Fragen in die Aufzeichnung mit aufgenommen?

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#139]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by devopvoid** [comment]
Hierzu gibt es bereits eine Diskussion zum Redebeitrag #131

**Comment by Andy-Schuerr** [comment]
Hat sich erledigt. Inzwischen gibt es eine DSGVO-Erklärung, die das genau beschreibt.
