### ISSUE TITLE
Zwei Fortschrittsbalken beim Rendering abwechselnd sichtbar

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#14]
Die Version 4.4.23 des lectureEditors zeigt abwechselnd zwei verschiedene Fortschrittsbalken an beim Rendern:
* den bisherigen Fortschrittsbalken
* einen zusätzlichen Audio-Fortschrittsbalken

Diese beiden Fortschrittsbalken werden abwechselnd im selben Fenster angezeigt, was massiv verwirrt. Zudem springt die Balkenanzeige des Audio-Fortschrittbalkens hin und her (sie flackert) und bewegt sich nicht so "smooth" wie der bisherige Fortschrittsbalken nach rechts.

Lösung: 
* Wenn das Video gerendert wird, dann würde ich den neuen Audio-Fortschrittsbalken komplett weglassen
* Wenn nur das Audio gerendert wird, dann würde ich auch den normalen Fortschrittsbalken benutzen,
  da dem Anwender nicht klar ist (und er auch nicht wissen muss), dass beim Vektorformat nur das Audio zu rendern ist
* Beim Audiofortschrittsbalken scheint Anzeige immer zuerst auf einen Mittelwert gesetzt zu werden bevor sie der
  Balken dann weiter rechts wächst. Dadurch flackert die Anzeige.

**Comment by devopvoid** [comment]
Das ist bereits behoben (Commit 6491ecc) und wird im nächste Release enthalten sein. Die Renderings werden sequentiell behandelt, deren Fortschritte auch in der Reihenfolge angezeigt.
