### ISSUE TITLE
lectureStreaming (V 4.4.215): Audio-Knopf funktioniert nicht

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#151]
Wenn man im StreamingClient den Audio-Mikrofon-Knopf selektiert, dann wird der Ton ausgeschaltet, aber:
- das Icon des Mikrofons wechselt nicht auf eine durchgestrichene Darstellung
- erneutes Selektieren des Knopfs schaltet nicht wieder das Audio ein

Dieses Verhalten ist auf Windows-Plattform mit Firefox und Edge aufgetreten.

**Comment by maxkratz** [comment]
Bin mir nicht sicher, ob das zusammenhängend ist: Als zuhörende Person habe ich das gleiche Verhalten beim Muten des Streams gesehen.

- Lautsprechersymbol auf klicken um "stumm zu schalten" -> Funktioniert
- Erneutes Klicken stellt die Audioverbindung nicht wieder her.

OS: Linux Mint 20.1 x86_64
Browser: Chromium 91.0.4472.164 (Official Build) for Linux Mint (64-bit)

**Comment by Andy-Schuerr** [comment]
Vor 30 Sekunden habe ich genau dazu einen Bug-Report auf github erstellt.

Von: Max Kratz ***@***.***>
Gesendet: Mittwoch, 28. Juli 2021 12:56
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] lectureStreaming (V 4.4.215): Audio-Knopf funktioniert nicht (#151)


Bin mir nicht sicher, ob das zusammenhängend ist: Als zuhörende Person habe ich das gleiche Verhalten beim Muten des Streams gesehen.

  *   Lautsprechersymbol auf klicken um "stumm zu schalten" -> Funktioniert
  *   Erneutes Klicken stellt die Audioverbindung nicht wieder her.

OS: Linux Mint 20.1 x86_64
Browser: Chromium 91.0.4472.164 (Official Build) for Linux Mint (64-bit)

**Comment by Andy-Schuerr** [comment]
Genau das was Max Kratz oben beschrieben hat als Fehler ist das  Fehlverhalten, das ich mit meinem Bug-Report beschreiben wollte (glaube ich).

**Comment by Andy-Schuerr** [comment]
Das hat sich inzwischen durch diverse Korrekturen erledigt bzw. gibt es für verbliebene Probleme präzisere Bug-Reports, die die Ursachen für das Fehlverhalten genauer einkreisen.
