### ISSUE TITLE
lectureStreamingClient (V ???): Überarbeitung der "Knöpfe" Bearbeiten/Löschen/...

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#168]
Bei den Kursen gibt es bislang drei "Knöpfe" bzw. Schaltflächen für "Kopiere URL", "Bearbeiten" und "Löschen". Wie wäre es, wenn

* eine vierte Schaltfläche für "Betreten" (oder ähnlicher Name) des Kurses (das macht klarer was zu tun ist, um den Kurs zu betreten). Die Schaltfläche könnte ausgegraut sein, solange nicht gestreamt wird. Das wäre eine noch klarere Kennzeichnung des Kursstatus im Vergleich zu dem notgedrungen kleinen Streaming-Icon.

* bei der Schaltfläche "Kopiere URL" würde ich das Icon entfernen. Das führt auf meinem Android-Browser DuckDuckGo dazu, dass das diese Schaltfläche viel größer als die anderen angezeigt wird und zerstört das ganze Layout.

**Comment by devopvoid** [comment]
Hat sich dieses Issue schon erledigt?

**Comment by Andy-Schuerr** [comment]
Können wir schließen. Falls normale Nutzer Probleme mit der Oberfläche des Clients haben, werden sie uns das schon melden.
