### ISSUE TITLE
Parts of lines disappear if the drawing direction changes too much.

### ISSUE THREAD

**Issue by simongiegerich** [lectureStudio/lectureStudio#174]
**Describe the bug**
When drawing on the whiteboard, parts of lines disappear if the drawing direction changes too much.

**To Reproduce**
1. Open a whiteboard.
2. Activate the pen.
3. Draw an upside-down V shape (Draw the first line, hold down the mouse button and wait a second, Draw the second line without releasing the mouse button)
4. The point where the two lines intersect will disappear

**Expected behavior**
The line is complete.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/48727367/130106670-9e3c55fc-9f0a-4d5f-90b6-385aa9d44a1f.png)

**Desktop:**
Windows 10

**Comment by Andy-Schuerr** [comment]
Add-On: the sketched problem is only reproducable for thick lines!

**Comment by Andy-Schuerr** [comment]
Der Fehler ist immer noch vorhanden!
