### ISSUE TITLE
Erste Ideen für die Erweiterung von lecturePresenter als Zoom- bzw. Skype-Ersatz

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#188]
Um lecturePresenter als vollwertigen Ersatz für Zoom, Skype oder andere Konferenz-Tools benutzen zu können, fehlen zumindest folgende Funktionen:

- alle Teilnehmer:innen sehen die Liste aller anderen Teilnehmer an einer Konferenz (mit Klarname und ggf. zusätzlich Foto);
  man kann sich dabei an BigBlueButton orientieren, wo man bei der Konfiguration einer Videokonferenz einstellen kann,
  ob alle Teilnehmer eine Kursliste sehen oder nicht (aus Datenschutzgründen könnte man auch zusätzlich einführen,
   dass man Einstellen kann ob Dozent:innen die Teilnehmerliste mit Klarnamen sehen). Interessant ist auch das Feature
   von BBB, dass man die Teilnehmerliste speichern kann (will man das aus Datenschutzgründen, am besten noch mit
   den genauen Uhrzeiten, wann Teilnehmer:innen das Event betreten oder verlassen haben?!).
- WebCam-Bilder aller Teilnehmer:innen können gleichzeitig angezeigt werden oder reicht es, wenn immer nur das 
  WebCam-Bild der Person gezeigt wird, die gerade spricht; das würde einiges an Bandbreite sparen?! Sinnvoll wäre
  vermutlich, dass zwischen priviligierten Teilnehmer:innen = Dozent:innen unterschieden wird, deren Kamerabilder
  parallel angezeigt werden können und normalen Teilnehmer:innen, deren Kamerabild nur bei einem Redebeitrag
  gezeigt wird.
- Redebeiträge von normalen Teilnehmer:innen können ohne Freigabe durch Dozent:innen gestartet werden.
   Ggf. führt man auch drei verschiedene Klassen von Teilnehmer:innen an einem Event ein: die Dozent:innen mit allen
   Rechten, die über Presenter-Instanz zugeschaltet sind sowie priviligierte und normale Teilnehmer:innen mit 
   Browser-Client-Teilnahme. Dann könnte man Rechte für diese beiden Gruppen von Teilnehmer:innen unterschiedlich
   einstellen. 
- Die Chat-Funktionalität wird aufgebohrt: optional sehen alle Teilnehmer:innen die Nachrichten aller anderen Teilnehmer 
   und es wird optional auch das Versenden von Nachrichten nur an bestimmte Teilnehmer:innen unterstützt (siehe eigenen 
   Issue mit Ideen zur Erweiterung der Chat-Funktionalitäten). Zumindest sollte man unterscheiden können zwischen
   Versenden einer Nachricht an die Dozent:innen und Versenden einer Nachricht an alle.
- Es gibt verschiedene Bildschirm-Layouts, die auf verschiedene Anwendungsszenarien angepasst sind (Durchführen einer Präsentation mit Folien und/oder Whiteboard, Online-Konferenz ohne Anzeige von Folien, ... )
- Es gibt eine vordefinierte Schnellumfrage, auf die man mit "Ja", "Nein" und "Enthaltung" antworten kann.
- vorerst out-of-scope: Breakout-Rooms, ...

Alle diese neuen Funktionen müssen sowohl im Browser-lectureClient für die normalen Teilnehmer:innen als auch im lecturePresenter für die Dozent:innen bzw. Teilnehmer:innen mit mehr Rechten (entspricht den Hosts bzw. Organisatoren eines Meetings in Zoom) zur Verfügung stehen.

Diese neuen Funktionen sind alle/größtenteils (in den Einstellungen) optional aktivierbar. Damit das nicht zu unübersichtlich wird, braucht man vermutlich endgültig die Möglichkeit Profile von Einstellungen zu definieren, laden, ändern, löschen, ... . Dann kann es vordefinierte Profile für eine normale Präsentation mit Folien, eine Online-Konferenz mit/ohne Folien-Präsentation etc. geben.
Die Frage ist, "wo" diese neuen Funktionen aktiviert bzw. deaktiviert werden. Geschieht das durch Einstellungen beim Anlegen einer neuen Veranstaltung über den Browser-Client oder/und über Einstellungen im lecturePresenter der Dozent:innen, die die entsprechende Veranstaltung angelegt haben.

Geklärt werden muss auch, wie man den "kostbaren" Bildschirmplatz für die Anzeigeelemente der zusätzlichen Funktionen organisiert. Ideen dazu:

lecturePresenter:
- der Folienanzeigeplatz lässt sich zwischen Anzeige von Folien und Anzeige von WebCam-Kacheln der Teilnehmer umschalten
  (falls Anzeige mehrerer kleiner WebCam-Bilder gleichzeitig überhaupt unterstützt werden soll)
- der Folienvorschaubereich wird vertikal unterteilt in die bisherige Folienvorschau und neue Bereiche für die Anzeige von WebCam-Bildern von besonders wichtigen Teilnehmer:innen (die gerade sprechen oder ... ), Chat-Verläufen, Teilnehmer:innen, ... . Alle Teilbereiche dieses bisherigen Folienvorschaubereichs lassen sich in der Höhe verkleinern bzw. vergrößern bzw. ausblenden (bzw. als eigenständige Fenster abkoppeln und wieder einkoppeln).
- Auf diese Weise lässt sich der Bildschirmplatz an verschiedene Nutzungsszenarien anpassen.

lectureClient:
Der Aufbau des Bildschirms kann ähnlich strukturiert werden wie beim lecturePresenter?!

**Comment by elenziat** [comment]
Wenn es hier auch darum geht, Ideen bzw. Wünsche zu sammeln: Die Funktion, die ich bei Zoom mit am meisten verwende, ist die Möglichkeit, in einem freigegebenen Fenster zu skizzieren. Zum einen, um kleinere Skizzen oder Formeln in einen weißen Bereich des Bildschirms zu schreiben, anstelle die Freigabe zum Whiteboard wechseln zu müssen. Zum anderen, um Hilfestellungen bei der Bedienung von Programmen zu geben, indem ich Menupunkte und Schaltflächen einkreise, bzw. Fehler in Code markiere. Das beschleunigt die Zusammenarbeit immens.

**Comment by Andy-Schuerr** [comment]
Eine Verständnisnachfrage: das jetzt im Wintersemester zur Verfügung stehende Streaming erlaubt natürlich wie bisher Folien beliebig zu annotieren (mit der Option den Rand dafür zu Verbreitern)  sowie den Wechsel im Presenter zwischen Folien und Whiteboard. Die Studierenden sehen das alles sofort im Client und alle Annotationen sind auch weiterhin Bestandteil der Aufzeichnung und der optional gespeicherten PDFs.

Sobald die Screen-Window-Sharing-Funktion unterstützt wird, wird beim Wechsel von Interaktionen mit externen Fenstern (anderer Tools) zurück zum Presenter-Fenster ein Snapshot des "geteilten" Bildschirms oder Fensters erzeugt, denman dann wieder wie eine normale Folien annotieren kann.

Reicht das oder ist der Kommentar oben als Wunsch zu interpretieren, dass auch die ganz normalen Teilnehmer:innen Folien annotieren können sollen etc. ?

**Comment by elenziat** [comment]
Der Wunsch wäre, dass man den geteilten Bildschirm "live" annotieren kann. Das ist sicherlich ein Punkt, der weit über den Einsatzzweck "Präsentation" hinausgeht und in Richtung Zoom-Ersatz zielt. Dieser Use-Case entspringt der Betreuung studentischer Arbeiten über Zoom. Es hilft dabei m. E. sehr, wenn man z.B. eine Stelle in Matlab-Code (der sich auf dem vom Studierenden freigegebenen Bildschirm befindet) einkreisen kann, auf den sich eine Frage bezieht, anstelle über die Zeilennummer und "weiter rechts/weiter links" zu navigieren.

**Comment by Andy-Schuerr** [comment]
Mit der neuen Teilnehmerliste im Client und Presenter sowie den erweiterten Möglichkeiten zum Versenden von Nachrichten mit zugehörigem Rechtesystem sind einige Punkte aus der obigen Diskussion abgehakt. Zudem werden fast alle weiteren Punkte wie das Annotierten angezeigter Dokumente im Client oder das Öffnen eigener Dokumente oder das Sprechen ohne Wortmeldung oder ... durch das gerade laufende Projektseminar (SoSe 2020) abgedeckt. Damit kann diese Diskussion, die keine detaillierte Anforderungsliste ist, geschlossen werden.
