### ISSUE TITLE
lectureEditor: new function to split recordings at a given location in the timeline

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#2]
Splitting recordings which are longer than 20/30 minutes into smaller chunks is very often part of the postprocessing process of a recording. Right now you have to 
1) select the right place in a video for splitting purposes with the "cursor" in the timeline
2) extend the selection to the first part of the recording
3) delete the first part of the recording
4) store the rest (second part of the recording) in a new file
5) undo the deletion of the first part of the recording
6) identify again the place where the split shall take place (the most time-consuming part of the whole procedure)
7) extend the selection to the second part of the recording
8) delete the second part of the recording
9) store the rest (first part of the recording) in a new file

A function would be welcome, where you simply select the position in the timeline where the recording shall be split and press a button. The expected output of this function are two files which have the file name of the just processed recording as a prefix and something like "-1" and "-2" as new postfixes.

**Comment by devopvoid** [comment]
After pressing the button to split, should there appear a file-save-dialog to save the parts? With no visual effect in the timeline?

**Comment by Andy-Schuerr** [comment]
Good question! Probably yes. There is no need for any additional feedback, adjustement, ... . This function is not important, it just saves some seconds of editing time!
