### ISSUE TITLE
Feature request: Guest "account" support

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#216]
**Is your feature request related to a problem? Please describe.**

Since the Corona pandemic, the "Orientierungswoche" (OWO) uses a Moodle course for sharing documents and posting last-minute updates for the students. In the OWO 2020, we had the problem that some of the students (around 12 of ~300) did not have a TU-ID and, therefore, were unable to access the Moodle course without a dedicated guest access key.

**Describe the solution you'd like**

If lectureStudio will be used, e.g., to broadcast an event in a future OWO (or other larger events for new students), chances are high that some of them will not have a TU-ID. Currently, this would exclude them from all lectureStudio streams because there is no guest access (AFAIK). In other streaming solutions, like Zoom or BBB, guest access is easy to grant.

**Describe alternatives you've considered**

Organizers of a stream could contact the HRZ to get guest TU-IDs for the new students. IMO, this is not a good solution:

* The person issuing guest TU-IDs is responsible for them (AFAIK).
* Last year, the students did contact us on the same day the event started -> There is not enough time to go through the bureaucratic process of issuing guest TU-IDs.

**Comment by Andy-Schuerr** [comment]
Einzige sinnvolle Lösung für dieses Problem: 
* Server ist ohne VPN zugänglich (denn wenn jemand keine TU-ID hat, dann kann er/sie auch nicht ins VPN der TU)
* Der Server kann so konfiguriert werden, dass er das Anlegen von Gast-Accounts mit Name, Email-Adresse und Passwort
   zulässt
* Gäste können sich mit ihrem Account auch auf dem Server einloggen und können dann ihren Account wieder löschen
  und sehen alle Kurse, die von Gästen "besucht werden" dürfen
* Es wird ein neues Recht für Kurse eingeführt, das die Teilnahme daran für Gäste erlaubt

**Comment by Andy-Schuerr** [comment]
Dieser Issue wurde in einen anderen Issue integriert, der sich generell mit dem Thema "Verwaltung von Teilnehmer:innen von lectureStudio-Kursen" befasst (White-List, Black-List, Login via Moodle, TUCaN, Gäste-Login, ... ). Dieser Issue hier kann deshalb geschlossen werden.
