### ISSUE TITLE
lecturePresenter (v4.4.170): SIGSEGV after start up on Linux

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#221]
**Describe the bug**
The binary of the latest release from Github (https://github.com/lectureStudio/lectureStudio/releases/tag/v4.4.170) crashes after launching with a segmentation fault (SIGSEGV). The GUI is visible for some seconds before the crash.

**To Reproduce**
1. Download the latest release (v4.4.170) from Github.
2. Extract archive.
3. Run binary, e.g.: `$ ./lecturePresenter`

**Expected behavior**
The binary should start without any errors.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 x86_64, Kernel 5.11.0-34-generic
 - OS: Debian Bullseye (11), Kernel 5.10.0-8-amd64

(I could verify the behavior with a clean installed Debian Linux in a VM.)

**Additional context**
I've attached the error output of the JVM and the application log.

[hs_err_pid1208.log](https://github.com/lectureStudio/lectureStudio/files/7144700/hs_err_pid1208.log)
[presenter.log](https://github.com/lectureStudio/lectureStudio/files/7144733/presenter.log)

**Comment by jomority** [comment]
I can confirm the crash with lecturePresenter on Arch Linux (Gnome, Kernel 5.14.2).

[hs_err_pid9986.log](https://github.com/lectureStudio/lectureStudio/files/7145224/hs_err_pid9986.log)
