### ISSUE TITLE
Live-Rückmeldung während Aufzeichnung, dass Mikrophon aktiv ist

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#24]
Ein Nutzer hat gefragt, ob es während der Aufzeichnung eine Live-Rückmeldung gibt, dass das Mikrophon "aktiv" ist.
Vermutlich stellt er sich einen "tanzenden" Balken vor, der Rückmeldung über die Lautstärke der gerade aufgezeichneten Tonspur gibt. Eigentlich keine schlechte Idee, hätte vielleicht bei mir verhindert, dass ich schon mehrfach Aufzeichnungen mit ausgeschaltetem oder falsch platzierten Mikrophon durchgeführt habe, auf denen dann einfach gar nichts zu hören war.

**Comment by devopvoid** [comment]
Vielleicht einen Indikator in die bereits existierende Indikatorenleiste (siehe unten) einbauen? Es gibt aber auch einen Hot-Plug Listener, der eine Meldung anzeigt, wenn ein Mikrofon deaktiviert oder angeschlossen wurde.

<img src="https://user-images.githubusercontent.com/58339654/113735344-742d8f80-96fc-11eb-944d-7230f3447760.png" width="200">

**Comment by Andy-Schuerr** [comment]
Ich hatte mir tatsächlich einen kleinen flackernden Indikator in der Indikatorenleiste vorgestellt, der meinetwegen die Werte schwarz = es tut sich nichts, grau = sehr leise, grün = alles in Ordnung, gelb = etwas laut, rot = sehr laut (oder einfach nur ein Flackern in irgendeiner Farbe in Abhängigkeit von der Lautstärke) annimmt. Mein Problem ist IMMER, dass ich das falsche Mikrofon, das angeschlossen ist benutze, oder das angeschlossene Mikrofon zu leise gedreht habe oder … ☹.

ABER: das ist nicht wichtig genauso wie viele andere Feature-Requests, die ich eingetragen habe (damit sie nicht in Vergessenheit geraten). Wichtig ist, dass wir mit dem Server und dem Streamen vorankommen. Davon hängt es vermutlich ab, ob sich lectureStudio weiter verbreiten wird … .

              AS

Von: Alex Andres ***@***.***>
Gesendet: Dienstag, 6. April 2021 17:22
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] Live-Rückmeldung während Aufzeichnung, dass Mikrophon aktiv ist (niedrige Priorität) (#24)


Vielleicht einen Indikator in die bereits existierende Indikatorenleiste (siehe unten) einbauen? Es gibt aber auch einen Hot-Plug Listener, der eine Meldung anzeigt, wenn ein Mikrofon deaktiviert oder angeschlossen wurde.

[https://user-images.githubusercontent.com/58339654/113735344-742d8f80-96fc-11eb-944d-7230f3447760.png]<https://user-images.githubusercontent.com/58339654/113735344-742d8f80-96fc-11eb-944d-7230f3447760.png>

**Comment by Andy-Schuerr** [comment]
Das hat sich teilweise durch die Testmöglichkeiten von Mikrofon und Kamera beim Starten eines Streams erledigt. Diese Testmöglichkeiten zusätzlich beim Start einer Aufzeichnung anzubieten macht keinen rechten Sinn. Dann würde man das ja doppelt angeboten bekommen, wenn man Streams aufzeichnet.
