### ISSUE TITLE
Automatische Mikrophonpegeleinstellung funktioniert nicht (mehr) - DRINGEND (lecturePresenter 4.4.23)

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#25]
Die automatische Einstellung des Mikrophonpegels in lecturePresenter funktioniert nicht (mehr) wie erwartet. 
Wenn ich unter Windows 10 einen längeren Probesatz spreche, wird der Lautstärkeregler in der Anzeige auf
einen vermutlich passend berechneten Wert gesetzt (tendenziell etwas leise, aber noch okay). 
ABER: wenn man dann eine Probeaufnahme macht, dann wird mit sehr großer Lautstärke aufgenommen.
Mein Eindruck: diese Aufnahmelautstärke ist völlig unabhängig von dem gesprochenen Probesatz immer der gleiche hohe Wert.
Das Problem kann man dadurch beheben, dass man den Pegelregler manuell etwas hin und her bewegt ohne den Pegel zu verändern. Ab dann wird mit der richtigen Lautstärke aufgenommen.

**Comment by devopvoid** [comment]
Sollte nun behoben sein.
