### ISSUE TITLE
lectureClient (V 4.4.XXX): Name der Einstiegs-Webseite zum Streamen ändern

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#264]
Wenn man sich eine Bookmark für die Einstiegs-Webseite zum Streamen anlegt, dann bekommt diese Bookmark den Namen "Einloggen". Bitte einen besseren Namen festlegen wie "lectureStudio" oder ... .

**Comment by devopvoid** [comment]
Der Titel der Webseite hat das folgende Muster: "Inhalts-Titel (z.b. Kurse, Impressum,...) - lectureStreaming"
