### ISSUE TITLE
lecturePresenter (V 4.4.354, Windows 10): Erratisches Verhalten des Dokumente-Speichern-Dialogs

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#292]
Wenn man unter Windows 10 den Presenter mit "Whiteboard" öffnen startet und dann eine Annotation durchführt und anschließend den Presenter durch Klick auf das "Kreuz" rechts oben am Fensterrand schließt, dann wird in ca. 20% der Fälle der Speicherdialog nicht angeboten.  Je mehr Annotationen man erstellt, desto unwahrscheinlicher scheint es zu werden, dass der Speicherdialog nicht angeboten wird. Es sieht fast so aus als ob es da eine beim Programmstart nicht initialisierte Variable gibt die steuert, ob der Speicherdialog angeboten wird.

**Comment by Andy-Schuerr** [comment]
Der Fehler existiert immer noch. Das ist fatal, weil ich mich ganz und gar darauf verlasse, dass mir beim Beenden des Presenters der Speicherdialog angeboten wird. Wenn das nicht der Fall ist und nicht aufpasse, dann sind alle handschriftlichen Notizen auf dem Whiteboard weg.

**Comment by devopvoid** [comment]
Behoben. Zu beachten ist, dass es einen Timeout zum Aufzeichnen von Folien gibt. Nur wenn auf der aller ersten Folie Annotationen schnell ausgeführt werden und Presenter geschlossen wird, alles unter dem Timeout, dann wird der Speicher-Dialog nicht angezeigt. Dieser Timeout lässt sich in den Aufnahme-Einstellungen einstellen.
