### ISSUE TITLE
lecturePresenter (V 4.4.363): Schließen von Dokumenten zerschießt Dokumentespeichern-Funktion

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#297]
Wenn man im laufenden Presenter Dokumente mit Annotationen schließt (Folien oder Whiteboard) und danach den Presenter beendet, wird der Dialog zum Speichern der annotatierten Dokument (einzeln und/oder zusammengeführt) angeboten.

ABER: das Speichern scheitert, weil die zu speichernden Dokumente gar nicht mehr geöffnet und damit alle Annotationen verloren gegangen sind.

Mögliche Lösungen des Problems: 
1) Der Befehl zum Schließen von Dokumenten wird nicht mehr angeboten, Dokumente werden nur noch durch das Beenden des Presenters geschlossen.
2) Dokumente werden nur scheinbar geschlossen (ihre Tabs verschwinden rechts von der Folienvorschau), intern bleiben sie aber weiterhin geöffnet (das muss man dann auch beim erneuten öffnen berücksichtigen) und damit mit all ihren Annotationen erst mal erhalten.
3) Beim Schließen von Dokumenten wird gefragt, ob man ggf. die zugehörigen Annotationen abspeichern will - nur für diese eine betroffene Dokument. Sobald ein Dokument geschlossen ist, wird es bei dem "Dokumente-Speichern"-Dialog überhaupt nicht mehr berücksichtigt.

**Comment by devopvoid** [comment]
Bugfix mit Option 2.

Möchte man dann aber wirklich beim erneuten Öffnen die Annotationen vom alten Dokument beibehalten?

**Comment by Andy-Schuerr** [comment]
Antwort auf Frage zu Option 2: keine Ahnung! Alternativ müsste man beim (scheinbaren) Schließen der Dokumente nachfragen, ob die Annotationen erhalten bleiben sollen oder nicht. Mein Vorschlag: wir lassen das jetzt erst mal so wie es realisiert ist und warten Erfahrungen damit ab. Im Normalfall wird man während einer Präsentation ja sowieso keine Dokumente schließen, sondern nur weitere öffnen. Mein Experiment  mit Öffnen (und Schließen) von ganz vielen Dokumenten war ein Versuch den lecturePresenter zu "crashen".
