### ISSUE TITLE
No packages created - build error on Ubuntu 20.04

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#3]
**Describe the bug**
I've tried to build lectureStudio using an Ubuntu 20.04 environment (inside a Docker container, but that should not make any difference). My set-up steps (from a clean Ubuntu 20.04) are:
* Install java, maven and some utilities: `$ apt-get install -y openjdk-14-jdk-headless maven build-essential zip unzip`
* Install avdev dependencies: `$ apt-get install -y gcc g++ libstdc++6 libpulse-dev libudev-dev libjpeg-dev libv4l-dev`
* Install stylus dependencies: `$ apt-get install -y libx11-dev libxi-dev`
* Link libjawt to /usr/lib: `$ ln -s /usr/lib/jvm/java-14-openjdk-amd64/lib/libjawt.so /usr/lib/libjawt.so`
  * (I've got errors if `libjawt.so` wasn't present in `/usr/lib`.)

The installation of avdev and stylus did *not* show any errors and ran through. On the build of lectureStudio itself (`$ mvn install`) I get the following error:

```
[INFO] ------------------< org.lecturestudio:lect-jpackage >-------------------
[INFO] Building lect-jpackage 1.0.0                                     [26/26]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-license) @ lect-jpackage ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-jgit-buildnumber-plugin:1.2.10:extract-buildnumber (git-buildnumber) @ lect-jpackage ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ lect-jpackage ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (generate-bundle) @ lect-jpackage ---
[INFO] Executing tasks

main:
     [exec] Get lecturePresenter modules
     [exec] java.base,java.compiler,java.desktop,java.instrument,java.management,java.naming,java.rmi,java.scripting,java.security.jgss,java.sql,jdk.sctp,jdk.unsupported
     [exec] Get lectureEditor modules
     [exec] java.base,java.compiler,java.instrument,java.management,java.naming,java.rmi,java.scripting,java.security.jgss,java.sql,jdk.jfr,jdk.sctp,jdk.unsupported,jdk.unsupported.desktop
     [exec] Get lectureBroadcaster modules
     [exec] java.base,java.compiler,java.desktop,java.instrument,java.management.rmi,java.naming,java.scripting,java.security.jgss,java.sql,jdk.unsupported
     [exec] Create Runtime
     [exec] Error: Hash of java.rmi (8af1b01f9bef4c4c469a84e2f33f46003cf597b4a50bfb17aa20d2064f1a9be5) differs to expected hash (294dbda1aa59329138167d9be87a07094b5dd369b28dc2949f05c251fa3b26c2) recorded in java.base
     [exec] WARNING: Using incubator modules: jdk.incubator.jpackage
     [exec] Packaging lecturePresenter
     [exec] jdk.incubator.jpackage.internal.ConfigException: Specified runtime image directory runtime-image: runtime does not exists
     [exec] Packaging lectureEditorcp: cannot stat 'lecturePresenter/*': No such file or directory
     [exec] 
     [exec] WARNING: Using incubator modules: jdk.incubator.jpackage
     [exec] Packaging lectureBroadcaster
     [exec] jdk.incubator.jpackage.internal.ConfigException: Specified runtime image directory runtime-image: runtime does not exists
     [exec] cp: cannot stat 'lectureEditor/*': No such file or directory
     [exec] WARNING: Using incubator modules: jdk.incubator.jpackage
     [exec] zip I/O error: No such file or directory
     [exec] zip error: Could not create output file (/data/lectureStudio/../release/lectureStudio-4.3.3-linux-x86_64.zip)
     [exec] jdk.incubator.jpackage.internal.ConfigException: Specified runtime image directory runtime-image: runtime does not exists
     [exec] cp: cannot stat 'lectureBroadcaster/*': No such file or directory
     [exec] chmod: cannot access 'lectureStudio-4.3.3-linux-x86_64/lib/app/lib/native/ffmpeg': No such file or directory
     [exec] Result: 15
[INFO] Executed tasks
[INFO] 
```
(The complete output is attached below.)

-> Am I missing something to get a successful build?

**To Reproduce**
1. Install all dependencies as described above.
2. Run `$ mvn install` in avdev and stylus project.
3. Run `$ mvn install` in lectureStudio repository.

**Expected behavior**
Maven should be able to pack the built project including all dependencies into the zip file as desired.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (inside a Docker container)

**Additional context**
I've attached the complete build output as file.
[mvn-install.log](https://github.com/lectureStudio/lectureStudio/files/6171273/mvn-install.log)

**Comment by lectureStudio** [comment]
Hi @maxkratz,
thanks for the report!

>      [exec] zip I/O error: No such file or directory
>      [exec] zip error: Could not create output file (/data/lectureStudio/../release/lectureStudio-4.3.3-linux-x86_64.zip)

This is a bug. The folder `release` is currently expected to exist in the same directory where your `lectureStudio` source folder is located.
For the time being the workaround would be to create an empty folder `release` in your `data` folder. There you will find the build.

**Comment by maxkratz** [comment]
> Hi @maxkratz,
> thanks for the report!

Thank you for your quick reply!

> This is a bug. The folder release is currently expected to exist in the same directory where your lectureStudio source folder is located.
> For the time being the workaround would be to create an empty folder release in your data folder. There you will find the build.

That makes sense. I've created the folder - the zip I/O error is gone :smile:.

There is a created zip archive in the folder `release` but its size is only a few bytes and it contains only a folder `lectureStudio-4.3.3-linux-x86_64` with no content at all.
This is the new build output:
```
main:
     [exec] Get lecturePresenter modules
     [exec] java.base,java.compiler,java.desktop,java.instrument,java.management,java.naming,java.rmi,java.scripting,java.security.jgss,java.sql,jdk.sctp,jdk.unsupported
     [exec] Get lectureEditor modules
     [exec] java.base,java.compiler,java.instrument,java.management,java.naming,java.rmi,java.scripting,java.security.jgss,java.sql,jdk.jfr,jdk.sctp,jdk.unsupported,jdk.unsupported.desktop
     [exec] Get lectureBroadcaster modules
     [exec] java.base,java.compiler,java.desktop,java.instrument,java.management.rmi,java.naming,java.scripting,java.security.jgss,java.sql,jdk.unsupported
     [exec] Create Runtime
     [exec] Error: Hash of java.rmi (8af1b01f9bef4c4c469a84e2f33f46003cf597b4a50bfb17aa20d2064f1a9be5) differs to expected hash (294dbda1aa59329138167d9be87a07094b5dd369b28dc2949f05c251fa3b26c2) recorded in java.base
     [exec] Packaging lecturePresenter
     [exec] WARNING: Using incubator modules: jdk.incubator.jpackage
     [exec] jdk.incubator.jpackage.internal.ConfigException: Specified runtime image directory runtime-image: runtime does not exists
     [exec] cp: cannot stat 'lecturePresenter/*': No such file or directory
     [exec] Packaging lectureEditor
     [exec] WARNING: Using incubator modules: jdk.incubator.jpackage
     [exec] Packaging lectureBroadcaster
     [exec] jdk.incubator.jpackage.internal.ConfigException: Specified runtime image directory runtime-image: runtime does not exists
     [exec] cp: cannot stat 'lectureEditor/*': No such file or directory
     [exec] WARNING: Using incubator modules: jdk.incubator.jpackage
     [exec] jdk.incubator.jpackage.internal.ConfigException: Specified runtime image directory runtime-image: runtime does not exists
     [exec] cp: cannot stat 'lectureBroadcaster/*': No such file or directory
     [exec] chmod: cannot access 'lectureStudio-4.3.3-linux-x86_64/lib/app/lib/native/ffmpeg': No such file or directory
```

**Comment by lectureStudio** [comment]
Please see the updated comment above, for the error you are getting.

**Comment by maxkratz** [comment]
> You can try to completely remove the current JDK and install the OpenJDK from AdoptOpenJDK or Zulu OpenJDK.

> Please see the updated comment above, for the error you are getting.

You are right, after using AdoptOpenJDK the zip archive was created successfully! Thank you once again :)

**Comment by devopvoid** [comment]
Should be fixed now. You can find the build in the project's root `target` directory.

**Comment by maxkratz** [comment]
> Should be fixed now. You can find the build in the project's root `target` directory.

Can confirm that, thanks!
