### ISSUE TITLE
lectureClient/Presenter (V 4.4.381): Stream für Kurs B starten während Chat bei Kurs A läuft

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#310]
Wenn man im Presenter
- den Messenger-Service für Kurs A startet
- dann einen Stream für Kurs B startet (mit aktiviertem Chat)

Dann bleibt im Client das Chat-Fenster bei Kurs A (Nachrichten gehen aber verloren) und bei Kurs B gibt es kein Chat-Fenster.
Wenn man den Stream im Presenter stoppen will, dann scheitert das mit Fehlermeldung. Danach ist auch der Streaming-Zustand im Presenter "kaputt". Starten eines neuen Streams funktioniert nicht, stoppen ebenfalls nicht. Ein Neustart des Presenters behebt das Problem.

Abhilfe: 
Alternative 1: ein Stream zu Kurs B kann nur gestartet werden, wenn kein Chat zu einem Kurs A läuft
Alternative 2: der Chat bei Kurs A wird mit dem Starten des Streams zu Kurs B automatisch beendet

**Comment by devopvoid** [comment]
Mit #309 behoben. Es lässt sich nur ein Kurs steuern.
