### ISSUE TITLE
lecturePresenter/Client (V 4.4.381): Messenger und Quiz zu zwei verschiedenen Kursen parallel

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#311]
In der Oberfläche des Presenters kann man den Messenger-Dienst und einen Quiz zu zwei verschiedenen Kursen gleichzeitig laufen zu lassen. Wenn man
- Messenger zu Kurs A startet
- Quiz zu Kurs B danach startet
werden bei den beiden Kursen in den Clients die korrekten Fenster angezeigt. ABER: Quiz-Antworten aus Kurs B kommen vom Client aus nicht beim Presenter an (es wird kein Chart angezeigt). Nachrichten aus Kurs A kommen hingegen beim Presenter an.

Abhilfe: solche Mischsituationen generell verbieten, das macht keinen Sinn!

**Comment by devopvoid** [comment]
Mit #309 behoben. Es lässt sich nur ein Kurs steuern.
