### ISSUE TITLE
lecturePresenter/Client (V 4.4.381): Zwei Quize gleichzeitig starten lassen korrumpiert Presenter-Zustand

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#312]
Die Oberfläche des Presenters erlaubt es, einen Quiz bei Kurs B zu starten während noch ein Quiz bei Kurs A läuft. Dabei wird der Quiz bei Kurs A automatisch beendet (im Client) und ein Quiz bei Kurs B (im Client) gestartet. Im Presenter wird auch der neue Quiz zu Kurs B als laufend angezeigt.

ABER: Antworten im Client zu Kurs-B-Quiz kommen nicht beim Presenter an.

Abhilfe: das Starten eines neuen Quizzes ist nicht möglich, solange noch ein alter Quiz läuft (egal ob beim selben oder verschiedenen Kursen).

**Comment by devopvoid** [comment]
Mit #309 behoben. Es lässt sich nur ein Kurs steuern.
