### ISSUE TITLE
lecturePresenter (V 4.4.381): PDFs und Aufzeichnungen zu laufenden Quizen enthalten zu viele Seiten

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#316]
Wenn man im Presenter einen Quiz durchführt, dann wird bei jeder eintreffenden Antwort das PDF-Dokument mit den Fragen und den verschiedenen Charts neu erzeugt und in der Anzeige aktualisiert. Das hat folgende unerwünschte Seiteneffekte:

1) Annotationen auf den entsprechenden PDF-Seiten gehen bei jeder neu eintreffenden Antwort verloren, sollten also während des laufenden Quizzes nicht erstellt werden.

2) Jede Aktualisierung führt zu einer eigenen PDF-Seite in den abgespeicherten Dokumenten (bei einem Quiz mit vielen Teilnehmern hat man dann entweder ganz viele identische Versionen der Frageseite im abgespeicherten Dokument oder ganz viele verschiedene Versionen einer im Presenter im Folienbereich angezeigten Chart-Seite.

3) In einer laufenden Aufzeichnung hat man ganz viele Seitenwechsel. Wenn man zu einer solchen Aufzeichnung das PDF-Dokument speichert, enthält dieses Dokument ebenfalls wieder ganz viele entweder identische Frageseiten oder ... . 

Ich bin etwas ratlos wie man diese Probleme beheben kann. Erste Ideen dazu:
- Während eines laufenden Quizzes ist es nicht möglich die entsprechenden pdf-Seiten zu annotieren.
- [Während eines laufenden Quizzes ist es nicht möglich eine der Chart-Seiten für die Folienansicht zu selektieren; das würde
   auch die Inkonsistenz beseitigen, dass man im Presenter die Chart-Seite im Folienbereich sieht, aber die Studierenden im Strea,
   diese Seite noch nicht sehen solange der Quiz nicht geschlossen und geteilt wurde.]
- Während eines laufenden Quizzes werden für die in der Folienansicht angezeigten Quiz-PDF-Seiten (insbesondere die Fragen) keine Seitenfortschalt-Events erzeugt, sodass die Probleme 2) und 3) oben vermieden werden.

**Comment by devopvoid** [comment]
Auch Punkt 1 behoben. Annotationen bleiben auf den neu erstellten Folien erhalten.

**Comment by devopvoid** [comment]
> [Während eines laufenden Quizzes ist es nicht möglich eine der Chart-Seiten für die Folienansicht zu selektieren; das würde
> auch die Inkonsistenz beseitigen, dass man im Presenter die Chart-Seite im Folienbereich sieht, aber die Studierenden im Strea,
> diese Seite noch nicht sehen solange der Quiz nicht geschlossen und geteilt wurde.]

Diese Strategie gewählt.

**Comment by Andy-Schuerr** [comment]
Idee zur Behebung des Problems: wie wäre es, wenn die PDF-Seite mit den Fragen eines Quizes und die PDF-Seiten mit den Charts getrennte PDF-Dokumente sind? Dann übertragt man das PDF-Dokument mit der Seite der Fragen nur einmal zum Client und aktualisiert dieses Dokument auch nie. Während das Quiz läuft kann man dann die Fragen beliebig annotieren ohne dass das zu Problemen führt. Und das sich dauernd aktualisierende PDF-Dokument mit den Charts wird während des laufenden Quizes nicht angezeigt, aufgenommen oder zu den Clients übertragen. Damit wären dann alle oben skizzierten Probleme beseitigt.
