### ISSUE TITLE
lecturePresenter (V 4.4.386): Verbesserung der optischen Ausgestaltung der Quiz-Charts (für Projektseminar?)

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#319]
Die aktuelle Darstellung der Quiz-Charts (der pdf-Seiten) könnte/sollte man wie folgt verbessern:
- Für die Diskussion der Ergebnisse einer Umfrage ist es ungünstig, dass weder die Frage (zumindest in Kurz- bzw. Überschriftsform)
  noch die verschiedenen Antwortsmöglichkeiten auf der entsprechenden Seite mit angegeben sind (sondern stattdessen nur die
   generischen Texte "Antworten", "Optionen" und "A", ... .
- Es fehlt dringend die Angabe, wieviele Personen an der Umfragen teilgenommen haben bzw. welche der möglichen Antworten
   ausgewählt haben. Im Augenblick hat man damit überhaupt kein Möglichkeit zu sehen, wieviele der Teilnehmer im Stream bereits
   an einer laufenden Umfrage teilgenommen haben - um zu entscheiden, wann man die Umfrage beendet.
- Die aktuellen Farben sind nicht mein Geschmack (insbesondere das Oliv-Grün) --> dazu gibt es glaube ich bereits einen Issue
   Entweder wählt man einfach weniger kontroverse Farben (da kann man sich ja an Standard-Paletten von Excel orientieren) oder
   man macht das auf Dauer sogar konfigurierbar.

**Comment by devopvoid** [comment]
> Es fehlt dringend die Angabe, wieviele Personen an der Umfragen teilgenommen haben...

Das sieht man bereits rechts oben im Fenster beim Indikator.
