### ISSUE TITLE
lectureClient (V 1.0.0-8): Kursanzeige ist aktiviert und Kurs wird gestartet, aber Folien nicht angezeigt

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#338]
Folgende Abfolge von Aktionen funktioniert nicht korrekt mit Chrome:
- Kurs/Stream läuft und wird in Chrome angezeigt (die Folie, ... )
- Stream wird gestoppt und als gestoppt in Chrome angezeigt
- Danach wird im Chrome-Client nichts gemacht
- Stream wird neu gestartet

Danach wird der Kurs als wieder laufend im Client angezeigt und das Nachrichtenfenster erscheint (weil der Messenger mit gestartet wurde). Aber die Folien werden nicht geladen und nicht angezeigt. Man muss erst auf die Kursliste im Client gehen und neu in den Kurs rein, um das Laden der Folien und die Anzeige der aktuellen Folie auszulösen.

**Comment by devopvoid** [comment]
Hmm.. das ist wieder was Seltsames, das ich nicht reproduzieren kann. Falls es nochmal auftritt, helfen vielleicht die Logs im Browser.

**Comment by Andy-Schuerr** [comment]
Ach verd... ! Jetzt kann ich das Verhalten auch nicht mehr reproduzieren. Dann bleibt uns nichts anderes übrig als den Issue zu schließen.
