### ISSUE TITLE
lectureEditor (V 4.4.402): Video-Rendering bleibt wieder mal hängen

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#347]
Bei der Beispielaufzeichnung (editierte Fassung) in der Hessenbox unter https://hessenbox.tu-darmstadt.de/getlink/fiKewQTpqCtjThAosrtsdNY3/ bleibt das Video-Rendering zuverlässig an der geschnittenen Stelle auf Folie 15 bei 7:25 Minuten hängen. Das ungeschnittene Original wird hingegen ohne Probleme gerendert.

**Comment by devopvoid** [comment]
Fixed with e7bf0ac.
