### ISSUE TITLE
lecturePresenter (4.4.408): Verbleibende Kamera-Einstellungs-Probleme

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#355]
Wenn man die Kamera im Presenter von 16:9- auf 4:3-Format umstellt, dann gibt es noch folgende zwei Probleme auf Windows 10 und Lenovo-Notebook:
1) Es wird nicht der Kamera-Ausschnitt geändert, sondern einfach das 16:9-Bild auf 4:3 umskaliert. Das sieht nicht vorteilhaft für die Dozent:innen aus. Diese umskalierte Bild sieht man im Presenter und in den Clients.
2) Nur bei der Logitech-Kamera HD Pro Webcam C920 tritt zusätzlich folgendes Problem auf: nach der Umstellung auf 4:3 ruckelt das Bild ganz furchtbar sowohl im Presenter als auch in den Clients. Manchmal verschwindet nach irgendeiner nicht reproduzierbaren Aktion, die die Kamera ein- und ausschaltet dieses Ruckeln (Stream starten/Stoppen), meistens aber nicht.

Für die Reproduktion des zweiten Problems kann die Logitech-Kamera in meinem Büro verwendet werden.

**Comment by devopvoid** [comment]
1. Lässt sich nach Bugfix nicht mehr reproduzieren.
2. Konnte nicht getestet, da die Kamera fehlt. Sollte aber auch behoben sein. Das "Ruckeln" lag wahrscheinlich daran, dass die Framerate der Kamera für das jeweilig Bildformat auf <15 gesetzt war.
