### ISSUE TITLE
lectureEditor (V 4.4.416): Parametereinstellungen für Video-Export funktionieren nur teilweise

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#365]
Im Editor verwende ich bislang für den Video-Export ausschließlich die Standard-Einstellungen. Deshalb ist mir jetzt erst aufgefallen, dass

-  im Bereich "Datei" die Umschaltung des Videoformats von MP4: H264 + AAC auf irgendwas anderes nicht funktioniert (zumindest ändert sich die Anzeige nicht)

- die Bereiche "Video" und "Audio" komplett leer sind solange man nicht einmal in den Reiter "Entrauschen" gewechselt und wieder in den Reiter "Video exportieren" zurückgekehrt ist.

- die Option "Zweipass-Codierung" funktioniert nicht, die Fortschrittsanzeige aktualisiert den blauen Balken nicht und das Video-Rendering selber bleibt bei unterschiedlichen (winzigen) Aufzeichnungen an unterschiedlichen Stellen hängen. Bei einer Testaufzeichung (Whiteboard mit ein paar Sekunden Ton) bleibt es beim "Audio Rendering" hängen
[editor-fx.log](https://github.com/lectureStudio/lectureStudio/files/7840242/editor-fx.log)

Ansonsten haben die verschiedenen Experimente mit unterschiedlichen Codecs, Parametereinstellungen etc. alle funktioniert.

**Comment by devopvoid** [comment]
> im Bereich "Datei" die Umschaltung des Videoformats von MP4: H264 + AAC auf irgendwas anderes nicht funktioniert (zumindest ändert sich die Anzeige nicht)

Das komprimierte Video hat je nach Format eine andere Dateiendung, z.B. `.avi`, `.webm`, `.mp4`.

Das funktioniert auch, zumindest bei mir :-)

> die Bereiche "Video" und "Audio" komplett leer sind solange man nicht einmal in den Reiter "Entrauschen" gewechselt und wieder in den Reiter "Video exportieren" zurückgekehrt ist.

Kann ich leider nicht reproduzieren. Falls das nochmal vorkommt, vielleicht steht dazu was in den Logs.

> die Option "Zweipass-Codierung" funktioniert nicht...

Diese Option erstmal entfernt.

**Comment by Andy-Schuerr** [comment]
Hier die Logdatei zu "Editor aufrufen, zwischen den Video-Export-Reitern hin- und herwechseln und Editor beenden":
[editor-fx.log](https://github.com/lectureStudio/lectureStudio/files/7847375/editor-fx.log)

Nach dem Start des Editors sieht die Fläche unter "Datei" so aus:
<img width="1280" alt="Screenshot 2022-01-11 153527" src="https://user-images.githubusercontent.com/80956559/148963309-09f761cd-01bd-427e-b70f-1bdf82e0d087.png">

Nach einmal Wechseln zum Entrauschen-Reiter und wieder zurückwechseln sieht es dann so aus:
<img width="1280" alt="Screenshot 2022-01-11 153539" src="https://user-images.githubusercontent.com/80956559/148963378-3eddc787-478b-4a6d-8d81-2527e5757d61.png">
