### ISSUE TITLE
lectureStreaming (V 5.0.438 / 1.0.0-21): Schnelles Aus- und Einschalten der Kamera im Presenter wird im Client nicht nachvollzogen

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#390]
Wenn man im Presenter schnell die WebCam während des Streamings erst aus- und dann wieder einschaltet, dann wird im Client das Kamerabild entfernt, aber nicht wieder hinzugefügt. "Schnell" heißt so etwa innerhalb einer Sekunde erst aus und dann wieder einschalten. Die Kamera ist dabei auf Presenterseite eingeschaltet. Wenn man die Kamera im Presenter wieder ausschaltet, wartet und sie dann wieder einschaltet, wird die Kamera im Client auch wieder angezeigt.

**Comment by devopvoid** [comment]
Verfolgen wir das noch weiter? War das nicht nur mit der einen Logitech Kamera möglich?

**Comment by Andy-Schuerr** [comment]
Das Problem tritt mit jeder Kamera auf und hat glaube ich eher nichts mit dem WebClient zu tun. Wenn man die Kamera auf Presenterseite sehr schnell aus- und wieder anschaltet, dann ist die Kamera aus Presentersicht an (und ist auch tatsächlich hardwaremäßig eingeschaltet). Die Clients erhalten aber einfach kein Event, dass die Dozent:innen-Kamera wieder eingeschaltet ist. Damit zeigt die Presenter-Oberfläche einen falschen Zustand an.

**Comment by Andy-Schuerr** [comment]
Dieses Issue ist ein Duplikat.
