### ISSUE TITLE
lectureStreamingClient: im Stream anzeigen, wenn Aufzeichnung im Presenter läuft

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#395]
Aus datenschutzrechtlichen Gründen sollte auch lectureStudio (wie Zoom und Co) klar und deutlich anzeigen, wenn der gestreamte Kurs aufgezeichnet wird, da insbesondere die Wortmeldungen von Kursteilnehmer:innen ja mit aufgezeichnet werden.

Die Minimallösung besteht darin, dass
- die Client-Oberfläche neben dem grünen Symbol für einen laufenden Stream ein zusätzliches Icon anzeigt (roter Annahmekreis oder  ... ), das eine Aufzeichnung des Streams signalisiert
- in der Datenschutz-Erklärung wird darauf hingewiesen (und ggf. auch in der Benutzerdokumentation)

Zusätzlich könnte man auch die Lösung von Zoom wählen, dass in einem zu bestätigenden Popup-Fenster beim Einschalten der Aufzeichnung oder beim Betreten eines Streams, der schon aufgezeichnet wird, auf die Aufzeichnung hingewiesen wird. Zoom geht sogar noch einen Schritt weiter und bietet in einem solchen Popup-Fenster die Zustimmung oder Ablehnung an. Unklar ist mir, was passiert, wenn man nicht zustimmt. Wird man dann aus dem Kurs rausgeworfen? Das macht irgendwie keinen Sinn, da man ja auch selber den Kurs verlassen kann oder man sich nicht zur Wort melden kann, nachdem zur Kenntnis genommen hat, dass aufgezeichnet wird.

**Comment by devopvoid** [comment]
Ich denke ein Dialog - beim Betreten - mit dem Hinweis "Kurs wird aufgezeichnet" sollte reichen. Momentan haben wir keinen Konferenzmodus und alle Teilnehmer sind anonym, bis auf die Wortmeldung.
