### ISSUE TITLE
Unable to launch lecturePresenter (4.3.1314) on Linux with an empty config.json

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#4]
Please notice: I've edited this issue, because I found that lecturePresenter couldn't start, because its `config.json` in `~/.config/lecturePresenter/` somehow got empty. (The file existed, but it had no content.) If I started it with `sudo`, the config file in roots home directory was used.

---

**Describe the bug**
I've downloaded and extracted lectureStudio v4.3.1314 from [the official download page](https://www.lecturestudio.org/download) on my Linux Mint 20.1 machine, as described in the ["Benutzerhandbuch"](https://www.lecturestudio.org/assets/manual/lectureStudio-Benutzerhandbuch.pdf).

~~I'm able to start `lectureEditor` and `lecturePlayer` as expected (with the permissions of my normal user account).
However, I'm unable to start `lecturePresenter` without running it as super user (e.g. through `sudo`): I get an error printout on console, which I will append.~~

~~Interestingly, the previous release v4.3.1060 does not show this behavior.~~

Please see above: lecturePresenter is unable to start if its `config.json` is empty.

**To Reproduce**
1. Go to the official download page and download the latest release (4.3.1314) for Linux: https://www.lecturestudio.org/download
2. Extract the archive (e.g. with `unzip`)
3. Start the application from terminal ~~with normal user rights~~ e.g. with: `$ ./lecturePresenter`
4. Somehow - I don't know how - the content of `~/.config/lecturePresenter/config.json` was removed.
5. Start the application again -> It will fail to launch.

**Expected behavior**
The program should start without an error message and show its GUI or show a useful error message without ~~super user permissions~~ a proper config file.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1, Kernel 5.5.19-generic

**Log output:**
[lecturePresenter-output.log](https://github.com/lectureStudio/lectureStudio/files/6177279/lecturePresenter-output.log)

**Comment by maxkratz** [comment]
Update:
> 4. Somehow - I don't know how - the content of ~/.config/lecturePresenter/config.json was removed.

Issue #7 describes, how the file got empty in my case.

**Comment by jomority** [comment]
I can reproduce this issue.

Interestingly the file only gets emptied on a crash when trying to open a PDF, not when opening the whiteboard. And only in ~80% of the times (independent from the PDF file).
