### ISSUE TITLE
lecturePresenter (4.3.1314): black areas when scribbling with pen tool

### ISSUE THREAD

**Issue by jomority** [lectureStudio/lectureStudio#41]
**Describe the bug**
On Windows, when scribbling very fast with the pen tool, black areas appear.

**To Reproduce**
1. Open a whiteboard in lecturePresenter (on Windows)
2. Scribble very fast in circles
3. Black areas appear

**Expected behavior**
There should only be lines on the whiteboard.

**Video**

https://user-images.githubusercontent.com/7509228/115144794-e8e2c100-a04e-11eb-8ceb-e18e252eded4.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19042

**Additional context**
I cannot reproduce this problem on linux.

**Comment by Andy-Schuerr** [comment]
Das Problem lässt sich nicht mehr reproduzieren.
