### ISSUE TITLE
lectureClient: Reaktion auf Fehlbedienung des Geräteeinstellungsdialogs

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#443]
Bei Experimenten mit dem lectureClient unter Android auf dem Smartphone ist es mir aus Versehen gelungen, dem Browser die Rechte für die Nutzung von Video/Audio (teilweise) zu verweigern. Das korrumpiert (in Firefox zumindest) den Zustand des Clients wie folgt:

* im Gerätedialog sind keine Geräte auswählbar (die Auswahlbox für Audio ist leer, die für Video enthält nur "keine").
* "Zurücksetzen" hat keinen Effekt und liefert auch keine Fehlermeldung
* Handmeldungen laufen anscheinend ganz normal durch, aber nach der Bestätigung der angenommenen Wortmeldung im Client scheitert der Verbindungsaufbau. Weder im Presenter noch im Client gibt es dazu eine Fehlermeldung (auf beiden Seiten sollte eine Fehlermeldung angezeigt werden, dass der Verbindungsaufbau wegen fehlender Rechte zur Nutzung der Geräte gescheitert ist).

Man muss dann selbst auf die Idee kommen, im Browser die falschen Rechteeinstellungen zu löschen und ... .

**Comment by devopvoid** [comment]
Die Geräteeinstellungen sind so angepasst worden, dass dort auch die Meldung zu notwendigen Berechtigungen angezeigt wird und die Einstellungsmöglichkeiten deaktiviert sind.

Wortmeldungen werden mit dem gleichen Hinweis quittiert.

Ich denke mehr können wir hier nicht tun. In einigen Browsern, wie z.B. Firefox, hilft das Neuladen der Seite. Dann wird man wieder vom Browser um Berechtigung gefragt.
