### ISSUE TITLE
Weird black shapes

### ISSUE THREAD

**Issue by elenziat** [lectureStudio/lectureStudio#45]
When opening a recorded lecture in lectureEditor, a few slides show some weird black shapes instead of the actual content. The generated video shows this shapes as well.

I don't know if this is a similar problem as described in #41. However, in this case the problem wasn't visible during recording with the lecturePresenter, but only afterwards.

lectureStudio 4.4.52 on Windows.

(It is the only time afters hours of recording (with older versions) that this happened. But this is kind of a severe problem, especially because it only reveals itself in the postprocessing.)

![Screenshot_LectureEditor](https://user-images.githubusercontent.com/22983571/115507794-dc43b000-a27c-11eb-8da5-3347b009f384.png)
![Screenshot_Video](https://user-images.githubusercontent.com/22983571/115507796-dcdc4680-a27c-11eb-92df-5126bcbdef0a.png)

**Comment by devopvoid** [comment]
The recording itself should be fine. This is some kind of rendering issue.
Is it possible that you provide me the recording, or the part of it where this happens?

**Comment by elenziat** [comment]
Of course. I've just sent you a link to the recording by e-mail.

**Comment by Andy-Schuerr** [comment]
Diese schwarzen Polygone kann ich leider immer noch erzeugen, wenn ich auf dem Whiteboard sehr schnell male und dabei immer über die Ränder hinaus!

**Comment by devopvoid** [comment]
Der hier beschriebene Fehler lag an der seltenen korrupten Aufzeichnung von einzelnen Folien. Das sollte mit der letzten Version 4.4.136 behoben sein.

**Comment by Andy-Schuerr** [comment]
Ah okay! Stimmt, die schwarzen Artefakte sehen auch anders aus als die, die man mit dem Stift auf dem Whiteboard produzieren kann.
