### ISSUE TITLE
lecturePresenter (V 5.0.492): Handhabung von URLs bei der Anzeige von Nachrichten

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#468]
Wenn eine Textnachricht eine URL enthält und diese in eine PDF-Seite konvertiert und anschließend im Stream angezeigt wird, dann ist diese URL - anders als URLs sonst in Folien - nicht selektierbar.

**Comment by Andy-Schuerr** [comment]
Ich bin beeindruckt, das ist toll!

**Comment by Andy-Schuerr** [comment]
Das Anzeigen einer URL aus einer Nachricht hat einen ungewollten Seiteneffekt: wenn man im Client dann eine solche URL anwählt und damit auf die entsprechende Seite kommt, dann geht diese Seite nicht in einem neuen Tab auf. Wenn man dann mit dem üblichen "zurück" wieder in den Stream zurück will, dann landet man auf der Seite, die behauptet das der Stream nicht läuft - obwohl er gerade läuft. Das Problem lässt sich dann nur mit einem "reload" beheben.

**Comment by devopvoid** [comment]
Das lässt sich momentan schwer einzustellen, dass der Link in einem neuen Tab oder Fenster öffnet. Bei Erstellung des Dokumentes wird das von der API ignoriert.

Als Alternative können Teilnehmer per Rechtsklick auf den Link im neuen Tab öffnen.

**Comment by Andy-Schuerr** [comment]
Okay, dann bessere Behandlung des „Zurück“-Knopfs im Client?

Von: Alex Andres ***@***.***>
Gesendet: Freitag, 6. Mai 2022 09:56
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; State change ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] lecturePresenter (V 5.0.492): Handhabung von URLs bei der Anzeige von Nachrichten (Issue #468)


Das lässt sich momentan schwer einzustellen, dass der Link in einem neuen Tab oder Fenster öffnet. Bei Erstellung des Dokumentes wird das von der API ignoriert.

Als Alternative können Teilnehmer per Rechtsklick auf den Link im neuen Tab öffnen.

**Comment by devopvoid** [comment]
Ist per clientseitigen PDF-Renderer behoben. Dieser Fall lässt sich auch mit der Titelseite des ES-Foliensatzes testen (WWW-Seite der Vorlesung).
