### ISSUE TITLE
lecturePlayer (MP4, v?): Playback not possible in Chromium on Windows

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#497]
**Describe the bug**
Playback of MP4-based recordings (e.g., from the [tutorial page](https://www.lecturestudio.org/tutorials)) is not possible in Chromium on Windows OS (at least on my system).

**Can someone confirm this for me?**

**To Reproduce**
1. Go to https://www.lecturestudio.org/tutorials in Chromium on Windows.
2. Start a tutorial as MP4-based recording.
3. Stuck on 

**Expected behavior**
Playback should be possible and/or an error message should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/20956405/162009194-4c56ecbf-24a6-4f1e-bd7d-fab400f37fe2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium version 98.0.4711.0 (Developer-Build) (64-Bit)

**Additional context**
It works for me with/in:
- Firefox v99.0 on Windows.
- Chromium v99.0.4844.84 (Official Build) (64-Bit) on Linux Mint.

**Comment by Andy-Schuerr** [comment]
Bei mir funktioniert das Ganze wunderbar auf Windows und mit Chrome als Browser. Man muss zwar das Abspielen manuell starten (was auch okay ist), aber ansonsten klappt es ohne Probleme. Ich benutze Chrome ohne irgendwelche zusätzlichen Plugins oder Add-Ons oder ... so wie er "out-of-the-box" installiert wird. Das Problem sollte also durch irgendein Chrome-Add-On verursacht sein?!

**Comment by maxkratz** [comment]
Ich habe es gerade noch einmal auf meinem privaten Rechner (unter Windows 10) getestet. Ergebnis:

| Browser | Version | Ergebnis |
| --- | --- | --- |
| Firefox | v98.0.2 (64-Bit) | Funktioniert | 
| Firefox | v99.0 (64-Bit) | Funktioniert | 
| Chrome | v100.0.4896.75 (Official Build) (64-Bit) | Funktioniert |
| Chromium | v102.0.4992.0 (Developer Build) (64-Bit) |  **Funktioniert nicht** |

Alle jeweils ohne Plug-Ins im Inkognito-Tab (und auch im normalen Modus).

Vielleicht ist das auch eine Eigenart von Chromium, weil ein Codec fehlt oder Ähnliches?

**Comment by maxkratz** [comment]
Update: Chromium kann bei mir schon die MP4-Datei nicht abspielen (wenn ich sie direkt mit dem Link aufrufe).

Scheint also wirklich ein Codec-Problem zu sein.

![image](https://user-images.githubusercontent.com/20956405/162572459-d0b9a93a-5363-459e-b0f0-3f7902a15da7.png)

**Comment by maxkratz** [comment]
In der Tat kann Chromium bei mir unter Windows (generell) keine MP4-Dateien abspielen, wenn diese den h.264 Codec oder den AAC Audio Codec benutzen. (Beide sind im lectureEditor per default ausgewählt beim Export.)

> By default, Chromium does not support proprietary codecs (like h.264, aac). Official info: https://www.chromium.org/audio-video

(Quelle: https://superuser.com/a/1545667, Mehr Infos: https://www.chromium.org/audio-video/)

Scheinbar wird das "Problem" unter Linux meist dadurch behoben, dass die Distributions-Maintainer eigene Builds des Browsers anfertigen, welche die Codecs enthalten. So etwas gibt es für Windows auch (https://chromium.woolyss.com/). Für mich hat sich das Problem jetzt dadurch gelöst, dass ich für mein Windows-System auch auf solche Chromium-Binaries umsteige (oder eben Firefox etc. benutze). Die speziellen Chromium-Builds muss ich allerdings erst noch ausprobieren (unter Windows), da bin ich aber recht zuversichtlich, dass das klappt.

Dann kann das Issue hier geschlossen werden und falls in Zukunft jemand das gleiche Problem hat, kann er hierhin verwiesen werden!
