### ISSUE TITLE
lecturePlayer (MP4, v?): Layout bug in narrow browser windows

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#498]
**Describe the bug**
In narrow (but high) browser windows, the layout of the video player is buggy for the MP4-based playbacks. 

**To Reproduce**
1. Open a web browser window that is narrow, but relatively high. A good example is half of a 16:9 monitor
2. Go to https://www.lecturestudio.org/tutorials.
3. Start a tutorial as MP4-based recording.

**Expected behavior**
The video player should be at maximum as wide as the space available. This should hold horizontally and vertically.

**Screenshots**
![image](https://user-images.githubusercontent.com/20956405/162011272-bf63c382-81b1-4940-be72-e2f85b3b4456.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser(s):
   - Chromium version 98.0.4711.0 (Developer-Build) (64-Bit)
   - Firefox version 99.0 (64-Bit)

**Additional context**
The behavior is identical in Chromium/Firefox on Windows and Linux.

**However, all *HTML-/JavaScript-based* versions do not have this issue.**
---

**Comment by Andy-Schuerr** [comment]
Das Player-Layout hat sich bei schmalem Fenster verschlechtert in Version 1.3.0-82. Hier ein paar Screendumps:
<img width="698" alt="Screenshot 2022-08-20 112811" src="https://user-images.githubusercontent.com/80956559/185739082-3b94756f-167d-419a-8195-094f926881c2.png">
<img width="514" alt="Screenshot 2022-08-20 112828" src="https://user-images.githubusercontent.com/80956559/185739083-ce38f4d9-cc19-4a4f-8b04-cd234a10d5e8.png">
<img width="376" alt="Screenshot 2022-08-20 112842" src="https://user-images.githubusercontent.com/80956559/185739086-148b34cc-bfc5-43f6-b613-47f85b577dab.png">
