### ISSUE TITLE
lecturePresenter (V 5.1.560): Textnachrichten als html-Dokument nicht im Log-Verzeichnis speichern

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#513]
Die ganzen Textnachrichten zu einem Stream werden als html-Dokument im Log-Verzeichnis des Presenters gespeichert. Das ist nicht konsistent zum sonstigen Vorgehen beim Abspeichern von Aufzeichnungsdateien im Presenter. 

Deshalb bitte die 
* Möglichkeit zum Speichern der Textnachrichten einfach in den "Dokumente-Speichern"-Dialog mit aufnehmen
* Den Dateinamen nach dem gleichen Schema bilden wie Aufzeichnungen etc.
* Das Format kann gerne weiterhin html bleiben, das kann man ja bei Bedarf umwandeln in pdf oder ...

**Comment by devopvoid** [comment]
Welche Textnachrichten sollen abgespeichert werden?

1. Alle (Messenger mehrmals an/aus).
2. Alle seit Messenger an. Bei Messenger Neustart ist die Liste leer.
3. Nur die nicht entfernten aus der Liste.
4. ...

**Comment by Andy-Schuerr** [comment]
Entweder Option 1 oder Option 2 ist die richtige. Bei meinem Nutzerverhalten spielt es keine Rolle, welche der beiden Optionen gewählt wird. Ich starte den Stream zusammen mit den Messenger und sehe keinen Grund ihn zwischendrin zu stoppen. Allenfalls Internetprobleme oder Geräteprobleme am Anfang der Lehrveranstaltung könnten bei mir dazu führen, dass ich den Stream oder den Presenter komplett beenden muss. Dann muss ich aber auch die bisherige Aufzeichnung erst mal abspeichern etc.

**Comment by Andy-Schuerr** [comment]
Bislang sehe ich noch keine Option das Abzuspeichern. Unter der Option "Nachrichten" werden wie bisher nur die angezeigten Nachrichten alle als pdf-Dokument abgespeichert, was ja auch Sinn macht!

**Comment by Andy-Schuerr** [comment]
Hat sich erledigt!
