### ISSUE TITLE
lectureClient: Stream-Start führt zu Rendering-Fehler bei minimiertem Chrome

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#524]
Folgende Aktionssequenz führt im Chrome-Client zu einem Rendering-Fehler:
1) Client zeigt Stream-Seite mit der Meldung "Stream noch nicht gestartet" an.
2) Chrome-Fenster wird minimiert.
3) Stream wird gestartet und im Presenter die erste Folie angezeigt.
4) Chrome-Client wird wieder maximiert.

Der Chrome-Client zeigt nun nicht mehr die Meldung "Stream ..." an, sondern einfach eine leere weiße Seite an.
In Firefox funktioniert der skizzierte Ablauf, es wird nach der Maximierung die richtige Folie angezeigt.

**Comment by devopvoid** [comment]
Duplicate of #490
