### ISSUE TITLE
lecturePresenter (V 5.1.566): Balkendiagrammgrafik einer Umfrage enthält zusätzlichen Strich

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#528]
Die Balkendiagramme zu einer Umfrage besitzt auf einmal links von den Balken und rechts von der Legende "Antworten" einen zusätzlichen Strich, der überflüssig/unschön ist
[Quiz-2022_04_29-08_21.pdf](https://github.com/lectureStudio/lectureStudio/files/8588542/Quiz-2022_04_29-08_21.pdf)
.

**Comment by devopvoid** [comment]
Dieser Strich wird für die Achsenbeschriftung verwendet, also die Anzahl der Antworten. Bei nur einer Antwort wird keine Zahl geschrieben. Der Fall, dass nur eine Antwort eingeht ist eher unwahrscheinlich :-)

**Comment by devopvoid** [comment]
Der Strich ist nun weg.

**Comment by Andy-Schuerr** [comment]
Kann geschlossen werden, da der Strich einfach nur die Y-Achse für das Balkendiagramm darstellt. Bei genau einer Antwort sieht die nutzlos aus. Aber Umfragen mit genau einer Antwort gibt es in der Praxis auch nicht!
