### ISSUE TITLE
lectureEditor (V 5.1.582): Löschen eines ganzen Seitenbereichs

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#538]
Beim Löschen eines ganzen Seitenbereichs wird immer ganz kurz die erste Folie der Aufzeichnung angezeigt bevor dann wieder die "richtige" Folie angezeigt wird. Da manchmal danach die Aufzeichnung an dieser Stelle kaputt ist und das Abspielen mit der anzeige der ersten Folie stoppt, scheint das nicht nur ein "Anzeige"- sondern auch ein Logikproblem im Algorithmus zu sein mit Auswirkungen auf das Schneideergebnis.

**Comment by devopvoid** [comment]
Löschen des ganzen Seitenbereichs behoben.

> Beim Löschen eines ganzen Seitenbereichs wird immer ganz kurz die erste Folie der Aufzeichnung angezeigt bevor dann wieder die "richtige" Folie angezeigt wird.

Nicht ganz kritisch. Muss noch angepasst werden.

**Comment by Andy-Schuerr** [comment]
Es gibt noch einen Fehler beim Löschen von Seitenbereichen: wenn man ganz schnell mehrfach hintereinander den Lösche-Knopf drückt, dann kommt das Löschen nicht mehr "hinterher" und es wird ein Fehler geworfen. Ggf. hängt sich der Editor dann sogar auf.
