### ISSUE TITLE
lecturePresenter (V 5.1.582): es fehlen Seiten im generierten PDF einer Aufzeichnung

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#540]
Im folgenden Fall fehlen mir im generierten Gesamtdokument (PDF) zu einer Vorlesungsaufzeichnung Folien:
1) Ich habe das normale Foliendokument plus ein weiteres Dokument mit genau einer Folie offen.
2) Diese zusätzliche Folie zeigt eine Grafik einer fragenden Person und wird immer eingeblendet, wenn im Hörsaal jemand
    eine Frage stellt.
3) Das hat den Zweck, dass (1) die Zuhörer im Stream wissen, dass gerade eine Frage gestellt wird, die sie nicht hören können,
    sowie (2) dass ich im Nachhinein dann - wenn es sich anbietet - im generierten PDF die Frage und meine Antwort als kurze
    Texte ergänzen kann.

Leider wird die Folie in das Gesamt-PDF nur bei der ersten Anzeige integriert und danach nie mehr wieder. Bei der Fehlersuche ist zu beachten, dass ich auf dieser Folie in der Regel keine Annotationen durchführe, sondern sie einfach eingeblendet lasse während die Frage im Hörsaal gestellt wird, ich sie für den Stream wiederhole und schließlich beantworte.

**Comment by Andy-Schuerr** [comment]
Ergänzung: es hat auch eine generierte Seite mit Kommentar aus dem Stream gefehlt. Das verunsichert mich, da das bisher immer geklappt hat. Fakt ist: die erste "Hörsaalmeldeseite" und die ganzen Quizseiten wurden zusammen mit den annotierten Folien im generierten PDF mit berücksichtigt, alle weiteren Hörsaalmeldungen und eine angezeigte Nachricht wurden zwar in der Vorlesungsaufzeichnung gespeichert (und sind vorhanden, wenn man das PDF im Editor exportiert), sind aber nicht im PDF, das vom Presenter als Gesamtdokument generiert wurde, mit drin.

**Comment by devopvoid** [comment]
Seiten von allen angezeigten Textnachrichten sollten dabei sein.

Die _Hörsaalmeldeseite_ wird nur einmal aufgezeichnet, da hier der Schutz vor doppelten Seiten greift. Wenn aber auf dieser Seite was annotiert wird, wird diese auch ins Gesamt-PDF aufgenommen. Um das zu umgehen, muss dieses PDF speziell gekennzeichnet sein, damit eine mehrfache Aufzeichnung der Seite funktioniert.

Vielleicht nach dem Dokumentnamen vergleichen (Prefix, Suffix,...)?

**Comment by Andy-Schuerr** [comment]
Sowas habe ich befürchtet. Ich überlege mir einen Vorschlag.

**Comment by Andy-Schuerr** [comment]
Das Problem hat sich geklärt und eine Lösung wurde dafür gefunden.
