### ISSUE TITLE
Feature request: Add progress indicator for the PDF distribution while streaming

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#543]
**Is your feature request related to a problem? Please describe.**
In our lectureStudio meeting today we discussed the "problem" that the PDF distribution can take some time (especially with a high amount of students participating in the stream).
If the lecturer integrates quizzes, the quiz questions are distributed as new PDF files to all students (which can take some time).
Currently, the lecturer is urged to wait a few seconds until the distribution finishes before they can continue but there is no indicator if all clients could successfully download the new PDF (at least that I know).

**Describe the solution you'd like**
One (hopefully simple) idea is to indicate the progress of the PDF distribution to the lecturer by, e.g., displaying a progress bar. This could be done either percentual or with the total amount of listeners:

- *73%*
- *146/200 students*

With this solution, the lecturer knows exactly when to proceed with the quiz, e.g., explaining the question(s).

**Comment by Andy-Schuerr** [comment]
In der Praxis hat sich das nicht als Problem herausgestellt. Am Anfang der Vorlesung sieht man genau, wenn Studierende vollständig im Stream "angekommen" sind und das Foliendokument besitzen. Dann ändert sich nämlich das Icon von "Hörsaal"-Status zu "Daheim"-Status in der Teilnehmerliste. Und die Verteilung von Quiz-Dokumenten geht so schnell bei den üblichen Teilnehmerzahlen, dass man darauf kaum Rücksicht nehmen muss.
