### ISSUE TITLE
lectureEditor (V 5.1.603): Falsche Darstellung der Waveform nach Schneiden

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#553]
Wenn man in der Datei ES-2022-06-01 in die Waveform zwei/drei Schritte reinzoomt und dann ganz am Anfang die Stille wegschneidet, dann sieht die Waveform danach wie in diesem Screendump hier aus. Das ist reiner Darstellungsfehler, der nach Speichern und wieder Laden der Aufzeichnung behoben ist
<img width="1280" alt="Screenshot 2022-06-02 084626" src="https://user-images.githubusercontent.com/80956559/171570046-838c14b6-fc4d-4f03-afbc-0959da874c3e.png">
. Es fehlen die ganzen Ausschläge nach oben. Zum Vergleich hier die richtige Darstellung:
<img width="1280" alt="Screenshot 2022-06-02 085044" src="https://user-images.githubusercontent.com/80956559/171570368-a3eda5a8-ab11-4bc8-a12c-a7b05bc3aa86.png">
Die entsprechende Datei findet man an der üblichen Stelle in der Hessenbox.

**Comment by Andy-Schuerr** [comment]
Ergänzung: das Problem tritt auch ohne Reinzoomen bei manchen Aufzeichnungen auf!

**Comment by devopvoid** [comment]
War auch mit der Aufzeichnung "SE2-4-1-1-Einleitung" reproduzierbar.

**Comment by Andy-Schuerr** [comment]
Dann hoffen wir mal, dass dieses immer mal in der Vergangenheit auftauchende Problem damit "Geschichte" ist.
