### ISSUE TITLE
lecturePresenter: Neue Einstellung für Gitternetz auf Whiteboard-Seiten aktivieren

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#560]
Auf  Whiteboard-Seiten brauche ich immer ein Gitternetz als Hilfsmittel damit ich einigermaßen ordentlich schreibe und male.
Deswegen muss ich immer zweimal klicken, wenn ich das Whiteboard nutze (Whiteboard aktivieren, Gitternetz einschalten).
Schön wäre deshalb eine neue Option in den Einstellungen für das Whiteboard mit der man das Gitternetz defaultmäßig (de-)aktivieren kann.

**Comment by devopvoid** [comment]
Wie wäre es ohne extra Einstellung und einfach merken, ob zuletzt das Gitternetzt aktiviert war?

**Comment by Andy-Schuerr** [comment]
Dann muss man es nur noch einmal zu Beginn des Programms bei der ersten Whiteboard-Seite angeben.

Von: Alex Andres ***@***.***>
Gesendet: Dienstag, 7. Juni 2022 19:21
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] lecturePresenter: Neue Einstellung für Gitternetz auf Whiteboard-Seiten aktivieren (Issue #560)


Wie wäre es ohne extra Einstellung und einfach merken, ob zuletzt das Gitternetzt aktiviert war?
