### ISSUE TITLE
lecturePresenter (V 5.1.664): URL für Streaming-Server sollte "https" erlauben

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#569]
Wenn man die URL des Streaming-Servers aus der Adressleiste des Browsers kopiert, dann hat man das Format

   "https://.../"

Wenn man diesen String genau so in den lecturePresenter-Einstellungen einträgt dann wird der Server nicht gefunden. Man muss erst das führende "https://" entfernen. Das sollte nicht notwendig sein.

**Comment by devopvoid** [comment]
Es können nun auch komplexe URLs eingefügt werden, z.B. https://lecturestudio.e-technik.tu-darmstadt.de/course/1

**Comment by Andy-Schuerr** [comment]
Das funktioniert noch immer nicht! Die Eingabe https://lecturestudio.dek.e-technik.tu-darmstadt.de/ wird nicht richtig verarbeitet, die Eingabe lecturestudio.dek.e-technik.tu-darmstadt.de/ hingegen schon.
