### ISSUE TITLE
neuer Client: nach Fenstergröße verändern wird falsche Folie angezeigt

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#580]
Wenn man im laufenden Stream (mit genau einem offenen PDF) das Browserfenster vergrößert oder verkleinert, wird danach nicht die aktuelle Folie, sondern die erste Folie des geladenen Dokuments angezeigt. Dieses Phänomen tritt in Chrome und in Firefox auf. Zudem funktioniert das Redraw in Firefox generell bei Änderung der Fenstergröße nicht richtig. Das Ergebnis sieht beispielsweise so aus:
<img width="587" alt="Screenshot 2022-07-03 164314" src="https://user-images.githubusercontent.com/80956559/177044895-f5676d56-f457-4a49-8e58-df32c13f1c12.png">

**Comment by devopvoid** [comment]
Kann ich leider nicht reproduzieren. Vermutlich durch die letzten Änderungen ist das auch behoben.
