### ISSUE TITLE
lectureEditor (V 5.1.664): Löschen von Stelle X bis Ende der Aufzeichnung setzt Abspielmarke falsch

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#582]
Wenn man ab einer Stelle X im Programm alles danach löschen will (weil man die Aufzeichnung splitten will), dann ist die Abspielmarke danach falsch gesetzt. Ich würde erwarten, dass die Abspielmarke nach dem Löschen ganz am Ende der verbleibenden Aufzeichnung stehen bleibt. Stattdessen wird sie um die Länge des gelöschten Teils zurückversetzt. Also Beispiel:

- Die Aufzeichnung hat 50 Minuten Länge
- Es werden die letzten 10 Minuten gelöscht
- Danach steht die Marke nicht am Ende der Aufzeichnung (also bei 40 Minuten), sondern in etwa bei 30 Minuten)

Das irritiert beim Arbeiten ziemlich.

**Comment by devopvoid** [comment]
Lässt sich nicht mehr reproduzieren. Nicht sicher, ob behoben ist!
