### ISSUE TITLE
lecturePresenter (V 5.1.664): Quizze mit zu vielen Antwortoptionen

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#589]
Wenn ein Quiz so viele Antwortoptionen besitzt, dass diese in der Legende der Balkendiagramme (Tortendiagramme) nicht mehr auf eine Folie passen, dann wird das Layout der Balkendiagramme zerstört. Das Balkendiagramm liegt dann über einem Teil des Legendentextes auf einer Folgeseite, auf der ersten Balkendiagrammseite bleibt der für das Diagramm reservierte Platz frei bzw. ungenutzt.

**Comment by devopvoid** [comment]
Wenn die Antwortoptionen nicht auf die erste Seite passen, werden sie auf neue Seiten umgebrochen. In der Vorschauleiste lassen sich diese Seiten auch anklicken und anzeigen, solange das Quiz läuft. Nach Beendigung sind auch Chartseiten anklickbar.

**Comment by Andy-Schuerr** [comment]
Die Implementierung wurde an dieser Stelle leider "verschlimmbessert". Wenn die Legende zu den Charts nicht mehr auf eine Seite (unterhalb der Charts) passt, dann werden die Charts-PDF-Seiten einfach gar nicht mehr generiert. Ich konnte das beliebig oft reproduzieren mit einem Quiz mit vielen Multiple-Choice-Antwort-Optionen. Sobald die Legende zu den Antwortoptionen bei den Charts nicht mehr in den dafür zur Verfügung stehenden Platz passt, werden entweder gar keine Chart-Seiten mehr generiert oder aber Chartseiten mit kaputtem Layout.

Testen lässt sich das Verhalten mit immer mehr Quizoptionen, die alle den Text

1234567890 1234567890 1234567890 1234567890

enthalten. Wenn man da genügend Quiz-Optionen hinzufügt ist irgendwann das Layout kaputt (erst kommt die Legende über mehrere PDF-Seiten verteilt  und dann die Balkendiagramme).

Spannender ist, wenn man lange Zeichenketten ohne Leerzeichen dazwischen als Quizoptionstexte verwendet:

12345678901234567890123456789012345678901234567890123456789012345678901234567890

Wenn man dann genügend Optionen angibt bei einer Multiple-Choice-Frage dann werden irgendwann gar keine PDF-Seiten mehr generiert. 

Vorschlag: wir lösen das Problem ganz einfach dadurch, dass mehr als 6 Quizoptionen verboten werden (ab 7 Optionen habe ich je nach Text beim Testen Probleme bekommen).
