### ISSUE TITLE
lecturePresenter (4.4.77): Quiz-Speichern gibt keine Bestätigung

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#61]
Wenn man einen Quiz erstellt und auf den "Speichern"-Knopf drückt, erhält man überhaupt keine Bestätigung, dass Speichern funktioniert hat. Das ist damit wohl der einzige Speicherdialog in lectureStudio ohne Rückmeldung.
Um die Konsistenz der Oberfläche zu gewährleisten: eine Quittierung einbauen wie bei anderen Speicherdialogen.

**Comment by devopvoid** [comment]
Diese Option gibt es nicht mehr als einzelnen Menüeintrag. Das geht nun alles über "Dokumente speichern". Dort gibt es eine Bestätigung nach dem Speichern.

**Comment by Andy-Schuerr** [comment]
Nein, da gibt es weiterhin keine Bestätigung!

**Comment by devopvoid** [comment]
Speichern-Buttons werden ausgegraut / deaktiviert wenn gespeichert wurde und wieder aktiviert, wenn es Änderungen im Quiz gibt.
