### ISSUE TITLE
Client (V 1.3.0-76): Es fehlt doch das Recht zum Streamen eines Kurses, der einem nicht gehört

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#619]
Aktuell gibt es keine Möglichkeit einer anderen Person das Recht zu geben, dass Sie einen Kurs streamen darf, der ihr nicht gehört. Dafür muss doch wieder das Privileg "Kurs streamen" eingeführt werden. 

Im Presenter identifziert sich die Person, die für einen bestimmten Kurs das Recht zum Streamen erhalten hat, über ihr eigenes Zugriffs-Token. Beim Starten eines Streams/Nachrichtendienstes/Quizzes müssen dann alle die Kurse angeboten werden, die der Person gehören plus die Kurse, für die die Person zusätzlich das Recht erhalten hat, sie zu streamen.

Unklar ist mir: welche Rechte hat diese Person dann über das Presenter-Interface noch? Darf Sie dann Nachrichten lesen/senden/... auch wenn die entsprechenden Rechte fehlen (was eigentlich keinen Sinn macht)? Oder wird der Presenter immer wie ein Kurseigentümer behandelt, egal ob der Eigentümer des Kurses oder eine privilegierte andere Person den Stream gestartet hat.

**Comment by Andy-Schuerr** [comment]
Das Recht gibt es jetzt, aber es wird im Presenter noch nicht berücksichtigt (siehe separater Issue dazu).

**Comment by devopvoid** [comment]
> Unklar ist mir: welche Rechte hat diese Person dann über das Presenter-Interface noch?
Darf Sie dann Nachrichten lesen/senden/... auch wenn die entsprechenden Rechte fehlen (was eigentlich keinen Sinn macht)? Oder wird der Presenter immer wie ein Kurseigentümer behandelt, egal ob der Eigentümer des Kurses oder eine privilegierte andere Person den Stream gestartet hat.

Das sollte genauso behandelt werden wie in den Browser-Clients auch. Wenn z.B. Co-Organisator:innen nicht das Recht haben Nachrichten zu schreiben, dann sollte das Eingabefeld nicht sichbar sein, dementsprechend wird dies auch auf Serverseite geprüft.
