### ISSUE TITLE
Presenter/Player: Teilnehmer:innenliste/Nachrichtendienst erweitern

### ISSUE THREAD

**Issue by devopvoid** [lectureStudio/lectureStudio#631]
Für die Teilnehmer:innenliste im Player (und teilweise auch im Presenter) wären folgende zusätzlichen Features nett (ist vielleicht eine geeignete Aufgabe für eine SHK):

* Die Liste wird alternativ einstellbar nach Vor- oder Nachnamen sortiert (Player & Presenter).
* In der Liste werden Wortmeldungen durch ein entsprechendes Symbol angezeigt (Player, vielleicht auch Presenter).
* Teilnehmer:innen mit Wortmeldungen werden oben in der Liste angezeigt (in der Reihenfolge der Wortmeldungen).
* Wortmeldungen können auch auf der Teilnehmer:innenliste angenommen oder abgelehnt werden (Presenter).

Zur Diskussion für den Presenter:
* In der Teilnehmer:innenliste wird auch als Symbol angezeigt, wenn jemand eine Textnachricht versendet hat, die noch nicht
   im Presenter bearbeitet wurde (angezeigt oder quittiert). 
* Die Teilnehmer:innen mit noch nicht bearbeiteten Textnachrichten werden in punkto Sortierung in der Liste wie 
   Teilnehmer:innen mit Wortmeldungen behandelt (beides wird nach Reihenfolge der Beiträge oben in der Liste sortiert).
* In der Teilnehmer:innenliste wird (optional/konfigurierbar?) die erste Textnachricht angezeigt, die eine Teilnehmer:in
   geschickt hat und die noch nicht bearbeitet wurde. Diese Textnachricht kann aus der Teilnehmer:innenliste heraus
   quittiert oder als Folie angezeigt werden.

Mit diesen zur Diskussion gestellten Erweiterungen hätte man im Presenter die Möglichkeit praktisch vollständig auf
das Nachrichtenfenster zu verzichten, falls eine Teilnehmer:innenliste angezeigt. Dann könnte man vielleicht auch das
Nachrichtenfenster so umbauen, dass quittierte Nachrichten nicht vollständig gelöscht werden, sondern ausgegraut
weiterhin angezeigt werden. Man kann dann bei Bedarf zu bereits quittierten Nachrichten zurückscrollen, sie ggf.
nochmal als Folie zur Anzeige bringen, ... . Es sollte aber automatisch immer nach dem Quittieren einer Nachricht so weitergescrollt werden, dass die erste nicht quittierte Nachricht oben im Fenster angezeigt wird (oder das leere Fenster, falls es keine Nachricht gibt, die noch nicht quittiert bzw. angezeigt wurde).

Zur Diskussion für Player und Presenter:
* Im Player (im Presenter auch?) wird die Möglichkeit angeboten, eine Nachricht zu beantworten. Die Antwort zitiert dabei
  die beantwortete Nachricht. Die beantwortete Nachricht ist damit quittiert (und wird in der Presenteransicht durch die
  Antwort mit Zitat der beantworteten Nachricht ersetzt).

**Comment by Andy-Schuerr** [comment]
Was von der oben gewünschten Funktionalität wurde realisiert? Ich kann die aufgeführten Erweiterungsideen im Presenter nicht sehen. Wurden im Client auf dem Testsystem neue Funktionen aus der Wunschliste oben realisiert?

**Comment by Andy-Schuerr** [comment]
Es sieht für micht so aus als oben die oben skizzierten Erweiterungswünsche realisiert wären.

**Comment by Andy-Schuerr** [comment]
Der Issue hat sich erst mal dadurch erledigt, dass das Nachrichtenfenster im Presenter automatisch nach vorne geholt wird, wenn dort eine Nachricht oder eine Wortmeldung neu angezeigt wird. Das ist die bessere (und deutlich weniger aufwändige) Lösung! Ggf. muss man über Sortierungsreihenfolgen in Teilnehmerlisten dann nochmal nachdenken, wenn nur Clients miteinander im Videokonferenzmodus interagieren.
