### ISSUE TITLE
Player (V 1.3.0-82): Nachrichten werden n-fach angezeigt

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#638]
Wenn man den Player auf Android und in Chrome laufen lässt und wartet bis der Bildschirm dunkel wird, dann den Bildschirm "aufweckt", dann sieht man alle bislang eingegangenen Nachrichten n-fach. Es sieht so als ob nicht nur bei jedem Aufwecken, sondern zusätzlich alle X Minuten zwischendrin mit ausgeschaltetem/dunklen Bildschirm die bisher erhaltenen Nachrichten im Nachrichtenfenster erneut angezeigt und an die bisherige Anzeige angehängt werden.

**Comment by Andy-Schuerr** [comment]
Das Fehlverhalten ist leider noch nicht ganz korrigiert. Nachrichten werden nicht mehr doppelt bzw. n-fach angezeigt aber:
Wenn man das Tablet (Android und Chrome) beim Streaming einfach in Ruhe lässt, dann schaltet sich bei meinen gewählten Einstellungen irgendwann der Bildschirm ab und auch die Verbindung bricht ab (vermutlich weil die Browser-App in den Energieeinstellungen so eingestellt ist, dass sie nicht im Hintergrund aktiv sein darf und für die App zudem verschärfte Energiesparmaßnahmen gelten). 

Beim "Wiederaufwecken" kommt wunderschön die Meldung "Verbindung ist abgebrochen und wird wiederhergestellt". Das ist leider aber nicht der Fall. Wenn das Meldungsfenster zugegangen ist hat der Player weiterhin keine Verbindung zum Stream (es werden 0 Teilnehmer angezeigt und das Nachrichtenfenster ist leer). Erst nach einem zusätzlichen "Reload" ist die Verbindung wieder aufgebaut!

**Comment by devopvoid** [comment]
Behebungen vorgenommen. Bitte nochmal testen.

**Comment by Andy-Schuerr** [comment]
Das automatische Wiederverbindung funktioniert (zumindest auf Android) immer noch nicht nachdem der Bildschirm eingeschlafen ist. Jetzt werden nicht mehr Nachrichten doppelt angezeigt, sondern:

* Teilnehmerliste ist nach der Wiederverbindung leer.
* Der Chat zeigt nach der Wiederverbindung überhaupt keine Nachrichten mehr an, die bereits versendet wurden.

Ein Reload behebt das Problem.
