### ISSUE TITLE
Player (V 1.3.0-85): automatisches Ausblenden von Chat und Teilnehmer:innen-Liste besser signalisieren

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#644]
Wenn man das Playerfenster im Hochformat anzeigt oder ganz schmal "macht", dann werden sinnvoller Weise die Teilnehmer:innen-Liste und der Chat erst mal ausgeblendet (und als eigene Fenster angeboten). Wenn man dann Fenster wieder im Breitformat anzeigt, bleiben Chat und Teilnehmer:innen-Fenster ausgeblendet (auch wenn sie vorher eingeblendet gewesen waren). Das verwirrt, man wundert sich ggf. wo diese Unterfenster auf einmal hinverschwunden sind, insbesondere wenn man den Player zum ersten Mal benutzt. Deshalb folgende Verbesserungsvorschläge:
1) Wenn das Nachrichtenfenster ausgeblendet ist, wird das entsprechende Icon unten durchgestrichen angezeigt. Analog wird das Icon für die Teilnehmer:innen-Liste ebenfalls durchgestrichen angezeigt, wenn die Liste ausgeblendet ist (analog zu visuellem Feedback bei ausgeschaltetem Lautsprecher, ... ).
2) Man könnte sich überlegen, ob man automatisch beim "Verschmälern" des Fenster ausgeblendete Unterfenster wieder einblendet, wenn das Fenster wieder verbreitert wird.

**Comment by devopvoid** [comment]
Zu Punkt 1: Sind Chat oder Teilnehmer:innen-Liste sichtbar, dann sind die jeweiligen Icons in blau dargestellt. Durch manuelles Ausblenden oder im kompakten Modus sind die Icons schwarz, was signalisiert, dass diese Elemente nicht sichtbar sind.

Würde man die Icons durchstreichen, würden die Benutzer denken, dass es ganz deaktiviert sei. Wobei bei fehlenden Privilegien sind die Buttons dann weg.

Ich setze das mal auf "Done", da Punkt 2 umgesetzt.
