### ISSUE TITLE
Weitere Screensharing-Fehler (V 5.3.710)

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#655]
Beim Screensharing gibt es neben den bereits in einem anderen Issue gemeldeten Fehlern der Benutzeroberfläche noch folgende Fehler:

1) Screenshares für verschiedene Fenster werden im selben Tab angezeigt, das den Namen des Fensters zu dem ersten eingerichteten Screenshare. Die Screensharing-Verwaltung scheint auch durcheinander zu kommen, wenn in einem Tab mehrere Fenster für Screensharing vorbereitet werden. KORREKTUR: in dem entsprechenden Tab werden zwar die ganzen generierten Screensharing-Seiten angezeigt, aber immer nur der letzte eingerichtete Share lässt sich aktivieren. Vorschlag zur schnellen Korrektur: wenn das Screensharing über den Knopf oben in der Toolbar beendet wird, dann wird der entsprechende Tab gelöscht so wie das auch bei der Selektion des Beenden-Knopfs (mit Quadrat beschrifteter Knop) in dem Tab der Fall ist. Dann ist klar, dass man im Augenblick nur einen Screenshare einrichten und benutzen kann.
2) Wenn kein Stream läuft kann man trotzdem das Screensharing einrichten. Das macht durchaus (in Zukunft) Sinn, da man ja Screensharing auch aufzeichnen und vor allem auch auf dem externen Bildschirm (Beamer im Hörsaal) anzeigen will während lectureStudio läuft. ABER: das Screensharing lässt sich nur dann wirklich starten, wenn ein Stream läuft. Ansonsten bewirkt der Klick auf den roten Knopf zum Starten nichts.
3) Wenn man zuerst das Screensharing einrichtet und dann den Stream startet, dann wird der ausgewählte Bildschirm nicht übertragen, sondern immer nur die generierte Seite angezeigt. Diese Reihenfolge macht aber durchaus Sinn (erst alles vorbereiten und dann den Stream starten).

**Comment by Andy-Schuerr** [comment]
Die Fehler sind soweit behoben. Aber: es ist nicht möglich einen Screenshare auf einem externen Bildschirm anzuzeigen (Beamer), wenn kein Stream läuft. Dieses Szenario macht aber durchaus Sinn.

**Comment by devopvoid** [comment]
> Die Fehler sind soweit behoben. Aber: es ist nicht möglich einen Screenshare auf einem externen Bildschirm anzuzeigen (Beamer), wenn kein Stream läuft. Dieses Szenario macht aber durchaus Sinn.

Das kommt in das nächste Release. Muss mehr getestet werden, ohne die aktuelle Implementierung durcheinander zu bringen.

Die oben gemeldeten Fehler sind behoben. Bitte dazu kurz Feedback geben und "Screenshare nur auf einem externen Bildschirm anzuzeigen" als separates Issue nicht als Bug kennzeichnen?
