### ISSUE TITLE
lectureEditor (5.3.710): Timeline playback does not switch slides reliably

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#656]
**Describe the bug**
From time to time, the timeline playback of the latest version of the **lectureEditor** misses some slide switching. If this happens, the playback marker passes on to a new slide (e.g., [2] after [1]) but the preview window still shows the old slide [1] instead of the new one [2].

This happens after/while scrubbing through the timeline, but I do not know how to reproduce it effectively.

**To Reproduce**
1. Record a lecture with slide transitions in **lecturePresenter**.
2. Open the recording with **lectureEditor**.
3. Scrub through the timeline and let it play slide transitions over and over again.

**Expected behavior**
The preview of the slide(s) should view the current slide of the timeline reliably.

**Screenshots**
See attached (short) screencast of the problem.

[2022-10-11-11-00-04.webm](https://user-images.githubusercontent.com/20956405/195047589-7d2a994f-d990-454a-ada9-9d055f2570c2.webm)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit, build 19044.2075

**Comment by Andy-Schuerr** [comment]
Diesen Fehler habe ich auch schon öfter bemerkt ohne ihn zuverlässig reproduzieren zu können. Der Fehler ist kein Drama, aber lästig!
