### ISSUE TITLE
Screenshare auf einem externen Bildschirm anzuzeigen (Beamer), wenn kein Stream läuft.

### ISSUE THREAD

**Issue by devopvoid** [lectureStudio/lectureStudio#657]
Es ist nicht möglich einen Screenshare auf einem externen Bildschirm anzuzeigen (Beamer), wenn kein Stream läuft. Dieses Szenario macht aber durchaus Sinn.

_Originally posted by @Andy-Schuerr in https://github.com/lectureStudio/lectureStudio/issues/655#issuecomment-1275791909_

**Comment by Andy-Schuerr** [comment]
Dieser Issue existiert doppelt.
