### ISSUE TITLE
Client: Add possibility to sort the list of participants alphabetically

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#674]
**Is your feature request related to a problem? Please describe.**
For larger streams, it may be necessary to sort the list of participants alphabetically, e.g., to check if a specific student is a participant.

**Describe the solution you'd like**
It would be nice to have a button at the top of the participants list to sort the list alphabetically (either by the first name or by surname).

**Describe alternatives you've considered**
Maybe sort the list by default?

**Additional context**
![f7095f0cabc244959bd22dae16e1993f](https://user-images.githubusercontent.com/20956405/196739143-15a29a95-c186-4671-b642-231095c72db7.png)

**Comment by maxkratz** [comment]
Unsure if I did not get it in the first place but currently, the list is sorted alphabetically w.r.t. the last name.

**Comment by Andy-Schuerr** [comment]
Die Teilnehmer sind inzwischen nach Vornamen sortiert.
