### ISSUE TITLE
Client: Add possibility to directly answer text messages privately

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#675]
**Is your feature request related to a problem? Please describe.**
If many students participate in a streamed lecture, it is quite complicated to answer a direct message with another direct message. Currently, one has to search the list of participants in the chat window to select the right student before sending the message.

**Describe the solution you'd like**
For example, a button at every sent message "Direct reply" (or named similar) in the chat window that pre-selects the student from the original message would solve the problem.

**Describe alternatives you've considered**
(Not sure if this is already possible:) Start typing the first name of the student while having the recipient drop-down menu open -> List automatically selects the right student?

**Additional context**
Context: Chat window while participating/running a live stream.

![ba65a760c5524684a3dd8db76cc3cbb4](https://user-images.githubusercontent.com/20956405/196740606-9872fbda-d60c-43fe-9369-f60757d034db.png)

**Comment by Andy-Schuerr** [comment]
Das geht mit direkten Nachrichten an die entsprechende Person. Da die Funktionalität praktisch nicht benötigt wird, reicht das völlig aus.
