### ISSUE TITLE
Client: Chat: Selected participant changes after waiting some time

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#676]
**Describe the bug**
I observed that the selected recipient for a private text message in the chat window changes after some time. Maybe this has something to do with joining/leaving students while typing the message.

**To Reproduce**
1. Co-host a stream with multiple students taking part of the live stream.
2. Select a specific student in the chat window.
3. Start typing a message.
4. Wait a minute and/or let students join/leave the stream. (I'm not sure if the last step is necessary to reproduce this!)
5. The selected student changes to another name.

**Expected behavior**
Once selected, the name of the recipient should not change. (Exception: If the recipient stops participating in the stream; Maybe it is a good idea to select the host or ... in this case.)

**Screenshots**
![ba65a760c5524684a3dd8db76cc3cbb4](https://user-images.githubusercontent.com/20956405/196741929-edcd1d42-2642-45b4-9c10-cfbe21f7a80f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, Build 19044.2130
 - Browser: Chromium Version 108.0.5354.0 (Developer-Build) (64-Bit)

**Comment by Andy-Schuerr** [comment]
... für den Fall, dass der Empfänger einer Textnachricht den Stream verlässt während man die Nachricht schreibt, sollte es die Möglichkeit geben "none" automatisch auszuwählen. Beim Versuch die Nachricht dann wegzuschicken sollte eine entsprechende Fehlermeldung erscheinen mit der Bitte den Empfänger neu auszuwählen.
