### ISSUE TITLE
Client/lecturePresenter: Feature request: Emergency messages to the streaming host that can't be ignored

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#677]
**Is your feature request related to a problem? Please describe.**
Consider the following situation:
- The host is streaming from the lecture hall.
- A co-host is participating via the stream.
- Something "bad" happens (e.g., audio is not working, the wrong course to stream was selected, etc.) -> The co-host wants to contact the host immediately and the normal chat is not sufficient to do that. (The latter could be the case, for example, if a variety of questions were asked in the chat beforehand.)

**Describe the solution you'd like**
Maybe it is a good idea to add some kind of "emergency messages" (only from co-hosts to hosts) that can't be ignored by the host. This could be realized through a red pop-up window or another visual change in the UI of the lecturePresenter.

**Describe alternatives you've considered**
- Writing a normal chat message.
- Raising your hand (in the client).

**Comment by Andy-Schuerr** [comment]
Inzwischen kommt das Nachrichten-Tab nach vorne, wenn eine neue Nachricht eintrifft. Das sollte reichen und Emergency-Messages deshalb nicht mehr notwendig sein.
