### ISSUE TITLE
Client/lecturePresenter: Answer messages with other (co-)host(s) in "CC"

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#687]
**Is your feature request related to a problem? Please describe.**
Consider the following scenario:
- The host (Prof.) gives a lecture while streaming.
- A student writes a question in the chat.
- One of the co-hosts (WiMi) sends a response to the student (directly).
- The host is unable to see the response to the question and will likely answer it again.

**Describe the solution you'd like**
I would like to have the possibility to answer student questions via chat while also CC'ing the host (and/or all other co-hosts).

**Describe alternatives you've considered**
- Not changing anything: Questions might get answered twice/multiple times.
- Marking the chat question as "solved" for the host.
- Writing the same answer to all participants incl. the host (which is a really bad solution).
- Writing a separate message to the host (which is also a bad solution IMO).

**Comment by Andy-Schuerr** [comment]
Add-On:

A function is missing that allows one to **answer** a received message (quoting the answered message) with two options as usual (via the Client interface and not via the Presenter interface):
* The answer is sent to the sender of the received message only (reply), the original message is removed from the
   list of messages in the Presenter (this option is useful if the answer for a message sent to all participants should NOT
   be sent to all participants in turn for whatever reasons).
* The answer is sent to the sender and all other recipients of the received message (reply all), the original message is
   replaced by the answer that quotes the original message in the list of messages of the Presenter (this option is useful
   for messages that were sent to all Co-Hosts to keep the other Co-Hosts informed and for messages sent to all 
   participants to add additional explanations, etc.).

This function hopefully fulfills the needs sketched above that all (Co-)Hosts share the same state of information of received and answered messages (if useful) such that the proposed option to select additional recipients of a messages is not needed. I have difficulties to imagine a situation, where

**Comment by maxkratz** [comment]
> A function is missing that allows one to **answer** a received message (quoting the answered message)

This would solve this issue, too: https://github.com/lectureStudio/lectureStudio/issues/675

**Comment by Andy-Schuerr** [comment]
Die Erfahrung zeigt, dass es eigentlich nie passiert, dass man die Nachricht eines Studenten direkt nur diesem Studenten beantworten will. Wenn doch, hat man die Möglichkeit eine Nachricht nur an diesen Studenten zu schicken. Deshalb wird dieser Issue geschlossen.
