### ISSUE TITLE
lecturePresenter crashes on Linux when opening whiteboard or PDF

### ISSUE THREAD

**Issue by jomority** [lectureStudio/lectureStudio#7]
**Describe the bug**
lecturePresenter crashes on Linux when opening whiteboard or PDF.
Log:
```
% ./lecturePresenter      
SwixML 2.6
null
null
./lecturePresenter: symbol lookup error: /tmp/libstylus3128255548820147599.so: undefined symbol: JAWT_GetAWT
```
The second `null` line is `Untitled` instead when opening a PDF.

**To Reproduce**
1. Download and extract lectureStudio-4.3.1314-linux-x86_64 from the [Download page](https://www.lecturestudio.org/download)
2. Run `./lecturePresenter`
3. Click on "Whiteboard öffnen"
4. The program crashes

**Expected behavior**
The program should not crash and open a whiteboard instead.

**Desktop (please complete the following information):**
 - OS: Arch Linux on Gnome

**Comment by maxkratz** [comment]
Can confirm this on Linux Mint 20.1.

**Comment by devopvoid** [comment]
Should be fixed now. But not published as a new release to the homepage. You can test it, if you build the latest version of lectureStudio.

**Comment by jomority** [comment]
Yes. It works now! The whiteboard and PDF files open.

However, I cannot draw or write anything on it. Should I close this issue and open a new one?

**Comment by devopvoid** [comment]
> I cannot draw or write anything on it.

Are you running it in a VM? If so, the input coordinates may be wrong captured. This needs further testing.

> Should I close this issue and open a new one?

Yes, please, since it is not crashing any more.

**Comment by maxkratz** [comment]
The bug (crashes while open pdf/whiteboard) was fixed on my system, to.

> I cannot draw or write anything on it.

"It works on my machine" :paintbrush: (Linux Mint 20.1 Xfce)
