### ISSUE TITLE
Client (V 1.3.0-97): Doppeltes Kamerafenster bei ausgeschalteter Kamera

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#700]
Folgende Abfolge von Aktionen führt zu dieser Konfiguration der Benutzeroberfläche des Clients:
![Screenshot 2022-11-25 181133](https://user-images.githubusercontent.com/80956559/204031500-c0866712-aeb8-49ec-ae06-2c686ec5bd5b.jpg)

1) Stream starten und Client mit Stream verbinden.
2) Kamera im Presenter ausschalten.
3) Stream beenden und wieder neu starten.
4) Client wartet ohne Interaktion darauf, dass der Stream wieder startet.
5) Sobald der Stream wieder verfügbar ist, verbindet sich der Client automatisch und zeigt dann zwei leere Kamerafenster
    nebeneinander an.

**Comment by Andy-Schuerr** [comment]
Der Fehler tritt leider sporadisch immer noch auf - nach einem Reload im Client nach einem Verbindungsabbruch.
![Screenshot 2022-12-26 112544](https://user-images.githubusercontent.com/80956559/209539381-3538be2f-3dbf-4e9d-9acb-c33a24856fb3.jpg)
Leider ist der Fehler nicht reproduzierbar :-(.

**Comment by Andy-Schuerr** [comment]
Der Fehler ist in Chrome nun tatsächlich behoben. Beim Neustart des Streams wird die WebCam sofort wieder angezeigt nach dem automatischen Reconnect.

Firefox verhält sich da (auf dem selben Rechner wie der Presenter) leider anders. Wenn man beim Neustart des Streams sofort die Kamera wieder aktiviert (sobald das wieder geht, siehe anderer Issue zu Fehler beim Stream neu starten), dann erscheint erst mal kein Kamerafenster. Nach ca. einer Minute kommt es dann doch noch!

Das gleiche Fehlverhalten zeigt sich, wenn man erst den Stream wieder startet und dann erst die Kamera im Presenter einschaltet. Auch dann wird die Kamera in Chrome sofort angezeigt, während im Firefox erst mal kein Fenster erscheint.

**Comment by devopvoid** [comment]
Kann ich noch nach erneutem Verbindungsaufbau des Presenters reproduzieren. Bin dran.
