### ISSUE TITLE
Client (V 1.3.0-97): Inkonsistenz Einheitenangaben im neuen Statistikenfenster

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#701]
Im neuen Statistikenfenster werden die Bitrate von Audio und Video in "kbit/s" angegeben. Bei Dokumenten und Events wird die Einheit "KiB" verwendet. Man sollte einheitlich entweder "kbit" oder "Kbit" oder "kBit" oder "KBit" schreiben. Gesehen habe ich das alles schon.

**Comment by devopvoid** [comment]
Das sind zwei verschiedene Angaben der Datenmengen. Die Bitrate gibt man üblicherweise mit Bits an (kbit/s, Mbit/s,...). Die Datenmenge eher in Bytes. Daher auch "KiB" (KiB mit 1024 Byte statt KB mit 1000 Byte). Wenn wir das einheitlich machen mit Bits oder Bytes, dann sind entweder die Werte der Bitrate zu klein (mit 0,...) oder die Werte der Datenmenge zu groß, so dass sie kaum leserlich/verständlich werden.
