### ISSUE TITLE
lectureClient: Slides not visible in Chromium on Linux/Pop!_OS

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#709]
**Describe the bug**
In the SE1 stream last Wednesday, I was unable to see the presented slides in Chromium on my Linux/Pop!_OS system. Firefox worked fine.

**To Reproduce**
1. Go to a lecture stream on the webpage with Chromium.
2. The slides were visible in the background. The start window popped up and I clicked "Start".
3. The slides were gone.

**Expected behavior**
I expected the slides to stay visible once I started the stream participation.

**Screenshots**
Chromium:
![Screenshot from 2022-12-07 15-30-24_censored](https://user-images.githubusercontent.com/20956405/207061908-30b20d4f-81c5-4118-8b4f-16d08828b719.png)

Firefox:
![Screenshot from 2022-12-07 15-31-35_censored](https://user-images.githubusercontent.com/20956405/207061927-7d1dac5c-2f48-4fd0-ba92-7c1604819aa0.png)

**Desktop (please complete the following information):**
 - OS: Linux/Pop!_OS (Ubuntu-based) 22.04
 - Chromium 108.0.5359.94 Built on Ubuntu
 - Mozilla Firefox 107.0

**Comment by devopvoid** [comment]
Who does even use this OS?! 🥲

**Comment by maxkratz** [comment]
> Who does even use this OS?! 🥲

![](https://media.tenor.com/cEv_NDZS6GsAAAAM/hello-its-me.gif)

Number 5 on **distrowatch** for the last 12 months! (https://distrowatch.com/dwres.php?resource=popularity)

It is based on Ubuntu (in my case 22.04 LTS) but without the Snap sh... stuff. Try it :).

**Comment by maxkratz** [comment]
Update:
It seams to me that slides are visible in Chromium on the mentioned system in most cases. However, the first slide is sometimes missing if the client does not receive a "change slide" event.
