### ISSUE TITLE
lecturePresenter (v5.3.725): First run of slide presentation only shows a fraction of the complete slide on presentation monitor/beamer

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#710]
**Describe the bug**
At least with my lecturePresenter installation, the first run of the slide presentation function (to show the slides, e.g., on the attached monitor/beamer) only shows a fraction of the slide.
This is best visible in the attached screenshots.

With my Windows 10 machine, this behavior can be reproduced with the monitors at my home/office and with the USB-C graphic tablet at FGES.

**To Reproduce**
1. Start lecturePresenter and open a PDF file.
2. Click on the small monitor icon to start the presentation
3. Look at the presentation monitor and observe only a fraction of the slide.
4. Start & stop the presentation and everything is fine.

**Expected behavior**
The complete slide should be shown on the presentation monitor/beamer, also for the first run.

**Screenshots**
First run (screenshot on all monitors at the same time):
![Unbenannt](https://user-images.githubusercontent.com/20956405/207063262-fc6631b3-dcc7-45a1-b68a-746f22cb3e59.PNG)

Second run (screenshot on all monitors at the same time):
![Unbenannt2](https://user-images.githubusercontent.com/20956405/207063318-049088c8-fd58-4ab0-a78c-ee3d614df9c7.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 22H2, 19045.2311

**Comment by Andy-Schuerr** [comment]
Der Fehler ist leider immer noch vorhanden, siehe neuer Screenshot.  Er lässt sich auch bei mir mit zugeklapptem Notebook und zwei externen Bildschirmen zuverlässig reproduzieren. Man muss nur gleich nach dem Start des Presenters sofort den externen Bildschirm aktivieren (siehe Screenshot zur Bildschirmkonfiguration).
![Screenshot 2022-12-26 111848](https://user-images.githubusercontent.com/80956559/209537894-2517036b-860e-42eb-b1c3-b9879a5fe326.jpg)
![Screenshot 2022-12-26 112232](https://user-images.githubusercontent.com/80956559/209537898-2c894d28-cbc4-40ab-9250-ec1b798d6fb2.jpg)
