### ISSUE TITLE
lecturePresenter (v5.3.725): Text boxes are buggy in multiple ways

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#711]
**Describe the bug**
The annotation feature "text boxes" is buggy in multiple ways:
- The window around the text does not fit onto the text in every case. (Screenshot **(1)** below.)
- Moving around a text box with the mouse creates artifacts. (Screenshot **(4)** below.)
- While typing text into a text box, the text only appears on the screen but **not** at the beamer/monitor presentation. (Screenshot **(2)** below.)
  - Sometimes the text appears on the presentation monitor after I've finished writing it.
  - Sometimes, I had to do multiple other actions, e.g., create a pencil annotation, to make it appear. (Screenshot **(3)** below.)
- Text boxes can not be removed with the eraser.

**To Reproduce**
1. Start lecturePresenter and open a PDF file.
2. Click on the text tool, click on a slide, and start typing text.
3. See the errors listed above.

**Expected behavior**
- The window around the text should fit in *every* case.
- Moving around text windows should never create rendering artifacts.
- While typing text into a box, the individual letters should appear in the stream *and* the presentation monitor at the same time. (Preferably while writing it instead of "at once" at the end.)
- Text boxes should be removable with the eraser tool (as it is the case with hand-written annotations).

**Screenshots**
(1) Text box in the presenter isn't visible on the presentation monitor.
![Unbenannt2](https://user-images.githubusercontent.com/20956405/207065467-821e3921-6f3b-461f-92e4-d2e3a47864ec.PNG)

(2) Text written with the text tool appears partly outside its box within the presenter's view.
![Unbenannt3](https://user-images.githubusercontent.com/20956405/207065589-850d12e7-8ac0-4e23-a997-090c9bf76ccc.PNG)

(3) Text written with a text tool only appears on the presentation monitor after drawing something with the pencil tool.
![Unbenannt4](https://user-images.githubusercontent.com/20956405/207065783-b1ef1ae7-0836-4359-b0e3-ffd943b5a7bc.PNG)

(4) Moving text boxes around creates rendering artifacts.
![Unbenannt5](https://user-images.githubusercontent.com/20956405/207066317-1000448f-b095-451b-ae0f-0f1ba90a1d80.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 22H2, 19045.2311

**Comment by devopvoid** [comment]
Has been fixed since version 5.3.756

**Comment by Andy-Schuerr** [comment]
Das "Text"-Tool ist immer noch fehlerhaft:
- Zeilenumbrüche werden im Stream ignoriert (siehe Screendumps).
- Texte werden auf dem externen Bildschirm überhaupt nicht (mehr) angezeigt (siehe Screendump).
- Mit dem Radiergummi lassen sich Texte weiterhin nicht löschen (das wäre viel natürlicher als die
  Anzeige eines "x" am Fenster über das sich ein Text wieder löschen lässt.
![Screenshot 2022-12-25 192516](https://user-images.githubusercontent.com/80956559/209478766-0599c6bb-81be-417d-bb85-7ce80956026e.jpg)
![Screenshot 2022-12-25 192534](https://user-images.githubusercontent.com/80956559/209478767-35c05092-00fb-421d-8284-ec6f8e67ea7a.jpg)
![Screenshot 2022-12-25 192808](https://user-images.githubusercontent.com/80956559/209478772-bda42f5c-79c2-47e5-9131-11feb4ea9103.jpg)

Zudem: 
- Der große Fensterrahmen um den Text herum im Presenter stört eigentlich. Besser wäre entweder gar kein
   Rahmen oder ein ganz dünner Rahmen, damit die Anzeige im Presenter und im Stream bzw. auf dem
   externen Bildschirm möglichst ähnlich sind.

**Comment by devopvoid** [comment]
Die Textboxen kann ich gerne anpassen und das "X" zum Löschen dieser Textbox entfernen. Der dickere obere Rahmen dient hauptsächlich dazu, die Textbox zu verschieben. Ist der Rahmen oben dünner, so lässt es sich mit einem Stift schwer treffen.

Alternative zum Verschieben der Textbox ("X" entfernt und ganz dünner Rahmen).
- Mit Stift/Maus auf den Inhalt (Text) der Textbox klicken und ziehen. Damit lässt sich dann aber der Text nicht mehr markieren.
- Oder in der Toolbar ein Tool hinzufügen, mit dem alle Annotationen verschoben werden können. Hier gibt es schon die Möglichkeit Annotationen klonen, verschieben und durch ein Rechteck mehrere Annotationen auswählen.

**Comment by Andy-Schuerr** [comment]
Die Fragen oben zum Verschieben der Textboxen hatte ich mir auch gestellt. Ich fürchte, ich bin der Falsche für ihre Beantwortung, da ich nie Textannotationen benutze. Meine Vermutung:
- Annotationen klonen wird man praktisch nie benutzen (ich sehe da keinen rechten Anwendungsfall für)
- Nicht-Text-Annotationen verschieben braucht man definitiv nicht. In all den Jahren der Nutzung von lectureStudio
  hatte ich nicht einmal das Bedürfnis eine Stiftmarkierung zu verschieben. Bei Textboxen sieht das vielleicht anders
  aus, wenn der Text wächst und nicht mehr so recht in den dafür vorgesehenen Platz passt oder so.
- Andererseits kann ich mir schon vorstellen, dass man bei einem längeren selbst geschriebenen Text mal was
  markieren oder unterstreichen will.

Wie wäre es, wenn man das optisch störende "x" entfernt (und konsistent mit Radiergummi löscht) und zudem der
Textrahmen von kräftig grün auf ziemlich durchsichtig hellgelb umgestellt wird (so dass man ihn gerade noch gut
sieht und wenn möglich dadurch ggf. verdeckte Teile der Folie "durchsehen" kann)?

Ansonsten sollen sich am besten Max und Andreas Koch dazu äußern, die das Texttool wirklich nutzen.

**Comment by devopvoid** [comment]
Alle oben gemeldeten Fehler sind behoben, lectureStudio und Client aktualisiert.

Presenter hat in den Toolbar-Einstellungen einen neuen Button zum Verschieben von Annotationen:
<img src="https://user-images.githubusercontent.com/58339654/209975120-be6b227b-16da-4791-8375-1088d88e0256.png" width="40">

**Comment by Andy-Schuerr** [comment]
Die Umstellung der Rahmen ist wunderbar geworden! Leider gibt es aber noch zwei Fehler:
1) Folgender Ablauf funktioniert im Client nicht:
    - Ein Text "Test" wird einzeilig angelegt
    - Ein weiterer Text "a" wird dicht darunter in einer neuen Box geschrieben
    - Der Text "Test" wird um eine weitere Zeile erweitert
    - Jetzt überlappen die beiden Textboxen leicht und die zweite Textbox wird im Client nicht mehr angezeigt
      (siehe Screendump)
![Screenshot 2022-12-30 122457](https://user-images.githubusercontent.com/80956559/210065634-2410df72-95fe-45d8-b500-d24f468f4f18.jpg)

2) Schnelles Verschieben von Textboxen führt immer noch zu Artefakten auf dem externen Bildschirm (siehe Screendump)
![Screenshot 2022-12-30 122530](https://user-images.githubusercontent.com/80956559/210065705-cc69604b-151c-48e6-a614-160b811f8dce.jpg)
