### ISSUE TITLE
lecturePresenter: Feature request to hide text boxes created with the text tool

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#712]
**Is your feature request related to a problem? Please describe.**
This feature request is loosely coupled to this issue: https://github.com/lectureStudio/lectureStudio/issues/711

Currently, the boxes around text (created with the text tool) are always visible in the stream, the presenter view, and the presentation monitor.

**Describe the solution you'd like**
In short: I would like a feature to enable and disable the text boxes around written text globally in lecturePresenter. This could, e.g., be a config checkbox in the settings menu.

![feature-request-boxes](https://user-images.githubusercontent.com/20956405/207067658-3ab1a24a-fa06-4237-bb46-3ed70100ed82.PNG)

**Comment by devopvoid** [comment]
Durch den dünnen Rahmen von Textboxen können wir dieses Issue schließen?

Zumal, wenn ein anderes Werkzeug ausgewählt ist, ist der Rahmen auch nicht zu sehen.

**Comment by Andy-Schuerr** [comment]
Das ist denke ich jetzt wunderbar gelöst!
