### ISSUE TITLE
Presenter (V 5.3.761): Zugriff auf Log-Verzeichnis über "Info" und Konvertierung alter Quiz-Dateien funktioniert nicht

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#718]
Manchmal (nicht reproduzierbar) funktioniert der Zugriff auf das Log-Verzeichnis über "Info/Log" nicht. Es erscheint dann die Fehlermeldung "Bitte kontaktieren Sie ihren Systemadministrator. Vollständige Details finden Sie im Anwendungsprotokoll".

Ausgangslage:
* Betriebssystem: Windows 10
* Im Log-Verzeichnis befinden sich zwei Dateien mit dem Namen "presenter-5.3.761-Datum" und eine Datei mit dem Namen "presenter-5.3.761".

Das Löschen der Datei "presenter-5.3.761" behebt in einem Fall das Problem. Es wird dann eine neue Datei mit Namen "presenter-5.3.761" angelegt. In einem zweiten Versuch hilft das Löschen dieser Datei nichts.

Das Problem wird interessanterweise anscheinend durch einen anderen Fehler ausgelöst: der Versuch der Konvertierung einer alten "QUIZ"-Datei in das neue "QUIZZES"-Format. 

Beispiel:
- Passsend zu PDF mit Namen "SE2-2023-05-22.pdf" existiert eine QUIZ-Datei "SE2-2023-05-22.QUIZ" aus dem vorigen Jahr
   (wurde umbenannt, die Umbenennung ist aber nicht die Ursache für den Fehler)
- Beim Starten der "Quiz auswählen"-Funktion wird die alte QUIZ-Datei umbenannt in "SE2-2023-05-22.QUIZ.backup",
   es wird aber keine "QUIZZES-Datei" im neuen Format angelegt.
- Nach dem Schließen des Auswahldialogs für Quizze funktioniert der Zugriff auf das Log-Verzeichnis nicht mehr.

Eine neu erzeugte Datei "presenter-5.3.761" enthält die Fehlermeldung "Open log path failed":
[presenter-5.3.761.log](https://github.com/lectureStudio/lectureStudio/files/10373364/presenter-5.3.761.log)

**Comment by devopvoid** [comment]
Das hängt mit der mitgelieferten Javaversion zusammen. Werde auf die zuletzt bekannte stabile Version zurücksetzen.
