### ISSUE TITLE
Presenter (V 5.3.761): Quiz-Legende in Diagrammen zu hoch bzw. ungünstig platziert

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#725]
Wenn man einen Quiz mit Mehrfachauswahl-Fragen stellt und die Quiz-Teilnehmer viele Antwortkombinationen auswählen (was fast immer der Fall ist), dann enthält die Legende dieser Antwortkombinationen sehr viele Einträge. Sie ist dann ungünstig so platziert, dass sie nach oben über den Rand des erlaubten Anzeigebereichs hinausragt und nach unten die Texte der verschiedenen Antwortmöglichkeiten überschreibt (siehe Screendump).
[Quiz-Legende.pdf](https://github.com/lectureStudio/lectureStudio/files/10418086/Quiz-Legende.pdf)

Vielleicht kann man die Legende weiter nach rechts verlagern und dafür den Anzeigebereich für die Textantworten etwas schmaler wählen. In jedem Fall sollte die Legende nicht nach oben und unten wachsen, sondern nur nach unten.

**Comment by devopvoid** [comment]
Vorschlag: Legende entfernen und Optionen (Buchstaben) in die X-Achse verschieben.

Bei nicht allzu vielen Variationen:
![grafik](https://user-images.githubusercontent.com/58339654/214668037-57a3d310-290c-47a9-bbd7-6ef7e2326aca.png)

Bei vielen Variationen werden die Optionen im 45° Winkel dargestellt:
![grafik](https://user-images.githubusercontent.com/58339654/214667017-51459a6d-3ec6-4201-96b6-af41ffc67ed8.png)
