### ISSUE TITLE
Presenter (V 5.3.675): Stream startet nicht

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#727]
Folgende Sequenz von Aktionen führt auf Windows 10 dazu, dass ein Stream nicht gestartet wird (nur der Nachrichtendienst wird gestartet):

1) Presenter neu starten (Clients warten bereits im Kurs/Stream).
2) Screenshare einrichten mit einem Fenster.
3) Anzeige auf dem externen Bildschirm aktivieren.
4) Screenshare aktiveren und pausieren (mehrfach).
5) Screenshare beenden.
6) Stream starten.
7) Anzeige auf dem externen Bildschirm beenden.

Nun zeigt die Kursübersicht an, dass für den entsprechenden Stream der Nachrichtendienst gestartet wurde, aber der Stream selbst nicht. Entsprechend gehen die Clients in den Hörsaalmodus.

Die Log-Datei sieht wie folgt aus:
[presenter-5.3.765.log](https://github.com/lectureStudio/lectureStudio/files/10471828/presenter-5.3.765.log)

**Comment by devopvoid** [comment]
Reproduzierbar mit weniger Schritten:
1. Presenter starten.
2. Screenshare starten und beenden.
3. Stream starten.

Ist für die nächste Version behoben.
