### ISSUE TITLE
Presenter (V 5.3.767): Anlegen eines Unterverzeichnisses für Screenshare-Aufzeichnungen

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#733]
Da beim Aufzeichnen von Screenshares zusätzliche Videodateien angelegt werden, könnte es sinnvoll sein, in diesem Fall alle Aufzeichnungen in einem gemeinsamen Unterverzeichnis abzulegen. Das würde dann vielleicht die Bearbeitung im Editor später erleichtern, wenn dort die normale Aufzeichnung an den entsprechenden Stellen Verweise auf die Videos der Screenshares enthält.

**Comment by Andy-Schuerr** [comment]
Mit der vollen Unterstützung von Screenshares auch im Editor und beim Rendern von Videos wird diese Anforderung wichtiger. Alle Dateien einer Aufzeichnung sollten unbedingt in einem Verzeichnis liegen und die Verweise aus der Hauptaufzeichnung in die zusätzlichen  Videos von Screenshares relative Dateipfade dafür nutzen.

**Comment by devopvoid** [comment]
Momentan werden Screenshares in das Verzeichnis gespeichert, das in den Presenter-Einstellungen unter Aufnahme - Aufnahmeverzeichnis konfiguriert ist. Die .presenter-Datei speichert dazu den Videopfad relativ ab. Das heißt, dass die Screenshare-Videos sich immer im selben Ordner mit der dazugehörigen Presenter-Aufzeichnung befinden müssen.

**Comment by Andy-Schuerr** [comment]
Die Änderung des Unterverzeichnisses für Aufzeichnungen in den Einstellungen ist wirkungslos. Man muss erst einmal beim Speichern einer Aufzeichnung in dem dann aufgehenden Dialog das gewünschte Unterverzeichnis auswählen, dann wird das auch im Folgenden genutzt. Damit ist die entsprechende Option in den Einstellungen (bislang) völlig wirkungslos.
