### ISSUE TITLE
lectureEditor (V 5.3.767): Behandlung von Aufzeichnungsnamen mit Umlauten

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#737]
Wenn man eine Aufzeichnung so umbenennt, dass der neue Name eine Umlaut wie "ä" oder ... enthält, dann wird beim Öffnen des Dialogfensters zum Rendern der Dateiname rot angezeichnet und der Start des Renderns verweigert. Allerdings erhält man keine erläuternde Fehlermeldung, sondern muss selbst darauf kommen, dass der Umlaut im Dateinahmen der Aufzeichnung das Rendern blockiert.

Gewünschte Änderung: zusätzlich zur roten Markierung des Dateinamens eine Fehlermeldung anzeigen, die das Problem erläutert!

**Comment by devopvoid** [comment]
Die Validierung wurde erweitert, damit sind Umlaute auch erlaubt. Verboten ist zum Beispiel das * Zeichen. Wegen Betriebssystem spezifischen Fehlermeldungen ist die Sprache momentan auf Englisch. Lässt sich mit der Zeit übersetzen.
