### ISSUE TITLE
lecturePresenter/Client (V 5.3.767): Layout von Quizzen inkonsistent

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#738]
Bei Quizzen mit Item-Listen im Haupttext ist das Layout in Quiz-Editor, Presenter (PDF-Folien) und Client unterschiedlich, was die Herstellung eines "schönen" Layouts fast unmöglich macht. Wie man in den Screendumps sieht sind die Zeilenabstände vor und nach dem Item-Block unterschiedlich
- ist im Quiz-Editor nach dem Item-Block etwas größer als vorher
- im Presenter (auf den PDF-Folien) gleich
- im Client nach dem Item-Block sehr viel größer als vorher

![Screenshot 2023-02-24 135801](https://user-images.githubusercontent.com/80956559/221185448-89416bcd-b8d8-412d-b695-277c85c4e1fb.jpg)
![Screenshot 2023-02-24 135814](https://user-images.githubusercontent.com/80956559/221185456-e93d702b-b297-4cdd-902f-20dad04bf78f.jpg)
![Screenshot 2023-02-24 135843](https://user-images.githubusercontent.com/80956559/221185466-332d9270-79c5-4a1c-8e7f-92d75a817d5f.jpg)

**Comment by Andy-Schuerr** [comment]
Das Layout von Item-Listen ist immer noch inkonsistent. Im Presenter gibt es vor einer Itemliste mit Bullets einen deutlichen Abstand zum vorhergehenden Absatz (gleicher Abstand wie zu Absatz nach Item-Liste), im Client gibt es diesen Abstand nicht. Das wird vermutlich mit der nächsten Client-Version behoben sein, die installiert wird (getestet habe ich mit lect.stream)?!

**Comment by devopvoid** [comment]
Genau, die Client-Version, wenn neu aufgespielt, hat die Inkosistenz behoben.
