### ISSUE TITLE
lecturePresenter (4.4.78): Reproduzierbare schwarze Artefakte bei handschriftlichen Annotationen

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#74]
Mir ist es gerade gelungen ebenfalls auf dem Whiteboard beim schnellen Stricheziehen mit dem Stift-Werkzeug ein schwarzes Artefakt zu erzeugen. Das erste Beispiel dieser Art befindet sich im Ordner "Schwarzes-Artefakt" im bekannten Hessenbox-Ordner.
Leider kann ich keine Log-Datei dazu liefern. Der lecturePresenter hat in diesem Fall keine Log-Datei angelegt - warum auch immer!?

Ein zweiter Versuch war ebenfalls erfolgreich - aber man muss dabei Geduld haben! Mein Eindruck: wenn man sehr schnelle Stiftbewegungen durchführt, die (weit) über die Ränder des weißen Blattes hinausgehen, dann bekommt man mit viel Glück oder Pech ein schwarzes Artefakt. Das Ergebnis des zweiten Versuchs habe ich im Ordner "Noch-ein-Artefakt" abgelegt, dieses Mal mit Log-Datei und Screendump.

Ein dritter und vierter und fünfter Versuch war ebenfalls "erfolgreich": wenn man schnelle kreisförmige Stiftbewegungen auf dem Whiteboard (mit der Maus) erzeugt, die sehr oft über die Ränder des Whiteboard-Blattes hinausgehen, erhalte ich inzwischen zuverlässig schwarzes Vielecke als Artefakte.

**Comment by devopvoid** [comment]
Duplicate of  #41

**Comment by Andy-Schuerr** [comment]
Leider kann man immer noch schwarze Artefakte mit dem Stift auf dem Whiteboard produzieren. Das geht, in dem man ganz schnell bei selektiertem Stift die Maus hin und her bewegt (ca. 10 Sekunden lang). Irgendwann bekommt man dann ein schwarz ausgefülltes Kreissegment statt einen Stiftstrich. Im Log steht nichts sinnvolles dazu drin. Hier das entsprechende pdf:
[Vorlesung-2021_12_17-09_23.pdf](https://github.com/lectureStudio/lectureStudio/files/7733637/Vorlesung-2021_12_17-09_23.pdf)
