### ISSUE TITLE
lectureClient: Ausloggen funktioniert nicht

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#746]
Wenn man beim lectureClient (unter Chrome) rechts oben im Drop-Down-Menue, das mit dem eigenen Namen bezeichnet wird, "Ausloggen" anwählt, dann kommt man auf die "Einloggen"-Seite. Wenn man dort "Einloggen" wählt ist man wieder als die gerade ausgeloggte Person eingeloggt ohne dass man TU-ID oder Passwort neu eingeben muss. Das ist nicht so ganz das was man erwartet.

**Comment by devopvoid** [comment]
Braucht ca. 1 Minute, dann wird intern ausgeloggt.
