### ISSUE TITLE
lecturePresenter (4.4.89): Beim Beenden erscheint der Erinnerungsdialog zum Abspeichern von pdfs nicht mehr

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#75]
In der neuestesn Version des lecturePresenters erscheint der Erinnerungsdialog zum Abspeichern von pdfs nicht mehr. Das ist vielleicht Absicht, weil man nun ja pdfs auch im Editor abspeichern kann?

**Comment by devopvoid** [comment]
Der Erinnerungsdialog in lecturePresenter zum Abspeichern von PDFs erscheint nur, wenn persistente Annotationen gemacht wurden. Auch wenn zuvor selbst abgespeichert wurde und es keine neuen Annotationen gibt, wird der Erinnerungsdialog nicht angezeigt.
