### ISSUE TITLE
lecturePresenter: Speichern einer Aufzeichnung dauert endlos und es gibt kein GUI-Feedback zum Fortschritt

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#750]
Gerade habe ich mal wieder eine ganze Vorlesung aufgezeichnet (knapp 90 Minuten). Das Speichern beim Beenden der Aufzeichnung hat endlos gedauert (bestimmt eine Minute) und das entsprechende Fenster mit dem "Abbrechen"-Knopf stand endlos ohne irgendein weiteres Feedback auf dem Bildschirm. Beinahe hätte ich den lecturePresenter-Prozess mit dem Task-Manager beendet weil ich die Geduld verloren habe. Deshalb folgender Vorschlag:

Kann man nicht in den Speicherdialog für das Abspeichern von Aufzeichnungen auch einen Fortschrittsbalken einbauen, damit man nicht in die Versuchung kommt, den Presenter-Prozess zu beenden, weil man vermutet, dass er "abgestürzt" ist. Das wäre echt hilfreich!

**Comment by devopvoid** [comment]
Fortschrittsbalken war da, nur wenn es - aus welchen Gründen auch immer - keinen Fortschritt gab, bewegt sich auch nichts. Jetzt gibt es neben dem Fortschritt in Prozent einen sich bewegenden Balken, der als Indikator dienen soll, dass die Anwendung nicht "eingefroren" ist.
