### ISSUE TITLE
Presenter (V 5.3.785): Lange Quiz-Zeilen sind immer noch ein Problem

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#754]
Beim Editieren des einleitenden Textes eines Quizzes hat man Probleme mit dem Zeilenumbruch. Wenn man im Quiz-Editor bei langen
Zeilen (damit man nicht nach rechts scrollen muss bei der Eingabe) Zeilenumbrüche einführt, dann werden diese Zeilenumbrüche auch bei der Folienanzeige verwendet (zusätzlich zu automatisch durchgeführten Zeilenumbrüchen). Das führt teilweise zu einem unschönen
Layout auf der generierten Folie. Hilfreich wäre, wenn deshalb

* entweder im Texteingabefenster bei der Quiz-Erstellung eine Zeile sich nicht endlos nach rechts erstreckt, sondern automatisch umgebrochen wird (ohne dass dafür harte Zeilenumbrüche eingefügt werden, die dann Einfluss auf das Textlayout auf der generierten
Folie haben)
* oder aber es zwei verschiedene Arten von Zeilenumbrüchen bei der Texteingabe gibt (solche, die nur das Layout im Textfenster
beeinflussen und andere, die auch das Layout auf der generierten Folie beeinflussen)
* oder aber Zeilenumbrüche nur dann beim Folienlayout berücksichtigt werden, wenn ein neuer Absatz beginnt (bei der Texteingabe
durch eine Leerzeile gekennzeichnet).

Was davon lässt sich am einfachsten realisieren?

**Comment by devopvoid** [comment]
Option 1 funktioniert bereits, siehe Screenshots:

**Editor im Presenter:**
![image](https://github.com/lectureStudio/lectureStudio/assets/58339654/ff54b625-e307-4934-814c-08e543691f5a)

**Generierte Folie:**
![image](https://github.com/lectureStudio/lectureStudio/assets/58339654/e7439a4b-14c5-49f1-9e85-306fc181386f)

**Comment by Andy-Schuerr** [comment]
Das Problem besteht nach wie vor. Wenn man lange Absätze hat, bei denen ein automatischer Zeilenumbruch im angezeigten Quiz (auf der generierte PDF-Seite) erfolgen soll, dann muss man diese Absätze in eine Zeile im Quizeditor schreiben. Diese Zeile geht im Eingabefenster beliebig lang nach rechts weiter ohne dass im Eingabefenster ein automatischer Zeilenumbruch passiert. Das ist sehr lästig, weil man dann dauernd links/rechts scrollen muss und man immer nur Teile des Textes im Eingabefenster sieht. 
Wenn man stattdessen den Text über mehrere Zeilen verteilt (ohne Leerzeile dazwischen)
wie hier in diesem Text,
dann werden diese Zeilenumbrüche in das PDF mit übernommen.
Das ist auch nicht das was man will.
