### ISSUE TITLE
Presenter (V 5.3.844): Konsistenz der Menues für Positionierung von Unterfenstern

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#778]
Die Menues für das Auskoppeln von Unterfenstern (Nachrichten etc.) und das Auswählen einer Position als Unterfenster im Presenter-Fenster sind zufällig geordnet (unterschiedlich). Sinnvoll wäre in beiden Menues die gleiche Reihenfolge für Nachrichten-, Notizen-, ... Fenster zu verwenden. Als Sortierkriterium kann man entweder alphabetisch sortieren oder nach Wichtigkeit ... .

**Comment by devopvoid** [comment]
Habe es zunächst nach Wichtigkeit sortiert.
