### ISSUE TITLE
Client (V 1.5.033): Leere Folienseite wird bei Stream-Betreten angezeigt statt aktuelle Folie

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#793]
Wenn man zwei Foliensätze im Presenter offen hat und dann einen Stream startet (mit sofort eingeschalteter Kamera), dann wird oft (aber nicht immer) im Chrome-Client nicht die im Presenter ausgewählte Folie angezeigt, sondern stattdessen eine leere weiße Seite. Das Problem tritt vermehrt dann auf, wenn die gewählten Foliensätze SEHR GROSS sind. Es reicht dann ggf. auch ein einzelner GROSSER Foliensatz!

Mein Eindruck: während der Client PDF-Dokumente lädt gehen Events verloren. Das können manchmal die Events sein, dass die Kamera bereits eingeschaltet ist oder die Events, die die aktuell angezeigte Folie übermitteln.

Mit diesem Testaufbau (einfach die gesamten PDF-Skripte von SE1, SE2, ES nutzen) kann ich relativ zuverlässig den Fehler provozieren (insbesondere mit langsamerer WLAN-Anbindung).  Manchmal tritt dabei auch das in einem anderen Issue beschriebene Kamera-Problem auf (der Client merkt nicht, dass die WebCam der DozentIn eingeschaltet ist).

**Comment by devopvoid** [comment]
Reproduzierbar nachdem ein Stream gestoppt wurde und dann wieder gestartet wird, mit mehreren offenen Dokumenten. Sollte nun behoben sein.

**Comment by Andy-Schuerr** [comment]
Das Problem ist bei mehreren Testversuchen mit dem oben geschilderte Prozedere nicht mehr zu provozieren.
