### ISSUE TITLE
lecturePresenter (4.4.89): Inkonsistenzen in pdf-Speicherdialogen

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#81]
Die pdf-Speicherdialoge des Presenters sind noch nicht konsistent:
1) Beim zusammengeführt speichern wird nicht (mehr?) nach eine Verzeichnis zum Abspeichern gefragt, sondern einfach
    im User-Verzeichnis abgespeichert.
2) Bei den Dialogen zum einzelnen Abspeichern von Folienannotationen oder Whiteboard wird das ausgewählte 
    Verzeichnis nicht gemerkt, sondern immer wieder neu im User-Verzeichnis gestartet.

**Comment by devopvoid** [comment]
> 1. Beim zusammengeführt speichern wird nicht (mehr?) nach eine Verzeichnis zum Abspeichern gefragt, sondern einfach
> im User-Verzeichnis abgespeichert.

Hierfür gibt es den `Durchsuchen...`-Button unter "Angekreuzte Dokumente in eine Datei zusammenführen".
