### ISSUE TITLE
Presenter (V 6.0.863): Oberfläche für neuen Browser/Client

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#810]
Wenn man beim Starten eines Streams die Option anwählt, dass man einen Client in der Browseroberfläche sehen will, dann muss man anschließend nochmal den zu streamenden Kurs auswählen (da erscheint eine entsprechende Dialogbox) obwohl der Kurs schon gestreamt wird. Mit dem neuen Browserfenster kann man überprüfen ob sich ein Client erfolgreich mit dem Server verbinden und die aktuelle Folie anzeigen kann. Nicht möglich ist die Überprüfung ob
- das Kamerabild in Ordnung ist (es wird das Webcam-Bild nicht angezeigt obwohl die Kamera aktiviert ist)
- Fortschalt-Events beim Client ankommen (davon kann man vermutlich ausgehen, dass das immer klappt),
  weil die Benutzeroberfläche des Presenters in diesem Augenblick ja gesperrt ist.
Letzteres kann man aber testen, wenn man den Client separat startet. Aber auch dann wird kein Kamerabild angezeigt.

**Comment by devopvoid** [comment]
Das mit der Dialogbox ist redundant mit #817, was nun behoben sein sollte.

> Nicht möglich ist die Überprüfung ob
> das Kamerabild in Ordnung ist (es wird das Webcam-Bild nicht angezeigt obwohl die Kamera aktiviert ist)

Das sollte auch nicht mehr vorkommen. Falls doch, dann ist es eher ein Fehler im Client.

> Fortschalt-Events beim Client ankommen (davon kann man vermutlich ausgehen, dass das immer klappt),
> weil die Benutzeroberfläche des Presenters in diesem Augenblick ja gesperrt ist.

Ich denke hier geht es hauptsächlich darum zu prüfen, ob der Stream samt Kamera überhaupt gestartet ist und Teilnehmer:innen es sehen können. Es gleich in einem separatem Fenster zu starten erfordert mehr Interaktionen, wenn die Annotationen auch überprüft werden sollen. Daher so lassen wie es jetzt ist?
