### ISSUE TITLE
lectureEditor (v5.3.725): `File`/`Save As...` does not add `.presenter` to suggested file name (on Linux)

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#812]
**Describe the bug**
The current stable release of the lectureEditor (v5.3.725) does not add the file ending `.presenter` to the suggested file name when saving the project (on Linux).

(I could not reproduce this bug on Windows.)

**To Reproduce**
1. Create a recording with the lecturePresenter.
2. Open the recording with lectureEditor on Linux.
3. Click on `File`/`Save As...`
4. Missing `.presenter` in the given file name.

**Expected behavior**
As on Windows, the file save dialogue should automatically add the `.presenter` file ending to the suggested file name.

**Screenshots**
![Screenshot from 2023-09-29 09-37-55](https://github.com/lectureStudio/lectureStudio/assets/20956405/6160e082-2707-40c6-84c7-a4763c15f662)

**Desktop (please complete the following information):**
 - OS: Linux/Pop!_OS (Ubuntu-based) 22.04

**Comment by devopvoid** [comment]
The extension will now be added automatically (if missing) before saving.

**Comment by maxkratz** [comment]
> The extension will now be added automatically (if missing) before saving.

I've tested it with the latest release and it works as expected -> will close this issue.
