### ISSUE TITLE
Presenter (V 6.0.863): Löschen von Annotationen mit dem Mülleimer funktioniert nicht immer

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#814]
Folgender Ablauf führt zu einer fehlerhaften Anzeige auf dem externen Bildschirm:
1) Es werden mehrere Stiftannotationen durchgeführt auf dem Whiteboard.
2) Anschließend wird das Mülleimerwerkzeug benutzt um alle Annotationen auf der Seite zu löschen.
3) Danach sind in der Client-Anzeige alle Annotationen gelöscht, aber auf dem externen Bildschirm
    bleiben einige (Teil-)Annotationen erhalten.
4) Ein nochmaliges Selektieren des Mülleimers löscht dann auch diese Annotationen.

**Comment by devopvoid** [comment]
Die Annotationen werden schon gelöscht, nur die Oberfläche auf dem externen Bildschirm falsch gerendert. Externe Ansicht im Presenter zum Beispiel de- und aktivieren zeigt dann alles korrekt an.
