### ISSUE TITLE
lectureEditor (4.4.89): neue pdf-Speicherfunktion ignoriert Annotationen auf Folienrändern

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#82]
Anders als die pdf-Speicherfunktion im lecturePresenter ignoriert die Speicherfunktion im lectureEditor alle Annotationen auf erweiterten Rändern von Folien oder Whiteboard. Das ist konsistent zur Anzeige im Folienstrom, aber nicht konsistent zum Speicherverhalten im lecturePresenter. Die Frage ist, was der Nutzer an dieser Stelle erwartet.

Vorschlag: diesen Issue erst mal nicht bearbeiten, sondern warten bis weitere Benutzer über dieses Verhalten "stolpern" und sich eine Änderung wünschen. Die Nutzung von Folienrändern ist denke ich sowieso ein exotischer Anwendungsfall!

**Comment by elenziat** [comment]
Die Beschreibung, dass die Annotationen auf dem Folienrand ignoriert werden, trifft es nicht ganz. Wenn die Folie mit eingeschalteten erweitertem Rand verlassen wird, wird diese aus dem beim Export aus dem lectureEditor auch mit diesem Rand und damit auch den dort vorhandenen Annotationen exportiert.

Ich fände es am logischsten, wenn diesbezüglich das Verhalten beim Export aus dem lectureEditor dem Verhalten beim Export aus dem lecturePresenter entsprechen würde: Jedes Ein- und Ausschalten des zusätzlichen Folienrandes zählt als eine neue Folie. (Das mag auch nicht immer optimal sein, aber dabei geht zumindest nichts verloren. Überzählige Seiten entfernen bekommt man immer noch hirgendwie hin. Ich kann hier nur auf eine Stichprobenmenge von 1 verweisen, aber ich nutze den erweiterbaren Folienrand ganz gerne.)

**Comment by Andy-Schuerr** [comment]
Bei der Implementierung des von E. Lenz gewünschten Verhaltens ist was schief gegangen. Folgender Vorgang führt zu unerwarteten Ergebnissen:
- Foliensatz öffnen und Aufzeichnung starten
- eine handschriftliche Annotation erstellen
- Folienrand vergrößern und eine weitere Annotation erstellen (auf dem zusätzlichen Rand)
- Folienrand verkleinern und eine weitere Annotation erstellen
- Folienrand wieder vergrößern und eine weitere Annotation erstellen (auf dem zusätzlichen Rand)

Das im lecturePresenter (4.4.164) erstellte PDF enthält danach 198 Folien, von denen jeweils dutzende identisch.
Es scheint so, als ob jede Annotationsteilstrich zu einer eigenen Folie führt.
Das im lectureEditor (4.4.164) erstellte PDF enthält danach 1 Folie, auf der alle vier erstellten Annotationen
sichtbar sind (mit expandiertem Rand). Das ist plausibel, entspricht aber nicht dem von Herrn Lenz genannten
Wunschverhalten oben.
