### ISSUE TITLE
Editor (V 6.0.877): Update des Eventfensters nach Eventlöschen führt zu Flackern

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#826]
Wenn man im Eventfenster (in der Eventliste) ein Event löscht (Annotations-Stift-Event oder Stift-Lösche-Event) dann wird zwar jetzt die Eventliste aktualisiert, aber meistens flackert sie danach so lange bis man einmal durch Scrollen in der Timeline die entsprechende Seite mit der Eventliste verlassen hat und danach dort wieder hin zurückkehrt. Bei den ersten Versuchen mit einer kleinen Aufzeichnung konnte ich das Verhalten gar nicht beobachten, bei einer Aufzeichnung tritt das Flackern erst beim dritten oder vierten Löschen auf und bei einer anderen Aufzeichnung schon beim ersten Löschen eines beliebigen Events in der Liste.
[SE1-2023-10-18-2023_10_16-15_48.zip](https://github.com/lectureStudio/lectureStudio/files/12917682/SE1-2023-10-18-2023_10_16-15_48.zip)

**Comment by Andy-Schuerr** [comment]
Das Problem mit dem Flackern des Eventlisten-Unterfensters tritt bei mir immer genau dann auf, wenn die Liste so lange ist, dass ein Scrollbar angezeigt wird. Sobald man aus der Liste so viele Events gelöscht hat, dass kein Scrollbar mehr notwendig ist, ist das Fensterflackern weg. Das Problem tritt auch nur dann auf, wenn man über Seitengrenzen hinweg die Abspielmarke hin- und herschiebt. Sobald man einmal zwischen Render-Tab links oben und Eventlisten-Tab hin und her wechselt, ist das Flackern der Anzeige auch beendet.

**Comment by devopvoid** [comment]
Ich setzte es mal auf "done".

**Comment by Andy-Schuerr** [comment]
Der Fehler ist leider noch vorhanden. Er lässt sich bei mir wunderbar reproduzieren, wenn man das Editorfenster nicht maximiert und langsam in der Höhe größer und kleiner macht. Wenn man des Fenster größer macht und die Höhe ziemlich genau so gewählt ist, dass die Eventliste gerade noch vollständig angezeigt werden kann (ggf. man vom dem letzten Event nicht mehr alles sieht), dann fängt die Eventliste wie wild an zu "flackern".

**Comment by devopvoid** [comment]
Konnte es endlich reproduzieren mit einer Zoomstufe von 150% des Bildschirms.
