### ISSUE TITLE
Presenter (V 6.0.877): Es wird in der Teilnehmerliste nicht zwischen Hörsaalmodus und Daheim-Modus unterschieden

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#831]
Die Teilnehmerliste zeigt für Teilnehmer im Daheim- und Hörsaalmodus unterschiedslos das selbe Icon an (ein Hochhaus). 
Zudem zeigt die Anzeige für die Anzahl der Teilnehmer im Kurs mit dem Format "x+y" seltsame Werte an. Die Anzeige steht
immer bei "1+x" wobei x durchaus der Anzahl der Teilnehmer im Stream entsprechen könnte. Wofür steht die unveränderliche "1"?

**Comment by devopvoid** [comment]
Die Anzeige x + y bedeutet: x = Anzahl im "Zu Hause"-Modus, y = Im Hörsaal-Modus.
