### ISSUE TITLE
lectureEditor (4.4.118): beim pdf-Dokument speichern verbreiterter Folienränder mit anzeigen

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#86]
Beim Speichern einer Aufzeichnung als pdf-Dokument im lectureEditor werden nur dann die verbreiterten Folienränder mit abgespeichert, wenn man die Folie (das Whiteboard) mit verbreitertem Rand verlässt. Ich würde glaube ich eine Folie immer mit verbreitertem Rand speichern, wenn innerhalb des betrachteten Zeitabschnitts der Folienrand irgendwann verbreitert wurde.

**Comment by elenziat** [comment]
Ist das nicht das gleiche wie #82 ?

**Comment by devopvoid** [comment]
Duplicate of #82

**Comment by Andy-Schuerr** [comment]
Das funktioniert jetzt, der Bug-Report überlappt zudem mit einem anderen und kann deshalb "archiviert" werden.
