### ISSUE TITLE
Presenter/Meta: Possible Presenter glitch when zooming into a PDF slide

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#867]
**Describe the bug**
(To give some context: This bug happened at the end of yesterday's lecture.)

The lecturer zoomed into a slide. While selecting the zoom area the blue selection box got stock on the stream and was visible twice. (One time with a larger size.)
After the lecturer finished the selection of the zoom box, the stream showed the smaller (stuck) zoom box and some of the details on the slide were missing.

**To Reproduce**
1. Start a lecture stream with the Presenter.
2. Zoom into a slide.
(3. I don't know what triggered this bug :disappointed: )

**Expected behavior**
The zoom area should be the same for the beamer view and the stream view in every case.

**Screenshots**

A recreation of the zoom box look on the stream while the presenter selected the zoom area:
![ls-abgeschnitten-assoziation_sketch](https://github.com/lectureStudio/lectureStudio/assets/20956405/844c78d7-9201-4658-994d-b4aadb48d8dd)

The final view of the zoomed-in slide in the stream (the top part was missing!):
![ls-abgeschnitten-assoziation_censored](https://github.com/lectureStudio/lectureStudio/assets/20956405/fb7d52f6-8be9-4d3f-81e2-fd22e07efa3d)

**Desktop (please complete the following information):**
 - OS: Linux/Pop!_OS (Ubuntu-based) 22.04 (**client!**)

**Comment by Andy-Schuerr** [comment]
Unfortunately yet another unreproducible bug :-(.
