### ISSUE TITLE
lecturePresenter (6.0.905): Laser pointer duplicates during presentation

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#871]
**Describe the bug**
During a lecture in December 2023, the laser pointer functionality of the lecturePresenter did produce duplicates in laser points on the slides.
These duplicates were visible:
- on the beamer
- on the screen of the presenter
- in the stream
- in the recording

**To Reproduce**
1. Load a PDF slide set into the presenter
2. Use the laser pointer to show something
3. ???
4. Duplicate laser points in some rare cases

**Expected behavior**
The laser point should at most be visible once at any time.

**Screenshots**
Screenshot taken from the exported MP4 file of the recording:
![image](https://github.com/lectureStudio/lectureStudio/assets/20956405/b541bb96-fffe-4585-9325-f67b8fe34f5b)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build ??? (I can check and comment it if this information is critical for this bug.)

**Comment by Andy-Schuerr** [comment]
Das ist der bekannte Fehler bei Quizzen, wenn das Quiz-Dokument während der Nutzung des Laserpointers durch eintreffende Nachrichten neu generiert wird. In diesem Fall wurden Laserpointer-Annotationen in die neue Dokumentversion fälschlicherweise mit übernommen, sodass es dann zu Duplikaten kommt. Der Fehler ist inzwischen nicht mehr beobachtbar und damit (vermutlich) für alle Szenarien der Quiz-Durchführung behoben.
