### ISSUE TITLE
lecturePresenter (6.0.905): Slide distortion/wrong aspect ratio/broken slide show

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#872]
**Describe the bug**
During a lecture in December 2023, the slide show broke (as can be seen in the screenshot/photo below) in the presenter. We could not fix it and had to restart the whole stream/presenter application to correct the slide placement.

**To Reproduce**
1. Load a PDF slide set into the presenter
2. Present the slides
3. ???
4. See the broken slides in the presenter

(We do not really know what caused this bug, sorry.)

**Expected behavior**
That ... should not happen.

**Screenshots**
![23-12-20 15-34-46 3201](https://github.com/lectureStudio/lectureStudio/assets/20956405/cbd17126-12a6-49c7-928b-c93cccdeb5e5)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build ??? (I can check and comment it if this information is critical for this bug.)

**Additional context**
- As this bug occurred on my Lenovo laptop, there was a graphics tablet connected and actively used when the slide show broke.
- The exported slide set (with annotations) seems to look correct -> the yellow annotation is correctly positioned and the slide looks normal to me.

**Comment by Andy-Schuerr** [comment]
The bug also shows up when no graphics tablet is attached - once per term. Unfortunately, it is unreproducable and maybe somehow related to the also unreproducible rare bug that destroys/breaks the lecture recording service. New error messages are implemented that signal the occurrence of recording bug asking the user to close and restart the Presenter.
