### ISSUE TITLE
lectureStudio (4.4.118): Weiterhin bestehende Probleme mit schwarzen Artefakten / schnellem Zeichnen

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#88]
beim schnellen Zeichnen auf dem Whiteboard gibt es weiterhin folgende Probleme:

1) Aufzeichnung Whiteboard-Schwarze-Artefakte (in Hessenbox):
    - die Länge der Aufzeichnung ist korrupt; ich habe die Striche definitiv nicht in 0:00:01 Sekunden gezeichnet
    - das gerenderte Vektorformat enthält schwarze Artefakte

2) Aufzeichnung Whiteboard-Schwarze-Artefakte-1 (in Hessenbox):
   - beim Abspielen des Vektorformats in Firefox oder Edge kommen beide Browser an ihre Grenzen;
      in der Mitte der kurzen Aufzeichnung wird das Abspielen langsamer und langsamer und friert schließlich fast ein

Anbei die Log-Datei des Presenters (allerdings über eine ganze Reihe von Experimenten hinweg).
[presenter.log](https://github.com/lectureStudio/lectureStudio/files/6465572/presenter.log)

**Comment by devopvoid** [comment]
Duplicate of #74
