### ISSUE TITLE
Linux: Cannot interact with whiteboard on wayland

### ISSUE THREAD

**Issue by jomority** [lectureStudio/lectureStudio#9]
**Describe the bug**
When running the current lectureStudio (4.3.7) on linux under wayland (gnome), it is not possible to interact with the whiteboard, i.e. draw or write.
This was already shortly mentioned in #7 . It could have something to do with input coordinate mapping.

**To Reproduce**
1. Build the repository with `mvn install`
2. Extract the builded zip file
3. Run `./lecturePresenter`
4. Create a new whiteboard
5. Try to draw with the mouse
6. No lines appear on the whiteboard

**Expected behavior**
Lines should appear on the whiteboard.

**Desktop (please complete the following information):**
 - OS: Linux (Gnome on Wayland)

**Additional context**
I know that currently X11 is still the dominant display protocol on linux, but this will change in the future: Fedora uses [wayland as default for years](https://fedoraproject.org/wiki/Changes/WaylandByDefault), and Ubuntu will [switch too in the next version](https://www.omgubuntu.co.uk/2021/01/ubuntu-21-04-will-use-wayland-by-default).

**Comment by devopvoid** [comment]
There is currently just the X11 implementation for the stylus library: https://github.com/lectureStudio/stylus/tree/main/stylus-jni/src/main/cpp/dependencies/linux/x11

This will require the Wayland implementation. Any volunteers? 😄
