### ISSUE TITLE
Client (V 1.9.0-170): Zeilenvorschübe von Chat-Nachrichten werden im Client bei der Anzeige ignoriert

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#903]
Wenn man im Client Chat-Nachrichten eingibt mit Zeilenvorschüben (mit "return") um eine bestimmte/gewollte Formatierung zu erreichen, dann werden diese Zeilenvorschübe im Presenter und auf den Folien korrekt übernommen, aber bei der Anzeige im Chat-Verlauf des Clients selber eliminiert. Das irritiert den Schreiber einer Chat-Nachricht und macht die Nachrichten im Chat ggf. "unlesbar".

**Comment by Andy-Schuerr** [comment]
Die Zeilenvorschübe funktionieren jetzt, leider werden aber alle Leerzeichen rausgefiltert. Damit ist es immer noch nicht möglich mal im Chat einen Textblock mit in etwa vorgegebenem Layout zu erstellen (Alexander wollte eine Tabelle erstellen in der Art

    XXX   |   YYY
---------|---------
     a1    |    b1
     a2    |    b2

Die Leerzeichen aus dem obigen Textblock bleiben in der Presenteranzeige von Nachrichten erhalten, aber im Client-Chat und bei der Anzeige als Folie werden alle leider weggeworfen.

**Comment by devopvoid** [comment]
Im Client wird es richtig eingerückt. Im Presenter auf den Folien geht das leider nicht perfekt, hauptsächlich die Bindestriche sind verschoben wie oben im Beispiel.
