### ISSUE TITLE
Anregungen für neue "Window Capture"-Funktion im lecturePresenter

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#91]
Hier nochmal kurz die diskutierten "Features" für die "Window Capture"-Funktion:

* Das Einrichten einer Verbindung zu einem zu streamenden Bildschirm bzw. Fenster auf dem Bildschirm wird vom Streamen selbst entkoppelt.
* Zunächst kann eine solche Verbindung mit auswählbarer Qualität eingerichtet werden. Dabei wird das zu streamende Objekt ausgewählt und in einem eigenen Tab in der Folienvorschau als eigene Folie angezeigt. Diese Folie (PDF) zeigt einen Screendump des ausgewählten Fensters bzw. des ausgewählten Bildschirms.
* Bei der Qualitätauswahl sollte man zwei Aspekte berücksichtigen: benötigte Auflösung (niedrig bis hoch) und benötigte Dynamik = Bildrate. Bei der Übertragung eines Films wird man die Bildrate hochsetzen müssen und die Auflösung so niedrig wie nötig halten, bei der Übertragung eines im Wesentlichen statischen Fensterinhaltes wird man eher die Auflösung hochsetzen und die Bildrate niedriger halten.
* Frage: kann man - wie seit neuestem üblich - für diese generierte Folie ein Template auswählen? Wenn ja: dann sollte man auf dieser Folie wieder einen Bereich definieren können, in dem ein Screendump des entsprechenden Fensters oder Bildschirms angezeigt wird. Dieser ganze Bereich hat dann einen schwarzen Hintergrund auf dem der entsprechende Screendump platziert wird.
* Am unteren Ende der Folienvorschau werden "Player"-Knöpfe angeboten für Start und temporären Stop der eigentlichen "Window Capture"-Funktion für das entsprechende Objekt.
* Für das endgültige Beenden bzw. Löschen einer "Window Capture"-Verbindung könnte man den vertrauten "-"-Knopf des Whiteboards verwenden, mit dem dort Folien in der Folienvorschau gelöscht werden oder den üblichen "Player"-Knopf für das Beenden einer Aufzeichnung dafür nutzen.
* Bei aktivierter "Window Capture"-Funktion wird der betroffene Bildschirm- bzw. Fensterinhalt auf dem ausgewählten externen Monitor angezeigt (falls der aktiviert wurde) und gestreamt (falls ein Stream aktiv ist).
* Die "Window Capture"-Funktion muss also nutzbar sein, sobald die Anzeige auf einen externer Bildschirm eingeschaltet wurde oder aber ein Stream läuft (wenn beides abgeschaltet ist, dann macht "Window Capture" noch keinen Sinn, solange es nicht Bestandteil einer Aufzeichnung ist).
* Sobald die "Window Capture"-Funktion gestoppt wird, wird der gerade aktuelle Bildschirm- bzw. Fensterinhalt auf die generierte Folie übertragen. Diese Folie ist dann die aktuelle und wird angezeigt (auf dem externen Bildschirm bzw. im Stream). Sie kann dann ganz normal annotiert werden, ist Bestandteil des generierten PDFs, ... .
* Eine gestoppte "Window Capture"-Funktion kann wieder gestartet oder aber endgültig beendet werden. Wenn sie beendet wird, dann verschwindet der entsprechende Tab in der Folienvorschau.
* Der übertragene Inhalt eines ausgewählten Fensters oder Bildschirms wird auf einem schwarzen Hintergrund platziert.
* Wenn die Verbindung kurzzeitig stockt beim Streaming, dann wird nicht eine andere Folie, sondern das eingefrorene Bild angezeigt.
* Wenn eine "Window Capture"-Verbindung gelöscht bzw. endgültig beendet wird, dann verschwindet die entsprechende Folie aus der Folienvorschau.

Erweiterungsideen für später (falls überhaupt realisierbar):
* Bei der Aktivierung der "Window Capture"-Funktion wird der Presenter minimiert (und wenn ein Fenster und kein ganzer Bildschirm das ausgewählte Objekt ist dann ggf. diese Fenster deminimiert und in den Fokus geholt wenn das möglich ist).
* Wenn die "Window Capture"-Funktion aktiv ist, dan bekommt das ausgewählte Fenster bwz. der ausgewählte Bildschirm einen grünen Rahmen drum herum.
* Das Minimieren eines gerade übertragenen Fensters stoppt - wenn möglich - automatisch die "Window Capture"-Funktion
(und maximiert den Presenter?)
* Man kann nicht nur "Window Capture" für einen Bildschirm oder ein Fenster vorbereiten, sondern für beliebig viele. Für jede vorbereitete "Window Capture"-Verbindung gibt es in der entsprechenden Folienvorschau eine eigene Folie. Mit den für das Whiteboard üblichen "+" und "-"-Knöpfen kann man das Einrichten einer neuen "Window Capture"-Verbindung starten bzw. eine existierende Verbindung löschen.
* * Wenn ein gestreamtes Fenster gelöscht wird (ggf. auch wenn, der zu übertragende Bildschirm "abgehängt" wird), dann wird - wenn möglich - eine Übertragung beendet und die entsprechende "Window Capture"-Verbindung gelöscht.

**Comment by devopvoid** [comment]
Das klingt nach einer sehr guten Idee. Auch alles wie beschrieben machbar, außer die Sache mit dem Eingabefokus von Fenstern. Da müsste man schauen, ob es mit Java ohne großen Aufwand möglich ist.

> wenn der entsprechende Tab (bzw. die aktuelle Seite) zu einem "geöffneten" Fenster der (die) aktive ist, dann wird im
> zentralen Bereich des lecturePresenters der Fensterinhalt gespiegelt angezeigt

Das müsste getestet werden. Der Erfahrung nach, sollte das nicht viel Rechenzeit "verschlingen".

**Comment by Andy-Schuerr** [comment]
Beim nochmal drüber nachdenken macht das kontinuierliche Spiegeln des Fensterinhaltes glaube ich keinen Sinn. Das ist nur wieder eine mögliche Fehlerquelle und ... . Ich glaube es reicht:

* Status "Window-Capture active": im zentralen Fensterbereich von lecturePresenter wird der Zustand des mitgeschnittenen Fensters angezeigt, der bei Aktivierung dieses Zustands gerade sichtbar war. Dabei wird "irgendwie" sehr klar visualisiert, dass
 man nicht mit diesem Fenster gerade interagieren sollte, sondern mit dem mitgeschnittenen Fenster (Inhalt wird sehr blass
dargestellt oder eine fette Textanzeige, die drübergelegt wird, weißt darauf hin oder ... . Gleichzeitig macht es vielleicht sogar
Sinn, dass alle Interaktionsmöglichkeiten mit lecturePresenter inaktiv sind außer der Knopf, der das Mitschneiden beendet
(wenn das nicht automatisiert durch Fokuswechsel zwischen Fenstern passiert). Oder radikaler Vorschlag so wie bei Zoom:
das lectureStudio-Fenster verschwindet ganz und stattdessen erscheint ein Rahmen um das mitgeschnittene Fenster?

* Status ""Window-Capture inactive": der entsprechende Tab bzw. die entsprechende Seite, die das Fenster repräsentiert,
   das mitgeschnitten werden kann, enthält einen "Screendump" des Zustandes des Fensters, der beim Wechsel von
   "active" nach "inactive" gerade aktuell war. Dann kann man diesen Zustand besprechen, annotieren, ... .

ACHTUNG: man muss sich überlegen was passiert, wenn in lectureStudio der Zugriff auf ein externes Fenster "geöffnet" ist,
aber das entsprechende Fenster "dummerweise" geschlossen wird. Kann man das über einen "Event" mitbekommen?
Es macht Sinn trotzdem den zugehörigen Tab/Seite in lecturePresenter offen  zu lassen, da man den sichtbaren Screendump
ja vielleicht annotieren will. Aber der Übergang von "inactive" zu "active" sollte dann nicht mehr möglich sein!

**Comment by devopvoid** [comment]
> Gleichzeitig macht es vielleicht sogar Sinn, dass alle Interaktionsmöglichkeiten mit lecturePresenter inaktiv sind außer der Knopf, der das Mitschneiden beendet

Das - denke ich - ist ganz wichtig, kann sonst passieren, dass im Hintergrund das Fenster ungewollt weiter aufgezeichnet wird.

> Status ""Window-Capture inactive": der entsprechende Tab bzw. die entsprechende Seite, die das Fenster repräsentiert,
> das mitgeschnitten werden kann, enthält einen "Screendump" des Zustandes des Fensters, der beim Wechsel von
> "active" nach "inactive" gerade aktuell war. Dann kann man diesen Zustand besprechen, annotieren, ... .

Wie soll die Funktion mit dem "Screendump" sich in der Aufzeichnung verhalten? Das wäre ja dann eine Whiteboard-Seite mit einem Bild, die wie üblich im Folienstrom auftaucht, samt möglichen Annotationen.

**Comment by Andy-Schuerr** [comment]
**Frage**: Wie soll die Funktion mit dem "Screendump" sich in der Aufzeichnung verhalten? Das wäre ja dann eine Whiteboard-Seite mit einem Bild, die wie üblich im Folienstrom auftaucht, samt möglichen Annotationen.

**Antwort**: Ganz genau! Exakt die gleiche Verhaltensweise wie bei Whiteboardseiten in jeder Hinsicht wäre sinnvoll (bei der Navigation zwischen Folien, Whiteboard-Seiten und diesen neuen Fenster-Seiten; bei der Anzeige im Folienstrom rechts im Presenter, Editor und Player; bei dem Export nach pdf im Presenter und im Editor, … ). Im Grunde ist das tatsächlich nur eine Whiteboard-Seite mit einem vorgegebenen und sich von Zeit zu Zeit ändernden Hintergrundbild (jeweils bei Aktivierung und Deaktivierung des Mitschnitts).
So langsam frage ich mich, ob es dann nicht sinnvoll wäre, keinen neuen Tab einzuführen im Presenter für die mitzuschneidenden Fenster, sondern einfach eine neue Art von Whiteboard-Seite mit der Option  bei der Erzeugung einer Whiteboard-Seite entweder eine normale „passive“ Whiteboard-Seite zu erzeugen oder eine neue Live-Whiteboard-Seite, die an einem externen Fenster „dranhängt“ und deren Hintergrundinhalt durch das dazu gehörende externe Fenster bestimmt wird.

**Comment by Andy-Schuerr** [comment]
Habe ich fürchte ich kein Gefühl dafür was einfacher oder schwieriger ist. Müssen Sie zusammen mit den Projektseminarteilnehmern entscheiden!

Von: Alex Andres ***@***.***>
Gesendet: Donnerstag, 20. Mai 2021 16:53
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] Anregungen für neue "Window Capture"-Funktion im lecturePresenter (#91)


eine neue Art von Whiteboard-Seite mit der Option bei der Erzeugung einer Whiteboard-Seite entweder eine normale „passive“ Whiteboard-Seite zu erzeugen oder eine neue Live-Whiteboard-Seite

Wäre das aber nicht für Dozenten/-innen komplizierter zu nutzen, statt kontext-basierte Tabs?

**Comment by Andy-Schuerr** [comment]
Nochmal neue Idee zum Screensharing: Auch BBB und Zoom haben so ihre Schwierigkeiten eine intuitive Benutzeroberfläche für das Screensharing anzubieten. Es bleibt immer das Problem, dass man einerseits mit einem geteilten (Werkzeug-)Fenster oder gesamten Bildschirm ganz normal interagieren will, andererseits aber doch Funktionen zur Kommentierung von Bildschirminhalten oder zur Interaktion mit den Teilnehmer:innen eines Streams zusätzlich zur Verfügung stehen müssen. Zoom versucht das Problem dadurch zu lösen, dass es einen grünen Rahmen um einen geteilten Bildschirm herum legt und eine minimale zusätzliche Werkzeugleiste anbietet (extrem nervig dabei ist, dass bei dabei das mühsam aufgebaute Layout von Teilnehmer- und Chat-Fenster erst mal zerstört wird und jedes Mal wieder neu angelegt werden muss).

Frage: kann man vielleicht doch den Inhalt eines "geteilten" Fensters in hinreichend guter Qualität (Auflösung, Wiederholrate) in den Folienanzeigebereich von lectureStudio spiegeln und Maus-Events auf dem lectureStudio-Folienanzeigebereich an das gespiegelte Fenster durchreichen? Wenn das technisch möglich wäre (und die Auflösung und Wiederholrate ausreichend für eine Interaktion mit einem Werkzeugfenster über seine gespiegelte Anzeige in lectureStudio möglich wäre), dann könnte man die Oberfläche wie folgt gestalten:

* Für ein geteiltes Fenster wird wie bisher geplant ein eigener Tab rechts in der Folienvorschau angelegt. Durch Wechsel der Tabs kann man sehr bequem zwischen Ansicht der "normalen" Folien und zusätzlichen geteilten Werkzeugfenstern hin- und herwechseln. 
* Ein gerade geteiltes Fenster wird im Hauptanzeigebereich des lecturePresenters angezeigt (wenn der entsprechende Tab ausgewählt wurde) und Mausevents innerhalb dieses Anzeigebereichs werden im Normalmodus dann an das Fenster bzw. die dahinter liegende Anwendung durchgereicht.
* Im Kommentiermodus (gibt es bei Zoom auch über die zusätzliche Werkzeugleiste) werden die Maus-Events nicht durchgereicht, sondern es wird ein Snapshot des bisher laufend aktualisierten geteilten Fensterinhalts erzeugt, der anschließend wie eine normale Folie behandelt wird (annotiert werden kann etc.). 

Wenn sowas technisch möglich ist, könnte man sich so das nervige Hin- und Herwechseln zwischen der Presenter-Oberfläche und einem geteilten Fenster sparen. Das wäre insbesondere dann von großem Vorteil, wenn man im Hörsaal steht und nur einen Bildschirm zur Verfügung hat (statt geteiltes Fenster und Presenter-Oberfläche mit Anzeige von Textnachrichten, Meldungen etc. über mehrere Bildschirme verteilen zu können).

Vorhersehbare Probleme mit einer solchen Lösung:
* Die Bildwiederholrate und Auflösung der Anzeige des geteilten Fensters im Presenter muss sehr hoch sein, damit die Interaktion mit einer Anwendung über ihre in gespiegelte Ansicht hinreichend gut funktioniert.
* Es steht für Anwendung bzw. das geteilte Fenster nur ein Teil der Bildschirmoberfläche zur  Verfügung (weil im Presenter zusätzlich die platzraubende Folienvorschau und die Textnachrichten der Teilnehmer:innen etc. angezeigt werden muss).
* Es wird eine "Kunst" sein, die Größe des geteilten Fensters genau so auszuwählen, dass der im Presenter zur Anzeige zur Verfügung stehende Platz optimal genutzt wird (automatische Anpassung der Fenstergröße an den zur Anzeige zur Verfügung stehenden Platz)?!

**Comment by Andy-Schuerr** [comment]
Dieser Issue hat sich erledigt, die Screensharing-Funktion gibt es inzwischen - teilweise etwas anders als hier skizziert realisiert. Für fehlende Funktionalitäten gibt es eigene neue Issues.
