### ISSUE TITLE
Presenter (V 6.1.940): In Aufzeichnung fehlen alle Events

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#912]
Bei einer Vorlesung am 2. Mai 2024 wurden (fast) von Anfang an alle Folienfortschaltevents, die sich auf das Haupt-PDF mit den Folien bezogen, nicht in der Aufzeichung des Termins gespeichert. Als Folge davon, enthält das generierte PDF nur die ersten Folien des Termins sowie generierte Quiz- und Hörsaal-Folien. Zudem ist die Aufzeichung für die Erzeugung eines Videos unbrauchbar, da sie zwar eine vollständige Audiospur enthält, aber alle Folienfortschalt-Events fehlen.

Die Log-Datei enthält viele "Create Page Failed"-Meldungen (4 Minuten nach Präsentationsbeginn kommt die erste Meldung dieser Art), die sich allerdings an der Benutzeroberfläche nicht bemerkbar gemacht haben (ich konnte ganz normal präsentieren, streamen, ... ). Meine Vermutung: die Meldungen wurden durch die fehlgeschlagenen Versuche PDF-Seiten zu speichern (für die PDF-Dokumente, die man am Ende des Termins abspeichern kann und die ja sehr unvollständig waren) ausgelöst?!

Dieser Fehler lässt sich mit den für die Vorlesung verwendeten Dokumenten nicht reproduzieren. Einziger Verdacht: ich hatte vor Vorlesungsbeginn eine White-Board-Seite geöffnet, um vor Vorlesungsbeginn darauf was zu schreiben. Das habe ich aber gleich wieder gelöscht (und noch vor Vorlesungsbeginn von der White-Board-Seite wieder auf die erste Folie der Vorlesung die Anzeige umgestellt). Das ist der einzige mir bekannte Unterschied zu anderen Präsentationen in letzter Zeit, bei denen die Aufzeichnung immer funktioniert hat.

[presenter-6.1.940-02-05-2024.log](https://github.com/lectureStudio/lectureStudio/files/15246686/presenter-6.1.940-02-05-2024.log)

Idee: vermutlich wird sich die Fehlerursache nicht einkreisen lassen?! Es wäre aber hilfreich, wenn in solchen Fällen Warnungen auf der Oberfläche ausgegeben würden. Dann könnte man die Vorlesung kurz unterbrechen und den Presenter einfach neu starten (und im Nachhinein dann die Aufzeichnungen soweit vorhanden zusammenfügen).

**Comment by devopvoid** [comment]
Anzeigen einer Fehlermeldung ist realisiert. Den Fehler ganz zu beheben bedarf es viel Zeit, um die Handhabung mit PDFs und deren Aufzeichnung threadsicher zu machen.

Setze es erstmal auf "done".
