### ISSUE TITLE
Presenter (V 6.1.940): Scrollrad der Maus wirkt nicht im Hauptfenster zum Folien-Blättern

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#916]
Wenn der Mauszeiger sich nicht über der Folienvorschau im Presenter, sondern im Hauptfenster über den Folien befindet, dann werden Scroll-Rad-Events der Maus ignoriert (anders als im Folienvorschaufenster). Das hat mich bei der Durchsicht der Folien im Büro vor Beginn der Vorlesung auch schon öfter irritiert (wie jetzt Björn Scheuermann).

Abhilfe:
Das Scrollrad hat genau die gleiche Funktionalität im Hauptfenster des Presenters, in dem die aktuelle Folie angezeigt wird, wie im Folienvorschaufenster.

**Comment by Andy-Schuerr** [comment]
Bitte bei Björn nachfragen, wie er sich die Reaktion auf das "Scrollrad" im Hauptfenster gewünscht hat. Nur als Vor- und Zurückblättern in der Folienvorschau oder aber als Vor- und Zurückblättern im Hauptfenster (also wie nächste/vorherige Folien-Key im Hauptfenster der Folienansicht). Ich hatte jetzt beim Ausprobieren letzteres erwartet und war verblüfft, dass im Hauptfenster die Folie nicht weitergeblättert wird.

**Comment by Andy-Schuerr** [comment]
Meine Meinung dazu: ich erwische mich auch immer wieder dabei, dass ich bei der Durchsicht der Folien im Presenter am Schreibtisch das Scrollrad der Maus versuche zu benutzen (wie sonst auch in anderen Tools). Ich bin jedes Mal dabei wieder verblüfft, dass sich bei der Position der Maus über dem Hauptfenster nur in der Folienvorschau weitergeblättert wird. 

Deshalb wäre mein Vorschlag: 
1) Mauszeiger über der Folienvorschau: Verhalten bleibt so wie es ist.
2) Mauszeiger über dem Hauptfenster mit der aktuell angezeigten Folie: das Scrollrad blätter im Hauptfenster vor und zurück.

**Comment by devopvoid** [comment]
Ich stelle es gerne auf Option 2 um!

**Comment by Andy-Schuerr** [comment]
Wunderbar, jetzt ist es intuitiv so wie man das erwartet!
