### ISSUE TITLE
Presenter (V6.1.957): Fonts für Textnachrichten-Folien sind in Acrobat nicht bekannt

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#923]
Die jetzt verwendeten Fonts für die Erzeugung von Textnachrichten-Folien haben folgenden gravierenden Nachteil: 
Wenn man die entsprechende Folie aus der Aufzeichnung exportiert, um beispielsweise mit Acrobat einen Tippfehler in der Textnachricht zu korrigieren, dann steht der verwendete Font nicht zur Verfügung. Sprich: man muss erst mal den Font des Textes komplett ändern bevor man darin sinnvoll korrigieren kann. Fehlt da die Einbettung des verwendeten Fonts im Dokument und/oder kann man nicht einen Font verwenden, den Acrobat von sich aus kennt?

**Comment by devopvoid** [comment]
Es liegt vermutlich daran, dass nur der Zeichensatz des Fonts in das PDF exportiert wird, der tatsächlich im Text verwendet wird. Mit dem PDF-Exchange Editor funktioniert das aber. Muss daher mal schauen, warum Acrobat das nicht.

**Comment by Andy-Schuerr** [comment]
Nachtrag: der Font ist Acrobat 2017 bekannt, der für die Nachricht verwendet wird. Aber er ist ausgegraut und kann nicht selektiert und nicht für das Tippen neuer Buchstaben verwendet werden. Einzige Lösung: man selektiert irgendeinen der anderen in Acrobat angebotenen Fonts für den ganzen Text der Nachricht und korrigiert dann.
