### ISSUE TITLE
lecturePresenter (4.4.126): Fehler im Live-Stream-Broadcast-Dialog und Verbesserungsvorschläge

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#94]
ERLEDIGT: Wenn ich in den Dialog Einstellungen/Live Stream (mit bereits vorher existierender Einstellungsdatei) gehe, dann ist dort die Auswahlbox für bereits existierende Profile "leer". Wenn ich dann ein neues Profil anlege, dann existieren danach auf einmal auch die Profile "Local" und "ETiT Cloud". Wenn ich vorher die Einstellungsdatei lösche, dann werden sofort die neuen Profile angezeigt.

Erweiterungswünsche für den Dialog (ERLEDIGT): 
- Profile sollten auch wieder gelöscht werden können. 
- Das Anlegen eines Profils mit leerem Namen sollte nicht möglich sein (habe ich aus Versehen gemacht)
- Die Parameter (IP-Adresse, ... ) eines ausgewählten Profils sollten sichtbar sein (damit man es kontrollieren kann oder ... )

Noch Verbesserungwünsche für das Editieren der Profile (aus Kommentar hierher hochkopiert, also NEU): 
-mit "Hinzufügen" wird eine Zeile mit leerem Namen hinzugefügt. Das muss man erst mal kapieren und dann auf diese Zeile klicken um sie zu editieren. Vielleicht wird das klarer, wenn man einen Default-Namen einträgt wie "Neues Profil" ("New Profile") und/oder gleich das Editieren der neuen Zeile aktiviert?
- Und: die Oberfläche macht nicht klar, dass die grau markierte Zeile das aktuell ausgewählte Profil ist. Das ist nicht selbsterklärend. Das kann man im Manual natürlich erläutern und damit das Problem eliminieren. Alternative Idee?

**Comment by Andy-Schuerr** [comment]
Noch ein Verbesserungwunsch für das Editieren der Profile: mit "Hinzufügen" wird eine Zeile mit leerem Namen hinzugefügt. Das muss man erst mal kapieren und dann auf diese Zeile klicken um sie zu editieren. Vielleicht wird das klarer, wenn man einen Default-Namen einträgt wie "Neues Profil" ("New Profile") und/oder gleich das Editieren der neuen Zeile aktiviert?

Und: die Oberfläche macht nicht klar, dass die grau markierte Zeile das aktuell ausgewählte Profil ist. Das ist nicht selbsterklärend. Das kann man im Manual natürlich erläutern und damit das Problem eliminieren. Alternative Idee?

**Comment by devopvoid** [comment]
> Noch Verbesserungwünsche für das Editieren der Profile (aus Kommentar hierher hochkopiert, also NEU):
> -mit "Hinzufügen" wird eine Zeile mit leerem Namen hinzugefügt. Das muss man erst mal kapieren und dann auf diese Zeile klicken um sie zu editieren. Vielleicht wird das klarer, wenn man einen Default-Namen einträgt wie "Neues Profil" ("New Profile") und/oder gleich das Editieren der neuen Zeile aktiviert?

> Und: die Oberfläche macht nicht klar, dass die grau markierte Zeile das aktuell ausgewählte Profil ist. Das ist nicht selbsterklärend. Das kann man im Manual natürlich erläutern und damit das Problem eliminieren. Alternative Idee?

Beides nachgeholt. Aktives Profil wird im Label über der Tabelle angezeigt.
