### ISSUE TITLE
Editor (V 6.1.979): Scrollen durch eine Aufzeichnung eines Fensters zeigt leeres Fenster

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#946]
Als Beispiel für Screenshares nutze ich immer VisualParadigm und erstelle damit Klassendiagramme. Wenn ich eine Aufzeichnung im Editor abspielen lasse, dann sehe ich im Editor-Hauptfenster wunderbar das Editieren des Klassendiagramms. Wenn aber durch den entsprechenden Teil der Aufzeichnung durchscrolle, dann sehe ich immer ein leeres Fenster, also den Anfangszustand des Screenshares. Die Aufzeichnung dazu zum Testen lege ich wieder an die übliche Stelle in die Hessenbox.

**Comment by devopvoid** [comment]
Das Scrollen ist jetzt wieder langsamer, aber präziser. Man müsste hier noch einen Kompromiss finden.

**Comment by Andy-Schuerr** [comment]
Das Scrollen ist immer noch "buggy", siehe anderen Issue dazu. Prinzipiell scheint es aber zunächst mal zu funktionieren.
