### ISSUE TITLE
Presenter/Editor (V 6.1.979): Annotationen auf Folien vor einer Screenshare-Demo werden über das Screenshare-Video drübergelegt

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#952]
Bei der Behandlung von Annotationen auf generierten Screenshare-Folien gibt es noch einen logischen Fehler (aber vielleicht ist das ja auch kein Bug, sondern ein Feature?):

* Wenn man eine generierte Folie annotiert (handschriftlich oder mit Text) und dann das Screensharing startet, dann sind im Video natürlich (im Presenter und auf dem Beamer ... ) die zuvor erzeugten Annotationen nicht zu sehen.

* ABER: wenn man dann im Editor die Aufzeichnung öffnet und abspielt, dann sieht man die Annotationen der generierten Folie auch im Video als Overlay. Das fällt erst mal gar nicht so auf, weil sie dort an genau den gleichen Stellen positioniert sind wo sie vorher auf der Folie waren. In der Nachbearbeitung könnte man die Annotationen auch beim Videobeginn löschen und damit entfernen wenn sie stören.

Sinnvoller wäre aber vermutlich, wenn in der Aufzeichnung jeder Beginn eines Screenshare-Videos wie ein Folienwechsel behandelt würde (und auch als Folienwechsel angezeigt würde). Das hätte glaube ich viele Vorteile: man das Video auf einen Schlag löschen mit dem "Folienlöschen"-Kommando. Die Annotationen wären "weg" wie bei der Präsentation selbst mit dem Presenter, etc. Ein Problem bei dieser Lösung mit zusätzlichen Folienwechsel-Events wäre, dass man dafür vermutlich keine Seiten beim PDF erzeugen im Editor erzeugen sollte, da es bereits die generierten Folien vor und nach dem Video gibt.

**Comment by devopvoid** [comment]
Das ist eine gute Idee Screenshare-Videos wie Folienwechsel zu behandeln. Damit hätten wir ein einheitliches Verhalten in der Aufzeichnung. Das muss ich genau durchdenken und dann zusammen mit #905 erledigen.
