### ISSUE TITLE
lecturePresenter (4.4.126): Verbindungsaufbau mit lokalen Server funktioniert bei mir nicht

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#96]
Wenn ich den lokalen Server starte und dann vom selben Rechner oder vom Smartphone im selben WLAN-Netz aus im Browser die angezeigte IP eingebe, dann lande ich auf einer Seite mit rotem Rand oben und einem angezeigten Wort "Forbidden". Was mache ich da falsch?

**Comment by devopvoid** [comment]
Da ist wahrscheinlich die IP-Adresse im IP-Filter nicht eingetragen. In den Einstellungen - Netzwerk gibt es eine IP-Filter-Tabelle. Dort sind einige standardmäßige IP-Adressbereiche eingetragen. Kann sein, dass Ihre IP-Adresse sich im Adressbereich etwas unterscheidet. Zum Beispiel 192.168.**2**.XYZ statt 192.168.**0**.XYZ.

**Comment by Andy-Schuerr** [comment]
Was für IP-Adresse(n) muss ich in dem Filter eintragen? Die des Rechners, auf dem der Server läuft, oder die der Clienten, die sich damit verbinden wollen? Wenn letzteres: dann muss ich doch irgendwie "Wildcards" benutzen können, damit ich nicht die ganzen IP-Adressen von allen möglichen Clients eintippen muss. 

Zudem: weder das Hinzufügen noch das Löschen von IP-Adressen im Filterbereich funktioniert bei mir.

**Comment by Andy-Schuerr** [comment]
Der Start des lokalen Servers funktioniert bei mir nicht (mehr). Ich vermute mann muss dafür in den Einstellungen den lokalen Server auswählen und das war's eigentlich? Bei mir sind die Parameter für den lokalen Server, die voreingestellt sind:
IP-Adresse: 0.0.0.0, Port: 80, SSL/TLS Port: 443.

**Comment by Andy-Schuerr** [comment]
... und mir ist immer noch nicht klar was ich für IP-Adressen auf der Filterseite angeben muss.

**Comment by devopvoid** [comment]
Ja, dazu muss in den Stream-Einstellungen in der Tabelle die Zeile für den lokalen Server ausgewählt werden. In Windows kann Port 80/443 betrieben werden. Unter Linux/Mac steht da Port 8080/8443 für nicht Root-User.

**Comment by devopvoid** [comment]
> und inzwischen ist mir glaube ich klar, was ich als IP-Adressbereich in der IP-Filter-Liste angeben muss:
> Den Adressbereich der Client-Geräte, die sich mit dem Quiz verbinden wollen.

Genau. In der letzten Version (4.4.136) steht da nun der folgende Text über der Tabelle:
**Geben Sie die IP-Adressbereiche an, die Zugriff auf die Web-Services erhalten sollen.**

**Comment by Andy-Schuerr** [comment]
Habe ich gesehen und genau das hat mir weitergeholfen!

Von: Alex Andres ***@***.***>
Gesendet: Samstag, 22. Mai 2021 13:27
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] lecturePresenter (4.4.126): Verbindungsaufbau mit lokalen Server funktioniert bei mir nicht (#96)


und inzwischen ist mir glaube ich klar, was ich als IP-Adressbereich in der IP-Filter-Liste angeben muss:
Den Adressbereich der Client-Geräte, die sich mit dem Quiz verbinden wollen.

Genau. In der letzten Version (4.4.136) steht da nun der folgende Text über der Tabelle:
Geben Sie die IP-Adressbereiche an, die Zugriff auf die Web-Services erhalten sollen.

**Comment by Andy-Schuerr** [comment]
Diese Zeile habe ich ausgewählt mit den „Local Server“-Angaben und jetzt kann ich den lokalen Server nicht mehr starten (in der letzten Version ging es noch bei mir).

Von: Alex Andres ***@***.***>
Gesendet: Samstag, 22. Mai 2021 13:24
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] lecturePresenter (4.4.126): Verbindungsaufbau mit lokalen Server funktioniert bei mir nicht (#96)


Ja, dazu muss in den Stream-Einstellungen in der Tabelle die Zeile für den lokalen Server ausgewählt werden. In Windows kann Port 80/443 betrieben werden. Unter Linux/Mac steht da Port 8080/8443 für nicht Root-User.

**Comment by devopvoid** [comment]
Vielleicht in der Tabelle zu "Local" die Ports 8080 und TLS 8443 ausprobieren? Haben Sie Logs dazu?

**Comment by Andy-Schuerr** [comment]
Hallo,

diese Umstellung hilft leider auch nichts. Anbei die Log-Datei von heute, in der ich nur
den Presenter gestartet, die Einstellungen wie unten vorgeschlagen abgeändert habe
und dann versucht habe den Messenger zu starten.

Viele Grüße

              Andy Schürr

Von: Alex Andres ***@***.***>
Gesendet: Samstag, 22. Mai 2021 13:50
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] lecturePresenter (4.4.126): Verbindungsaufbau mit lokalen Server funktioniert bei mir nicht (#96)


Vielleicht in der Tabelle zu "Local" die Ports 8080 und TLS 8443 ausprobieren? Haben Sie Logs dazu?

**Comment by Andy-Schuerr** [comment]
Der Timeout ist in manchen Fällen immer noch zu kurz auf meinem Rechner. Entweder den Timeout also nochmal verlängern oder es umstellen auf: beim Verbindungsaufbau geht ein Dialogfenster  mit "Abort"-Button, das so lange offen bleibt bis entweder der Verbindungsaufbau geklappt hat oder er manuell abgebrochen wird.
