### ISSUE TITLE
Beenden von Quizzen funktioniert nicht in lecturePresenter (4.4.126)

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#98]
Folgende Abfolge von Aktionen führt zu Problemen:
1) Ein Quiz wird in lecturePresenter gestartet.
2) lecturePresenter wird beendet ohne das Quiz explizit zu beenden.
3) Danach wird das Quiz immer noch im Browser angezeigt als laufend.
4) lecturePresenter wieder starten und ein neues Quiz starten.
5) Refresh im Browser zeigt nun das neue Quiz an.
6) Der Versuch in lecturePresenter dieses neue Quiz explizit zu schließen wird mit einer Fehlermeldung "Quiz kann nicht geschlossen werden" quittiert.
7) Danach ist in der Presenter-Oberfläche "Quiz schließen" ausgegraut und "Quiz starten" anwählbar, aber:
   der Versuch ein neues Quiz zu starten wird ebenfalls mit Fehlermeldung quittiert.
8) Schließen und Neustarten des lecturePresenter hilft! Dann kann man wieder einen Quiz starten.

Danach ist der Quiz-Server aber endgültig durcheinander. Er zeigt einen Quiz an, der eigentlich nicht mehr laufen sollte
(nach Refresh). Wenn man in diesem Quiz eine Option selektiert und sendet, kommt die Fehlermeldung "Nur eine Antwort pro Quiz" möglich. Vielleicht ist das sogar konsequent, weil mein Client schon vorher den eigentlich beendeten Quiz beantwortet hat.

**Comment by Andy-Schuerr** [comment]
Das Beenden des Messengers und von Quizzen funktioniert in der neuen Version 4.4.126 immer noch nicht bzw. neu nicht mehr. IN beiden Fällen kommen Fehlermeldungen - egal ob Messenger und Quizze parallel laufen oder nur alleine.

**Comment by devopvoid** [comment]
Meinten Sie die Version 4.4.136? Irgendwie kann ich das nicht reproduzieren. Das oben beschriebene Verhalten ist mit der Version 4.4.136 nicht mehr reproduzierbar.

**Comment by Andy-Schuerr** [comment]
Ja, da habe ich mich vertippt! Leider habe ich mit Version 4.4.136 exakt das gleiche Verhalten ☹.

Von: Alex Andres ***@***.***>
Gesendet: Samstag, 22. Mai 2021 13:30
An: lectureStudio/lectureStudio ***@***.***>
Cc: Schürr, Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [lectureStudio/lectureStudio] Beenden von Quizzen funktioniert nicht in lecturePresenter (4.4.126) (#98)


Meinten Sie die Version 4.4.136? Irgendwie kann ich das nicht reproduzieren. Das oben beschriebene Verhalten ist mit der Version 4.4.136 nicht mehr reproduzierbar.
